### ISSUE TITLE
Error al calcular precio por productos

### ISSUE THREAD

**Issue by elleiton** [whooohq/whq-woocommerce-chilexpress-shipping#1]
Hola que tal chicos, primero que todo gracias por la colaboración, casualmente encontré el plugin :) . Queria comentarles que al aplicarlo en mi sitio y comprar 2 o más productos en el valor del envío se suma por cada producto de forma individual, me imagino que lo correcto sería sumarlo a un mismo envío, de está manera el precio estaría acorde al paquete que se enviará y no por separado. Espero poder ayudar con  el comentario. Sldos.-

**Comment by jhoynerk** [comment]
Hola @elleiton gracias por comentarnos sobre este problema, nos podrias enviar mas información sobre el caso de prueba que realizaste. Para ver si podemos resolver este problema. Saludos.

**Comment by elleiton** [comment]
- En la imagen de ejemplo, al realizar el pago del producto se calcula correctamente el valor del envío por el total de productos que en este caso sería 1.
![imagen](https://user-images.githubusercontent.com/26824324/27757885-f6880e10-5dd5-11e7-86ec-68f5dafb9b9f.png)


- Sin embargo, al realizar el pago de 3 productos (a la misma dirección), el valor del envío lo calcula por cada producto de forma individual. Lo correcto sería realizar el calculo en un mismo envío para los tres productos, serían alrededor de $3.200. La solución me imagino que sería sumando el peso y las medidas dependiendo de la cantidad que compre el usuario.
![imagen](https://user-images.githubusercontent.com/26824324/27757889-240b7444-5dd6-11e7-9b8c-76a36c742cf4.png)

Espero haber ayudado. Sldos.

**Comment by jhoynerk** [comment]
@elleiton recuerda amigo que cada producto ocupa un volumen (Kg y Dimensiones), puede ser que el calculo de este volumen este correspondiente al monto que se le indica. Por favor verificar en el cotizador de [Chilexpress](http://www.chilexpress.cl/cotizador-envios-de-encomiendas-tarifas) y comenta cual es el monto que le cotizo. Saludos.

**Comment by elleiton** [comment]
Ya perro capa8 error mio, hice varias pruebas y está todo correcto saludos.-
