### ISSUE TITLE
Strict Standards: Non-static method WC_WHQ_Chilexpress_Shipping::get_chilexpress_option() should not be called statically

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#10]
Estimados,

Al momento de seleccionar ciudad y region se me llena la pagina de este error o warning 👍 

Strict Standards: Non-static method WC_WHQ_Chilexpress_Shipping::get_chilexpress_option() should not be called statically in /var/www/html/wp-content/plugins/woo-chilexpress-shipping/includes/woocommerce.php on line 21

Strict Standards: Non-static method WC_WHQ_Chilexpress_Shipping::get_chilexpress_option() should not be called statically in /var/www/html/wp-content/plugins/woo-chilexpress-shipping/includes/woocommerce.php on line 22

El campo donde está el producto queda cargando sin hacer nada mas.

Tengo PHP 5.6 , adjunto screenshot de como se ve la pagina : 

https://i.gyazo.com/6c2658a6da983aecf6a5272ad15eaba3.png

El mensaje de la cabecera me aparece en todas las paginas.

Un saludo

**Comment by TCattd** [comment]
¡Gracias por el aviso!
Resuelto. El update viene en unos minutos.

**Comment by llermaly** [comment]
Estimado, ahora me figuran estos notice : 

Notice: length se llamó incorrectamente. No se debería acceder a las propiedades del producto directamente. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/savoy/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, call_user_func, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::checkout, WC_Cart->calculate_totals, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, WC_WHQ_Chilexpress_Shipping->calculate_shipping, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Por favor, visita Depuración en WordPress para más información. (Este mensaje se añadió en la versión 3.0.) in /var/www/html/wp-includes/functions.php on line 4139

Notice: width se llamó incorrectamente. No se debería acceder a las propiedades del producto directamente. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/savoy/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, call_user_func, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::checkout, WC_Cart->calculate_totals, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, WC_WHQ_Chilexpress_Shipping->calculate_shipping, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Por favor, visita Depuración en WordPress para más información. (Este mensaje se añadió en la versión 3.0.) in /var/www/html/wp-includes/functions.php on line 4139

Notice: height se llamó incorrectamente. No se debería acceder a las propiedades del producto directamente. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/savoy/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::checkout, WC_Shortcodes::shortcode_wrapper, call_user_func, WC_Shortcode_Checkout::output, WC_Shortcode_Checkout::checkout, WC_Cart->calculate_totals, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, WC_WHQ_Chilexpress_Shipping->calculate_shipping, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Por favor, visita Depuración en WordPress para más información. (Este mensaje se añadió en la versión 3.0.) in /var/www/html/wp-includes/functions.php on line 4139

**Notice: Undefined index: s_city in /var/www/html/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 146**

Entiendo que son ignorables, pero no sería correcto seguir la buena practica?.

Me llama la atención la ultima linea. Me imagino que por esto no me carga la región de la comuna elegida automaticamente(?). Es que no me hace sentido tener que elegir la comuna y luego la region nuevamente a mano.

Un saludo y muchas gracias

**Comment by TCattd** [comment]
Resuelto esos notices (era algo nuevo de WooCommerce 3.0).
