### ISSUE TITLE
wooC 3.4.4 multiselect "Tipos de envíos soportados " no muestra items seleccionados (?)

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [whooohq/whq-woocommerce-chilexpress-shipping#100]
Desde ayer estoy viendo que el multiselect no muestra los valores por defecto ni los items seleccionados.

Acabo de hacer una instalacion limpia de wordpress 4.9.7 , con solo woocommerce 3.4.4, transbank y chilexpress shipping 1.3.13

A primera instancia el multiselect aparecia como simple dropdown, y al grabar me aparecia el campo en blanco, y se pueden re-añadir los tipos de envio de chilexpress, pero al grabar reaparece blanco.
Parece que los valores se graban en la BBDD ,pero como muestro mas abajo parece que no se graban bien tampoco.

podría jurar que hace poco se veía bien y tengo la leve sensación que el culpable es una actualización de woocommerce, ya que indagé el codigo y el multiselect queda conectado con una llamada a javascript.

Ademas me llama la atención, que aunque se seleccione solo dos items, el array en las opciones en la BBDD muestra esto:
s:15:"shipments_types";a:2:{i:0;i:3;i:1;i:4;}s:15:"locations_cache"

He intentado modificar el array manualmente pero eso parece que no ayuda...
Es decir es claramente un problema de woocommerce y no del plugin. queria solo indicarlo y para ver si alguien me puede confirmar el problema...

**Comment by TCattd** [comment]
Se agradece la proeficiencia, estimado.

Ojalá no hayan cambiado la API en WC no más. Ya pasó una vez con ese tipo de setting.

**Comment by PatrickCaneloDigital** [comment]
hmmmm, parece que hay malas noticias...

De WooCommerce me dicen, que el multiselect de atributos de producto funciona bien.
(Admin > Productos ->Atributos)
Generar nuevo atributo y varios terminos
>Despues ir a la pagina de producto > atributos y añadirle el nuevo atributo generado
Los terminos apareceran tipo multiselect

He podido verificar que efectivamente el multiselect de atributos de producto funciona, pero el del plugin no.
Asi que la mala noticia es que debe tener que ver como el plugin ocupa el multiselect...
no se si el selectWoo() del js o la iniciacion de los campos de opciones

**Comment by PatrickCaneloDigital** [comment]
estoy rastreando un poco el tema... 
Si bien en otras partes de woocommerce parece funcionar bien, 
estuve revisando codigo fuente de woocommerce al respecto... me parece que hay un secreto alli de como woocmmerce trata el seteo de valores en multiselect (de hecho me tinca que no tiene forma de setear un default desde el php... el metodo generate_multiselect_html() no considera $data['default'])... lo que probablemente falta en el codigo y en la documentacion es como setear valores predefinidos en el multiselect... a parte del selectWoo() o select2()

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Settings_API.html#700-752

puede estar allí el meollo...

**Comment by PatrickCaneloDigital** [comment]
Para seguir probando tomé el codigo de la definición de la API oficial de woocommerce y lo mezcle con el multiselect...
Para eso añadí al final del whq-woocommerce-shipping.php el código que adjunto aqui abajo. Eso producte una nueva Shipping_Method con su respective entrada como sección en envíos.

En este caso el multiselect se comporta bien... tambien le adjunté el mismo código de init_form_fields del plugin... y aún asi todo se comporta bien...
Por ende hay que ir comparando este código que funciona con el de la clase del plugin... puede que sea algo tan simple como la iniciación de los campos

PD: Esto no omite el caso, que en la selección inicial, efectivamente los default no se muestran bien... solo cuando los campos son sacados de la BBDD se muestran...
`


if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
	function your_shipping_method_init() {
		if ( ! class_exists( 'WC_Your_Shipping_Method' ) ) {
			class WC_Your_Shipping_Method extends WC_Shipping_Method {
				/**
				 * Constructor for your shipping class
				 *
				 * @access public
				 * @return void
				 */
				public function __construct() {
					$this->id                 = 'your_shipping_method'; // Id for your shipping method. Should be uunique.
					$this->method_title       = __( 'Your Shipping Method' );  // Title shown in admin
					$this->method_description = __( 'Description of your shipping method' ); // Description shown in admin
					$this->enabled            = "yes"; // This can be added as an setting but for this example its forced enabled
					$this->title              = "My Shipping Method"; // This can be added as an setting but for this example its forced.
					$this->init();
				}
				/**
				 * Init your settings
				 *
				 * @access public
				 * @return void
				 */
				function init() {
					// Load the settings API
					$this->init_form_fields(); // This is part of the settings API. Override the method to add your own settings
					$this->init_settings(); // This is part of the settings API. Loads settings you previously init.
					// Save settings in admin if you have any defined
					add_action( 'woocommerce_update_options_shipping_' . $this->id, array( $this, 'process_admin_options' ) );
				}
				/**
				 * calculate_shipping function.
				 *
				 * @access public
				 * @param mixed $package
				 * @return void
				 */
				public function calculate_shipping( $package ) {
					$rate = array(
						'id' => $this->id,
						'label' => $this->title,
						'cost' => '10.99',
						'calc_tax' => 'per_item'
					);
					// Register the rate
					$this->add_rate( $rate );
				}

				/**
				 * Initialise Gateway Settings Form Fields
				 */
				 function init_form_fields() {
				     $this->form_fields = array(
				     'title' => array(
				          'title' => __( 'Title', 'woocommerce' ),
				          'type' => 'text',
				          'description' => __( 'This controls the title which the user sees during checkout.', 'woocommerce' ),
				          'default' => __( 'Your Shipping Method', 'woocommerce' )
				          ),
				     'test_shipment_types'=>array(
				                        'title'       => __( 'Tipos de envíos soportados', 'whq-wcchp' ),
				                        'type'        => 'multiselect',
				                        'description' => __( 'Selecciona los tipos de envíos a soportar.<br/>Considera que dependiendo de la ubicación de origen de tus envíos, algunas localidades extremas podrían no contar con un tipo de envío normal (día hábil siguiente), y solo tener disponible envío al tercer día, por lo que lo recomendado es que selecciones al menos "día hábil siguiente", "día hábil subsiguiente" y "tercer día".<br/>Ten presente que los envíos Ultra Rápidos y Overnight están disponibles solo en ciertas ciudades de origen y para algunos destinos.<br/>También <strong>debes tener en cuenta que el envío Ultra Rápido debería ser despachado inmediatamente por tu tienda para cumplir con las espectativas del comprador</strong>.<br/>Conoce más sobre estos <a href="http://www.chilexpress.cl/tiempos-de-entrega-envios-paquetes-documentos" target="_blank" rel="noopener noreferrer">tipos de envíos, acá</a>.', 'whq-wcchp' ),
				                        'options'     => array(1=>'aaa',2=>'bbb',3=>'ccc',4=>'ddd',5=>'eee'),
				                        //'default'     => 4,
				                    ),


'enabled' => array(
                        'title'   => __( 'Activar/Desactivar', 'whq-wcchp' ),
                        'type'    => 'checkbox',
                        'label'   => __( 'Habilitar envíos vía Chilexpress', 'whq-wcchp' ),
                        'default' => 'yes',
                    ),
                    /*'shipping_zones_support' => array(
                        'title'       => __( 'Soporte de Zonas de Envío', 'whq-wcchp' ),
                        'type'        => 'checkbox',
                        'label'       => __( 'Habilitar Zonas de Envío de WooCommerce', 'whq-wcchp' ),
                        'description' => __( 'Al activar esta opción, Chilexpress se transforma en un método de envío compatible con las Zonas de Envío. Al hacerlo, esta página de configuración se moverá las <a href="admin.php?page=wc-settings&tab=shipping&section=">Zonas de Envío</a>.<br/>Debes tener en cuenta que para poder continuar utilizando Chilexpress como método de envío en tu tienda, <strong>tendrás que crear al menos una Zona de Envío, incluir a Chile en ella, y luego agregar Chilexpress como método de envío dentro de Chile</strong>. Hacerlo es mandatorio para poder continuar configurando el método de envío.<br/>Al activar esta opción, serás redireccionado a las Zonas de Envío de WooCommerce.', 'whq-wcchp' ),
                        'default'     => 'disabled',
                    ),*/
                    'title' => array(
                        'title'       => __( 'Título del método de envío', 'whq-wcchp' ),
                        'type'        => 'text',
                        'description' => __( 'El título del método de envío que el usuario verá en la página de checkout', 'whq-wcchp' ),
                        'default'     => __( 'Envío vía Chilexpress', 'whq-wcchp' ),
                    ),
                    'shipping_origin' => array(
                        'title'       => __( 'Origen de los envios', 'whq-wcchp' ),
                        'type'        => 'select',
                        'description' => __( 'Ciudad/Localidad de origen, desde donde se realiza el envío', 'whq-wcchp' ),
                        'options'     => array('AAA'=>'AAA','BBB'=>'BBB','CCC'=>'CCC',),
                    ),
                    'packaging_heuristic' => array(
                        'title'       => __( 'Método para cálculo de costo de envío (embalaje)', 'whq-wcchp' ),
                        'type'        => 'select',
                        'description' => __( 'Heurística utilizada para calcular el precio a base del ensamblaje de varios productos en un mismo pedido (paquete).<br/>
                            <ul>
                                <li>- Unir lados angostos: un solo paquete uniendo los lados más angostos, recomendable cuando son productos pequeños (método por defecto).</li>
                                <li>- Un paquete por item: un paquete por producto, recomendable cuando se envían productos mayores y/o en mayor cantidad.</li>
                            </ul>', 'whq-wcchp' ),
                        'options'     => array(
                            'join_narrow_sides'       => 'Unir lados angostos',
                            'single_package_per_item' => 'Un paquete por item',
                        ),
                        'default'     => 'join_narrow_sides',
                    ),
                    'shipments_types' => array(
                        'title'       => __( 'Tipos de envíos soportados', 'whq-wcchp' ),
                        'type'        => 'multiselect',
                        'description' => __( 'Selecciona los tipos de envíos a soportar.<br/>Considera que dependiendo de la ubicación de origen de tus envíos, algunas localidades extremas podrían no contar con un tipo de envío normal (día hábil siguiente), y solo tener disponible envío al tercer día, por lo que lo recomendado es que selecciones al menos "día hábil siguiente", "día hábil subsiguiente" y "tercer día".<br/>Ten presente que los envíos Ultra Rápidos y Overnight están disponibles solo en ciertas ciudades de origen y para algunos destinos.<br/>También <strong>debes tener en cuenta que el envío Ultra Rápido debería ser despachado inmediatamente por tu tienda para cumplir con las espectativas del comprador</strong>.<br/>Conoce más sobre estos <a href="http://www.chilexpress.cl/tiempos-de-entrega-envios-paquetes-documentos" target="_blank" rel="noopener noreferrer">tipos de envíos, acá</a>.', 'whq-wcchp' ),
                        'options'     => array(1=>'aaa',2=>'bbb',3=>'ccc',4=>'ddd',5=>'eee'),
                        'default'     => array( 3, 4, 5 ),
                    ),
                    'locations_cache' => array(
                        'title'       => __( 'Caché de ubicaciones', 'whq-wcchp' ),
                        'type'        => 'number',
                        'description' => __( '(En días) Chilexpress entrega un listado de ubicaciones (Regiones y Ciudades) dinámico.<br/>Para evitar saturar la API de Chilexpress, aquellos listados son guardados localmente en WordPress (Transients). Ingresa el número de días a mantener en el caché el listado de regiones y cuidades.<br/>Mínimo una semana, máximo dos meses.', 'whq-wcchp' ),
                        'default'     => 30,
                    ),
                    'extra_wrapper' => array(
                        'title'       => __( 'CM extra para caja/embalaje', 'whq-wcchp' ),
                        'type'        => 'number',
                        'description' => __( '(En centímetros) El plugin permite que añadas X centímetros extra al paquete que enviarás a Chilexpress, esto, para permitirte contabilizar el posible uso de una caja (y el espacio extra que necesitarás para evitar que lo que envias se dañe). Si ya usas ese estimado extra al momento de ingresar el tamaño de los productos a tu tienda, y no deseas utilizar este extra, simplemente deja el valor en cero.', 'whq-wcchp' ),
                        'default'     => 0,
                    ),
                    'soap_login' => array(
                        'title'       => __( 'Chilexpress API Username', 'whq-wcchp' ),
                        'type'        => 'text',
                        'description' => __( '(Opcional) Usuario a utilizar en las llamadas a la API de Chilexpress. Dejar en blanco para utilizar datos de conexión por defecto (públicos) que Chilexpress provee.', 'whq-wcchp' ),
                        'default'     => '',
                    ),
                    'soap_password' => array(
                        'title'       => __( 'Chilexpress API Password', 'whq-wcchp' ),
                        'type'        => 'text', // https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/45
                        'description' => __( '(Opcional) Contraseña a utilizar en las llamadas a la API de Chilexpress. Dejar en blanco para utilizar datos de conexión por defecto (públicos) que Chilexpress provee.', 'whq-wcchp' ),
                        'default'     => '',
                        'desc_tip'    => false,
                    ),


				                     );
					} // End init_form_fields()

				function admin_options() {
             ?>
             <h2><?php _e('Chilexpress Shipping','my_shipping_method'); ?></h2>
             <script>jQuery(document).ready(function( $ ) {   if( $('#woocommerce_your_shipping_method_test_shipment_types').length ) {
                console.log('woohoooooooooooo');
        $('#woocommerce_your_shipping_method_test_shipment_types').selectWoo();
        $('#woocommerce_your_shipping_method_shipments_types').selectWoo();
    }});</script>
             <table class="form-table">
             <?php 
             $this->generate_settings_html();    
             ?>
             
             </table>abc <?php
             }
			}
		}
	}
	add_action( 'woocommerce_shipping_init', 'your_shipping_method_init' );
	function add_your_shipping_method( $methods ) {
		$methods['your_shipping_method'] = 'WC_Your_Shipping_Method';
		return $methods;
	}
	add_filter( 'woocommerce_shipping_methods', 'add_your_shipping_method' );

	            
}


`

**Comment by TCattd** [comment]
Tuvimos un problema similar antes:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/86

Fix aplicado:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/commit/54eae3544e6f2f91befb90badc8e406c03a271b7

¿Tendrá que ver con eso, de nuevo?
Ignoro por qué lo cambiaron esa vez, pero nos pegó. Y ahora pega donde mismo. Es extraño.

**Comment by PatrickCaneloDigital** [comment]
puede ser... de hecho justo iba a revisar de eliminar el metodo 
validate_multiselect_field
porque en el php que funciona le doy ints como llaves en el array pero no sobreescribo el metodo validate_multiselect_field

**Comment by PatrickCaneloDigital** [comment]
ya... pues mientras le tengo una solución...
parece que es una mezcla de factores.
Lo que hice para solucionarlo es:
1) eliminar el metodo validate_multiselect_field() de la clase WC_Chilexpress_Shipping
2) eliminar la llamada selectWoo() en el archivo whq_wccp_admin.js
3) añadir un nuevo metodo en WC_Chilexpress_Shipping (en el cual se incluye el script que llama a selectWoo()

`
            function admin_options() {
                 ?>
                 <h2><?php _e('Chilexpress Shipping','woocommerce'); ?></h2>
                 <script>jQuery(document).ready(function( $ ) {
                    if( $('#woocommerce_chilexpress_shipments_types').length ) {
                        console.log('woohoooooooooooo');
                        $('#woocommerce_chilexpress_shipments_types').selectWoo();
                    }
                });</script>
                 <table class="form-table">
                 <?php $this->generate_settings_html(); ?>
                 </table> <?php
             }
`


lo otro es que desde woocommerce me han indicado esto, puede que sea una alternativa forma de incluir el script:
My guess is there's a JS error on the page and since the plugin is not using wc_enqueue_js to output the code it will cause errors.

Try wrapping $('#woocommerce_chilexpress_shipments_types').selectWoo(); inside the wc_enqueue_js function and see if that makes a difference.

**Comment by TCattd** [comment]
No sabía que WC tiene un método wc_enqueue_js. De hecho, uso wp_enqueue_script que es nativo de WP, pero... WC tiene uno propio. No entiendo.

Bueno saberlo, estimado. Bueno saberlo.

El uso de https://docs.woocommerce.com/document/settings-api/#section-2 no está mal.
De todas maneras no es el problema.

El problema es el método validate_multiselect_field(). Solo sacándolo, los valores gaurdados en la DB vuelven a ser los correctos.
Quiere decir que lo que yo parché cuando tuvimos el issue acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/86 fue una regresión... y debí haberla reportado :D

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/commit/e197db4b7b0d3c4c9b1b12e47766e561f8c52a4b

**Comment by TCattd** [comment]
Muy agradecido por la ayuda con el debug, estimado. Muy agradecido.

http://prntscr.com/kdgt0o

V1.3.14 disponible en wp.org ya.

**Comment by PatrickCaneloDigital** [comment]
De nada estimado...
Si es que ese problema aparecio recien desde la actualización del woocommerce 3.4.2 a 3.4.3 por lo visto.

La inclusión del wc_enqueue_js simplemente ayuda a inyectar js solo en caso que el contexto sea woocommerce, en eso veo la ventaja. uno se ahorra la prueba dentro del js si el contexto es woocommerce.

Sobreescribir el metodo: admin_options() solo lo hice, para re-asegurarme en las pruebas que la llamada a selectWoo() sea incluida al 100% dentro de ese contexto.
No es necesaria pero ayuda un poco a mantener la funcionalidad junta en un archivo (y no tenerla en el archivo whq_wccp_admin.js. 
Con eso hasta la prueba de 
`if( $('#woocommerce_chilexpress_shipments_types').length ) {`
se haría innecesaria ya que estariamos seguros que el script solo aparece cuando se muestran esos ajustes. Pero eso ya va mas en tema arquitectura y no funcionalidad.

PD: el otro PR ahora si puedo enviarlo de camino. Queria asegurarme que este problema no fuera un efecto colateral.

**Comment by PatrickCaneloDigital** [comment]
PD: Acabo de ver el edit en whq_wccp_admin.js para la version 1.3.14
y en realidad se hubiera podido eliminar odo este bloque, ya que con el cambio no contiene ninguna funcionalidad...

`
	//Shippment type select height
	if( $('#woocommerce_chilexpress_shipments_types').length ) {
		//$('#woocommerce_chilexpress_shipments_types').selectWoo(); //See admin_options() method
	}
`

**Comment by TCattd** [comment]
La verdad es que aún con el selectWoo() como estaba antes, seguía funcionando bien todo.
El admin_options() no era necesario aún; pero es interesante. No conocía ese método :) Quizás sirva para algo más a futuro.

Por ahora lo dejé así, a ver que ocurre; si no hay más reportes de errores. Si todo sigue bien, probablemente devuelva el selectWoo() a donde estaba antes nada más.

Gracias nuevamente ;)

**Comment by PatrickCaneloDigital** [comment]
de nada! ;)
Yo he probado con el selectWoo() donde estaba (con WooCommerce 3.4.4) y eliminando las lineas de script en admin_options() y dejó de funcionar, pero quizas tengo yo algo enredado ya a esta altura jajaja

El metodo admin_options() es bien interesante, ya que permitiría personalizar el diseño de las opciones y ponerle literalmente más color y un layout individualizado (sobreescribiendo otros metodos como generate_settings_html(), generate_multiselect_html(), etc.)
Es con eso que plugins como W3CTotalCache logran generar una apariencia mas personalizada o estructurada...

Saludos ;-)
