### ISSUE TITLE
Incompatibilidad entre plugins

### ISSUE THREAD

**Issue by PabloSilvaBravo** [whooohq/whq-woocommerce-chilexpress-shipping#103]
Estimado, primero que todo felicitarte por tan buen trabajo y soporte al plugin.
He presentado incompatibilidad con algunos plugins que se encuentran en  el market.
El plugin llamado WooCommerce Checkout Field Editor Pro Me permite configurar los campos de checkout de mi pagina web, por lo que vi es solo compatibilidad parcial, por lo que asumo que no sería problema, aunque igualmente es molesto ver el letrero en rojo sobre los plugin diciendo que existe un listado con plugins incompatible, y no está este en ese listado. 
Por otro lado esta la incompatibilidad (creo que total) con cualquier tipo de controlador de inventario o stock, ya que a pesar de que woocommerce tiene su propio control de stock, este no permite decir cuantas piezas tengo en el market, sino que solo me permite poner que tengo disponible, en reserva o agotado. 
Me gustaría que me pudieses ayudar con esa supuesta incompatibilidad, o si hay algun plugin que conozcas que no interfiera con el tuyo. 

De antemano muchas gracias.

**Comment by TCattd** [comment]
La incompatibilidad parcial es de cuidado, pero no para dejar de usar un plugin. Todo depende de qué hagas con el.
La explicación respecto a la incompatibilidad de aquel plugin es clara al respecto (creo):
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-326564625

El letrero rojo advirtiendo de algún plugin incompatible encontrado, solo aparece cuando el plugin nuestro se instala por primera vez o cuando se actualiza a una nueva versión.
Se puede remover (con la X arriba a la derecha), y no aparecerá más hasta que exista otra actualización del plugin nuestro, nada más.

Respecto a lo otro:
¿Con qué plugin de stock tienes problema, estimado?
No he usado ninguno, por eso pregunto.

**Comment by PabloSilvaBravo** [comment]
Cierro ese mensaje rojo, y claro se abre cada vez que tu plugin se actauliza, pero cuando instalo cualquier aplicacion para control de stock el mensaje salta denuevo, lo que me hace pensar que tiene concretamente una incompatibilidad en algun campo.
Por ejemplo en las siguientes y más comunes:

ATUM Inventory Management for WooCommerce

WooCommerce Stock Manager

PW WooCommerce Bulk Edit

Espero que puedas resolver la compatibilidad con alguno de estos, ya que me gustaría mucho poder controlar stock más detalladamente desde Wordpress. Gracias por responderme. Eres un crack!

**Comment by TCattd** [comment]
Duda:

¿Mientras has instalado aquellos plugins, aún mantienes instalado el plugin "WooCommerce Checkout Field Editor" en esa misma instalación de WP?

**Comment by PabloSilvaBravo** [comment]
así es, ese plugin lo uso para modificar los campos al hacer check out. si saco ese plugin se soluciona?

**Comment by TCattd** [comment]
Estimado,
No hay problema entonces. Ninguno.

El tema es sencillo: tienes instalado un plugin conocido por generar problemas si se utiliza mal (incompatibilidad parcial).

Cada vez que se actualiza el plugin de Chilexpress, ese cuadro de advertencia se reinicia. Al hacerlo, detecta que tienes un plugin incompatible (el ya mencionado), y vuelve a aparecer una alerta.

Lo mismo pasa si instalas otro plugin. Para poder verificar si es o no incompatible, se revisan todos los plugins. Por eso vuelve a aparecer la alerta, porque aún existe WooCommerce Checkout Field Editor instalado, y no porque el plugin nuevo, el que sea que hayas instalado, sea incompatible.

Esos plugin que mencionas, de stock, no tienen nada que ver con esa alerta. No son incompatibles.

Puedes ignorar el menaje, estimado. 

Veré como limitarlo solo a la pantalla de plugins y la config del plugin de Chilexpress. 

Saludos, 
Esteban

**Comment by TCattd** [comment]
Resuelto en 1.4.6
