### ISSUE TITLE
Problema checkout pago pendiente 

### ISSUE THREAD

**Issue by truchosky** [whooohq/whq-woocommerce-chilexpress-shipping#104]
Estimados,

No se desde que versión existe el problema, recién hoy me di cuenta de esto, reproducirlo es fácil, compren cualquier producto, con o sin envio, elijan un medio de pago para que quede en estado pendiente de pago (como khipu por ejemplo), obviamente no completen el pago,  vuelvan a la lista de pedidos e intenten pagarlo, se queda en el checkout hasta que se desactiva el plugin, con o sin envio (producto virtual) pasa esto

ninja edit: En el demo pasa lo mismo

**Comment by TCattd** [comment]
Agradecido por el aviso, estimado ;)

Resuelto en v1.4.4
