### ISSUE TITLE
Posibilidad de agregar apis de otros proveedores

### ISSUE THREAD

**Issue by chias10** [whooohq/whq-woocommerce-chilexpress-shipping#105]
Buen dia, no se si este comentario vaya en esta seccion, ando un poquito perdido, quisiera saber si existe la manera de reemplazar las apis de chilexpress para que funcion de igual manera con las apis de otro proveedor de servicio.

**Comment by TCattd** [comment]
Dudo que sea algo muy fácil de cumplir, estimado, considerando la variabilidad ilimitada que la API de otro servicio pudiese tener.

Lo siento.

Si se trata de otro proveedor de servicio de envío, entonces es trabajo para otro plugin.

Esteban
