### ISSUE TITLE
incompatibilidad Chilexpress para WooCommerce.

### ISSUE THREAD

**Issue by kachibu** [whooohq/whq-woocommerce-chilexpress-shipping#106]
quisiera qué grado de incompatibilidad existe y si hay algun plugin diferente que pueda usar para chilexpress que sea compatible.

**Comment by TCattd** [comment]
¿?

Estimado,
Si recibiste un mensaje al respecto, te aconsejo que leas el mensaje con calma, e ingreses al enlace que va acompañando al mensaje. Ahí se menciona que plugins sabemos que tienen cierta incompatibilidad, y a que nivel.
Luego coteja esa lista con la lista de plugins que tú tienes instalados, y actúa acorde y según lo desees.

La incompatibilidad no es del plugin de Chilexpress con WooCommerce. Eso te lo aseguro.

Esteban

**Comment by TCattd** [comment]
Después de detectar el plugin que *podría* causar conflictos, y si luego de leer el link que viene en el mensaje que viste aún tienes dudas, puedes re-abrir este issue para comentarnos, por favor.
