### ISSUE TITLE
Call to undefined function is_plugin_active()

### ISSUE THREAD

**Issue by EcoTiendaChile** [whooohq/whq-woocommerce-chilexpress-shipping#107]
Fatal error: Call to undefined function is_plugin_active() in /home/ecotiend/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 118

**Comment by TCattd** [comment]
Estimado,

¿Versión de PHP instalada en el servidor?
¿Versión de WordPress instalada?
¿Versión de WooCommerce instalada?

¡Gracias!

**Comment by TCattd** [comment]
Ah, no hace falta. Se lo que es.

Gracias por el aviso, @EcoTiendaChile ;)

Arreglado en 1.4.7
Update en vivo en unos pocos minutos.

**Comment by TCattd** [comment]
Estimado,

El arreglo está hecho en la versión 1.4.7
Solo debes actualizar el plugin desde WordPress mismo.

Saludos,
Esteban

**Comment by EcoTiendaChile** [comment]
ok pero lamentablemente no lo puedo actualizar ya que al cargar el plugin en wordpress y al momento de activar el plugin me arroja el error...

**Comment by EcoTiendaChile** [comment]
ya lo logre te agradezco tu ayuda y comprencion...

**Comment by TCattd** [comment]
;)
