### ISSUE TITLE
Campo para agregar una tarifa fija

### ISSUE THREAD

**Issue by avagp** [whooohq/whq-woocommerce-chilexpress-shipping#108]
Hola! Primero que nada quería darles nuevamente gracias por el plugin, está genial y ayuda mucho, pero me he topado con un problemita, no puedo costear bien el embalaje.

Este campo que viene en el plugin (que es para sumar cm adicionales al item) no ayuda al caso donde hay costos sobre el maquilado y el material de embalaje. Punto donde muchos emprendedores no caemos, y absorvemos el costo en vez de traspasarlo al cliente. 
![image](https://user-images.githubusercontent.com/11801254/45429785-5a2d8c80-b67a-11e8-901f-02016192bfaa.png)

En mi caso particular, y a modo de ejemplo, tengo un producto que mide 20x15x10 y pesa 1 kg, y con la caja sale 20x20x10 y pesa 1,1kg, pero eso no logra cambiar el precio para costear los 790 pesos adicionales que me cuesta la caja y el servicio de maquila por unidad adicional.

Por lo que sería una gran solución poder agregar una fórmula de costos para el envío, similar al que ya tiene woocommerce, que se sume al valor del envío obtenido por Chilexpress:
![image](https://user-images.githubusercontent.com/11801254/45430061-e6d84a80-b67a-11e8-92c6-5c373f76fc38.png)

Por ejemplo, para mi caso particular yo usaría la siguiente fórmula que sume al costo de envío:
790+([qty]-1)*280

Por que me sale 790 la primera unidad y 280 pesos adicionales cada unidad adicional.

Eso debería poder sumarlo al costo de envío de chilexpress, quedando:

Costo_Chilexpress + 790 + ([qty] - 1) * 280

Y eso debería cobrarle al cliente.

Con eso, los ecommerce que enviamos productos podemos realmente obtener el margen de nuestros productos, y no diluirlo con los costos variables e impredecibles del envío.

Ojalá les sirva mi sugerencia.

Saludos!!

**Comment by TCattd** [comment]
No es para nada mala idea, estimado. Para nada.

**Comment by PatrickCaneloDigital** [comment]
Le he dado unas vueltas a esta idea, y bien entiendo el argumento economico, pero una solución genérica se pone un poco compleja y no estoy seguro, si el ejemplo dado es el mas practicable para todos los usuarios del plugin.
Si uno vende productos mixtos (por ejemplo zapatillas deportivas y pendrives, los pendrives caben perfectamente en la caja de zapatos cuado se venden los dos productos al mismo tiempo, pero si se vende solo hace falta embalarlo)
Es decir si uno contempla una gran variedad de casos, es casi imposible tener la formula perfecta.
Eso es lo dificil de soluciones técnicas que tienen que ser genéricas y practicas de administrar... 

En teorías economicas hay varias formas como abarcar el caso, pero todas tienen una base en comun: 
Si se ven los costos de envio como costos operativos (es decir costos fijos, y no variables), se puede solucionar el tema costos embalaje con subvención cruzada.
Subvencion cruzada es que todos pagan algo (aunque no todos lo ocupen), bajo el lema entre varios la carga es mas liviana y se disipan variaciones al tratar un costo variable como costo fijo.

Se me ocurren 3 alternativas (aunque pueden haber mas): 
- Una es subir los costos a todos los productos unos pocos pesos, para que cubran juntos todos los costos de embalaje
- La otra alternativa es ponerle un costo de embalaje fijo a cada envio, independiente de su volumen. (deducido por el costo promedio mensual de embalaje y cantidad de pedidos a enviar por mes)
- O finalmente ocupar un costo fijo por unidad de volumen: por ejemplo cada 10cm cubicos del pedido son 300 pesos en embalaje.
Eso produce que algunos clientes quizas pagarán de mas, otros quizas pagaran menos, pero en todos se cubran los costos de embalaje o por ultimo se logre traspasar una cobertura de un x% de los costos de embalaje a los clientes.

Segun mi humilde opinion, los 3 ejemplos serían una forma genérica mucho mas practica que la mencionada, ya que no habria que definir costo de embalaje por cada producto individual, y que permite a cada dueño optimizar sus cotos de embalaje y traspasarlo al cliente de una forma u otra. Ademas estas variantes se podrían implementar mucho mas fácil tanto a nivel técnico para el plugin como a nivel usuario en su implementación.

No se que piensan...

**Comment by avagp** [comment]
No sé cuál es la mejor solución pensando en los usuarios del plugin, pero te puedo contar desde mi contexto.

Todas las empresas que ofrecen el servicio de fulfilment (almacenaje, maquilado y envío), lease, chilexpress, bluexpress, shipit, DHL (que son las que he usado o consultado) tienen el mismo sistema:

A) Costo por pedido
B) Costo por unidad en el pedido
C) Costo de envío

No te están cobrando la caja en ninguno de esos elementos. La caja está incluída, y solo aumenta el costo por pedido cuando has acordado que debe ir a una caja distinta de mayor valor, pero esa opción se aplica para todos tus envíos, no se puede aplicar para algunos productos de tus catálogos. Es todo o nada.

A) En el costo por pedido es el costo base del maquilado, es un costo fijo. Estás pagando por un paquete básico, un trabajador que te pone los productos en la caja y que le pega las etiquetas respectivas para su posterior envío. Independiente del tamaño de los envíos (a menos que pase los 20 kg o algo así)

B) El costo por unidad en el pedido te están cobrando el proceso de ir a buscar en la bodega y sacar del inventario tus productos y dejarlos en el sector de maquilado (empaquetado). Es un costo variable.

C) El costo de envío te cobran el traslado al destino del cliente. Es un costo variable.

A menos que tú lo hagas desde tu local y quieras escatimar costos, sí, puede que la solución se torne más compleja, ya que puedes manejar con mayor detalle qué cabe en cada caja, pero nadie lo hace, por que es muy complejo y tedioso.

La mayoría amortiza el valor de la caja y el envío en el producto, pero es una mala práctica.

Lo que se debe hacer es tratar de traspasar el mayor porcentaje del valor del proceso de envío al cliente. Es un ideal.

Hoy por hoy, a través del plugin le puedo solamente traspasar el costo de envío al cliente, lo cual ya es una gran victoria y agradezco mucho a ustedes que me dan la posibilidad de hacerlo.

Pero para mi sería un ideal poder agregar los otros 2 costos: el (B) y el (C), uno fijo y el otro variable.

Pensé que la solución que te entrega woocommerce sería un buen ejemplo para dar flexibilidad al cobro del envío. Tienes las variables [qty], [fee_percentaje], [cost], [fee_min] y [fee_max] más las operaciones aritméticas. 

Para mi eso cumpliría con las 2 primeras soluciones que presentas.

Ahora, si le agregan las dimensiones [height], [width], [depth] y [weight], se podrían hacer las 3 soluciones.


Yo igual estoy súper contento con el plugin así como está, así que para mi esto sería la guinda de la torta.

Saludos!

**Comment by PatrickCaneloDigital** [comment]
Si, entendi a la primera tu acercamiento a la problematica.
Como bien dices, es un tema complejo que es imposible de calcular de forma precisa.
Igual el acercamiento que mencionas tiene sus fallas: El costo por unidad en el pedido asimismo es un acercamiento ya que no es lo mismo ir a buscar 20 pendrives del mismo modelo o 20 artefactos electronicos grandes, por ende el costo promedio de maquilaje es en si un acercamiento.
Solo quiero constatar que cualquier formula que se aplique será un acercamiento. 

Habiendo dormido una noche por encima del tema, se me levantó una duda:
El plugin mismo calcula el costo de envío de Chilexpress y en estricto rigor no los costos de fulfilment y embalaje. Ademas destaca el costo de envío como "Chilexpress: Dia hábil siguiente" por ejemplo.

Si se incluyen estos costos con el solo titulo de "Dia hábil siguiente" (asi es como le aparecería al cliente final) puede generar confusiones si alguien maneja los precios reales de Chilexpress, ya que el precio que aparecería sería mas alto, lo que puede llevar al hecho de pensar que la tienda esta estafando.
Ahora si destacamos el maquilaje o fulfilment como punto aparte en la factura, el cliente se sentirá castigado doble al pedir por internet lo que puede desincentivar el pedir a traves de internet en esta tienda.

Si me preguntas, yo creo que la practica de integrar los costos de fulfilment en el precio del producto es una forma elegante para esconder esos costos ante el cliente.
El costo de producto es el menos transparente para el cliente por ende te evitas discusiones acerca la justificación y tus procesos y costos internos, y tampoco se le suma el costo a un item (entrega chilexpress) que en estricto rigor no tiene que ver con eso.

@TCattd Igual sería interesante ver que opinas.
La implementación técnica no la veo compleja, pero hay que pensar bien en una solución universalente practicable que no genere nuevos problemas o malentendidos.

**Comment by garretonfco** [comment]
Hola, justo estaba pensando en crearles un ticket relacionado a lo mismo cuando me pille con este.
En mi caso particular solo necesito añadir un precio fijo, ya que la variedad es menor.

Ojala pueden implementarlo partiendo quizas por algo simple.

Nuevamente les agradezco por el plugin, funciona muy bien.
Saludos

**Comment by mihai-lazar** [comment]
Por si a alguien le sirve, pueden agregar un costo fijo modificando un poco de código, tiene que ir al archivo ubicado en:

wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php

buscar la linea (770 y 787 en mi caso):

$rates[ $service_id ] = array( $service_id, $service_label, $service_value);

y editarla:

$rates[ $service_id ] = array( $service_id, $service_label, $service_value + 790 );

en donde los 790 equivalen al valor extra que uno desea cobrar.

**Comment by TCattd** [comment]
Disponible como opción en 1.4.23
