### ISSUE TITLE
Ayuda, no puedo instalar plugin en mi wordpress 

### ISSUE THREAD

**Issue by roonwhisky** [whooohq/whq-woocommerce-chilexpress-shipping#109]
hola buenas tardes a todos lo que sucede es que no puedo instalar el plugin de chile express en mi wordpress, mi WC dice que presenta error en linea 66. adjunto imagen del error.
si alguien tiene alguna idea de como solucionarlo seria de mucha utilidad.
se agradece.

el error que presenta.
https://www.dropbox.com/s/qcy9013s7d42h90/CE-error.png?dl=0

linea 66.
https://www.dropbox.com/s/4pvcgf8cmwklj9m/CE-linea.png?dl=0

**Comment by TCattd** [comment]
Estimado:

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?utf8=%E2%9C%93&q=is%3Aissue+Can%E2%80%99t+use+function+return+value+in+write

Actualizar versión de PHP.
