### ISSUE TITLE
Solución para fallo en calculadora de envios captura $_POST['s_city']

### ISSUE THREAD

**Issue by Missinglagola** [whooohq/whq-woocommerce-chilexpress-shipping#110]
Estimados.
Felicidades por el plugin, una contribución muy util.
Lo he instalado con el tema Mindig, y la calculadora, sólo funcionaba al poner la ciudad en mayúsculas y sin acentos, así que analice el plugin, hasta descubrir la función de captura de datos de la calculadora de envios en el carro de compras.
Una simple modificacion para eliminar los acentos que se incluyan en ese dato y luego convertirlo a mayúsculas, para poder hacer la comparación con la lista de ciudades, y no ha vuelto a fallar, ahora funciona a la perfección independientemente de como el cliente introduzca los datos en el campo de ciudad.
La función modificada ha sido en la línea 653 (private function get_tarification) del archivo classes/WC_WHQ_Chilexpress_Sipping.php, agregando una función de limpieza de acentos y un strtoupper al resultado, de forma que el valor, queda limpio de acentos y convertido a mayúsculas.
Espero que este aporte ayude a hacer que este plugin sea útil para un mayor número de usuarios, el plugin refleja un muy buen trabajo, gracias por vuesra contribución a la comunidad.
Saludos

**Comment by TCattd** [comment]
Estimado,

Tanto la calculadora como el checkout, al seleccionar Chilexpress, utilizan campos prellenados con los valores de ciudades y regiones que Chilexpress espera.

Ver:
http://prntscr.com/kzhz4u

http://prntscr.com/kzhzex

Lo puedes probar en el sitio de demo directamente: http://wpchilexpress.whooohq.com/cart/

Si no ves esos campos con los valores que Chilexpress envía desde la API, entonces hay algún problema de incompatibilidad con el Theme que tienes instalado y/o con algún plugin que tienes instalado y activado también.

Debes revisar.

Revisa las preguntas frecuentes https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout y sigue esos pasos, por favor.

**Comment by Missinglagola** [comment]
Hola Esteban.

Efectivamente, había un problema de incompatibilidad, probablemente, porque el tema que uso, nombra los campos con clases y etiquetas diferentes, por lo que el JS no realiza los cambios necesarios, pero igualmente, con la modificación que hice, el plugin funciona correctamente, no autorellena el campo de Ciudad, pero si tiene en cuenta el valor enviado por $_POST, y muestra los precios y servicios disponibles correctamente.

El campo de Región si logra autorellenarlo con los valores porporcionados por el plugin, pero no el de Ciudad.

He verificado con el tarificador de Chilexpress, y los valores y servicios que muestra, están correctos.

Tal vez este enfoque, aumente la compatibilidad del plugin, independientemente de las clases que usen los temas no compatibles en el Checkout,

En fin la idea era compartir este aporte en gratitud por el plugin, por si era útil. 

De todas formas, reitero, muchas gracias por tu tiempo y dedicación, magnifico aporte tu plugin.

Saludos.

**Comment by TCattd** [comment]
El problema y lo crítico de lo que haces, es que no podrás asegurarte que la ciudad y/o región estén escritas en la forma en que la API de Chilexpress espera que esos cambios vengan. Estás agregando una randomización que Chilexpress no espera en esas variables.

¿Cómo le dices a la región metropolitana?.

Region Metropolitana
Región Metropolitana
R. Metropolitana
regionmetropolitana
RM
Santiago
Gran Santiago
etc.

Sin considerar las faltas de ortografía.

Por eso el plugin funciona como lo hace, estimado, para limitar las variables a las que la documentación y API de Chilexpress espera que sean enviadas a esos endpoints.

Te sugiero revisar en detalle que es lo que genera problemas con tu theme, y resolver esos problemas de incompatibilidad (con lo que WooCommerce por default espera que exista) ya sea directamente con el desarrollador del theme o tu mismo usando un child theme para aplicar tus cambios.
No parchar el plugin de Chilexpress.

Saludos y buen día ;)
Esteban

**Comment by Missinglagola** [comment]
Hola Esteban.

Como te comente en mi anterior respuesta, en mi caso, el campo de Regiones si se carga correctamente.
El de Ciudades no, por lo que se reducen las posibilidades de error.

Despues de emparejar los datos a comparar mínimamente (remover acentos y asegurarse de que el texto proporcionado este en mayúsculas), se reducen las posibilidades de error, aunque esta claro que sería muy complicado establecer una comparación que contemple todo tipo de fallos al proporcionar los datos, en el peor de los casos, si los datos no corresponden con los de Chilexpress, continua mostrando que el servicio no esta disponible.

Es por esto que compartí esta solución, para ver si te interesaba aplicarlo en la próxima actualización, y no tener que estar parcheando el plugin, no es mucho el código el que se necesita, y reduce al menos este tipo de error comparativo.

Pero ya veo la mala recepción que ha tenido esta sugerencia, en fin, no insistiré más.

Saludos
