### ISSUE TITLE
Como configuro el plugin para envio por pagar?

### ISSUE THREAD

**Issue by roonwhisky** [whooohq/whq-woocommerce-chilexpress-shipping#111]
hola buenas, antes que nada gracias por la contestación sobre el fallo y tenían toda la razón que de se debía a actualizar el PHP, ahora que lo instalé busco la opción para colocar envío por pagar, cosa de que quien reciba el pedido cancele, como debo realizar esa configuración o donde aparece en las opciones, dado que me salen las opciones de "tercer día hábil",  "overnight", "día hábil siguiente". agradecería de antemano su ayuda

**Comment by TCattd** [comment]
Estimado,

Todo el punto del plugin es poder cobrar por adelantado el envío vía Chilexpress.
El plugin actualmente no hace lo que necesitas.

Pero, si el envío lo va a pagar el usuario, puedes simplemente especificar aquello en tu tienda, y no necesitas este plugin y ninguno más la verdad.

Puedes utilizar el "free shipping", por ejemplo, y renombrarlo a "Por pagar" así http://prntscr.com/kzyqtg y eso será mostrado como opción en el checkout: http://prntscr.com/kzyr6q

Tengo entendido, eso si, que Chilexpress solo permite envíos por pagar solo a sucursal.
El plugin, por el momento, no hace eso. No es capaz de limitar envíos solo a sucursales de Chilexpress.

Hay un issue abierto al respecto para ver este tema eso si, por acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/79
Si hay novedades, las comentaremos ahí.
O si alguien quiere ayudar con el desarrollo y enviar un PR, bienvenido sea. Las novedades igual las comentaríamos ahí.
