### ISSUE TITLE
Problema en el tamaño del width de regiones

### ISSUE THREAD

**Issue by javierhfa** [whooohq/whq-woocommerce-chilexpress-shipping#112]
Estimado, 

Tengo un error y estoy tratando de arreglar 
![image](https://user-images.githubusercontent.com/41651218/46693775-2c882480-cbe1-11e8-8e21-eee4f97c849f.png)

**Comment by TCattd** [comment]
Estimado

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/README.md#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Luego de seguir lo dicho ahí, nos comentas, por favor. 

Esteban

**Comment by TCattd** [comment]
Estimado,

¿Nos puedes comentar como te fue?

Gracias.

Esteban

**Comment by TCattd** [comment]
Reabres el issue si encuentras que el problema igual ocurre con lo solicitado en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/README.md#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout por favor.
