### ISSUE TITLE
Limitar envíos sólo en Región Metropolitana

### ISSUE THREAD

**Issue by ricardogonzalezcari** [whooohq/whq-woocommerce-chilexpress-shipping#113]
Hola Estimados!
Primero muchas gracias por el desarrollo de este plugin, la verdad es que me esta sacando de apuros enormemente, sin embargo tengo la necesidad de limitar el envío sólo en la Región Metropolitana.

Me podrías dar una idea de cómo realizarlo?

Muchas Gracias!
Un abrazo

**Comment by TCattd** [comment]
No se puede actualmente.

Creo que eso se podría si se trabaja en habilitar esto https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39 si no me equivoco.

No hay ETA para esa característica eso si, estimado.
Lo siento.

Esteban
