### ISSUE TITLE
Caída del Webservices de Chilexpress

### ISSUE THREAD

**Issue by AndresReyesTech** [whooohq/whq-woocommerce-chilexpress-shipping#114]
En este momento (y por las últimas 2 horas) ha estado caído el plugin de Chilexpress. la falla, según el wp-debug, es que http://qaws.ssichilexpress.cl/GeoReferencia?wsdl está arrojando un error 500.

Sólo lo aviso para que los usamos el plugin no demos vueltas en círculo.

Ojo: En el checkout está mostrando las ciudades pero se cae en el cálculo. Esto ocurre porque las ciudades las saca del transient y no directamente de Chilexpress.

Esperemos vuelva pronto.

**Comment by TCattd** [comment]
Gracias por el aviso, estimado ;)

**Comment by AndresReyesTech** [comment]
Estimados,

Durante toda la tarde ha estado caído, sin embargo, modifiqué los wsdl y les cambié los qaws por ws directamente y funcionan sin problemas. Usé las credenciales de prueba de la documentación pública que son:

Username: UsrTestServicio
Password: U$$vr2$tS2T

¿Será necesario modificarlos en el plugin para aplicar este cambio?

**Comment by PatrickCaneloDigital** [comment]
Buen punto @AndresReyesTech 
Lo ideal sería que en los ajustes del plugin permitan definir ambiente y que cambie el url de la api segun el ajuste, ya que aparentemente los qaws son de ambiente de desarrollo (quality assurance webservices) y los ws de ambiente productivo, eso podría producir a largo plazo mas estabilidad...

**Comment by TCattd** [comment]
Podemos poner una opción dentro del plugin, sin duda.

Solo cambiaste la URL a donde apuntan @AndresReyesTech ? Nada más?

**Comment by AndresReyesTech** [comment]
Si, cambié  la URL dentro de los wsdl. No hice otro cambio.

**Comment by TCattd** [comment]
Va update con esto https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/commit/4f9ac543c06c2e190108d77e6410db30c17fc285

Me pueden avisar si todo les funciona ok, por favor, @AndresReyesTech @PatrickCaneloDigital 
¡Gracias!

**Comment by TCattd** [comment]
No lo dejé por default con el ambiente de producción, porque como he dicho en otros issues, no tengo claro si ese set de user/pass que viene en la documentación (que no es 100% pública, hay que ser cliente de ellos para acceder si no me equivoco)... no tengo claro si lo quieren hacer público o no.
Entiendo que ese mismo set de user/pass está por todos lados. Es cosa de Googlear.

Pero no me quiero meter en problemas o enojar a la gente de Chilexpress solo por eso.
Por lo mismo el plugin tiene una opción para usar un user y password definidos por el usuario, y no viene con ellos preconfigurados.

Así c/u decide que hacer respecto a esto.

**Comment by AndresReyesTech** [comment]
Gracias!

**Comment by TCattd** [comment]
A ti, estimado. Buen fin de semana ;)

**Comment by jaimesoliscl** [comment]
Estimados, tuve el inconveniente varios días de la semana pasada incluso ayer, realice la actualización hace 1 hora aprox y sale de una, el aviso:

> Chilexpress no se encuentra disponible en este momento. Por favor, selecciona otro método de envío (si existiese), o iténtalo nuevamente en unos minutos.

Me podrían ayudar/colaborar con alguna indicación, leía sobre direcciones a modificar.

**Comment by PatrickCaneloDigital** [comment]
Acabo de avisar Chilexpress en respecto al tema y estan conscientes que todos los WS que empiezan con qaws no estan funcionando.
me enviaron un enlace alternativo de prueba que funcionó... eso fue recien hace poco, quizastuvieron una actualización del firewall o algo similar y no se dieron cuenta (hasta ahora).
Les mantengo al tanto de los descubrimientos

@jaimesoliscl :
que configuración tienes en los ajustes? Si es la de la gráfica es imposible que te funcione en el momento. Tendría que cambiar a WS PROD
![grafik](https://user-images.githubusercontent.com/21183922/48377084-8f228380-e6ab-11e8-8354-0bc909e191dc.png)

**Comment by jaimesoliscl** [comment]
> Acabo de avisar Chilexpress en respecto al tema y (despues de avisarles) estan conscientes que todos los WS que empiezan con qaws no estan funcionando.
> me enviaron un enlace alternativo de prueba que funcionó... eso fue recien hace poco, quizas tuvieron una actualización del firewall o algo similar y no se dieron cuenta (hasta ahora).
> Les mantengo al tanto de los descubrimientos
> 
> @jaimesoliscl :
> que configuración tienes en los ajustes? Si es la de la gráfica es imposible que te funcione en el momento. Tendrías que cambiar a WS PROD
> ![grafik](https://user-images.githubusercontent.com/21183922/48377084-8f228380-e6ab-11e8-8354-0bc909e191dc.png)

Muchas Gracias Patrick! Por lo pronto opera sin problemas.

**Comment by PatrickCaneloDigital** [comment]
Estimados, creo que tengo novedades al respecto.
No recibi mas respuesta de Chilexpress pero me da mucho la impresion que las direcciones de desarrollo cambiaron y no fueron actualizadas en la documentación.

Acabo de probar el enlace de prueba que me envió Chilexpress y parece que cambiaron los dominios:

> indicar al cliente que pruebe con la siguiente URL: http://testservices.wschilexpress.com/GeoReferencia?wsdl
> Cualquier cosa que nos avise.
> esa fue la repuesta de TI

http://testservices.wschilexpress.com/GeoReferencia?wsdl
http://testservices.wschilexpress.com/TarificarCourier?wsdl

Estos enlaces funcionan, por consecuencia sugiero cambiar en los archivos correspondientes el
qaws.ssichilexpress.cl
por testservices.wschilexpress.com

Si bien no tengo confirmación concreta de Chileexpress al respecto,
con eso deberían funcionar de nuevo los enlaces QA

**Comment by TCattd** [comment]
Una lástima la demora o nula respuesta de Chilexpress la verdad.

Gracias por el PR @PatrickCaneloDigital 
Va update ;)

**Comment by Rodolfinho21** [comment]
Yo actualice la última versión, y aun me sigue apareciendo “no disponible”, no soy muy computin, si me pueden guiar paso a paso como se hace l cambio de georeferenciacion, que posteo Patrick canelo
A quien cito:” indicar al cliente que pruebe con la siguiente URL: http://testservices.wschilexpress.com/GeoReferencia?wsdl
Cualquier cosa que nos avise.
esa fue la repuesta de TI
http://testservices.wschilexpress.com/GeoReferencia?wsdl
http://testservices.wschilexpress.com/TarificarCourier?wsdl “
Se agradecería muchísimo


Saludos,

**Comment by PatrickCaneloDigital** [comment]
entra en los ajustes del plugin y aprieta "guardar" eso debería solucionar los problemas.

@TCattd : Igual se podría implementar copias de los archivos WSDL_GeoReferencia_QA.wsdl y WSDL_Tarificacion_QA.wsdl con nombres WSDL_GeoReferencia_.wsdl y WSDL_Tarificacion_.wsdl como solución temporal, con eso los usuarios que no guardan los ajustes tendrían esa misma versión disponible y no topan con problemas (no es elegante, lo admito)

**Comment by Rodolfinho21** [comment]
Gracias por responder, actualice a la ultima versión y luego ingrese a ajustes y guardar, cabe mencionar que tengo el ambiente api WSqa

Que puedo hacer aún me figura no disponible.
gracias @PatrickCaneloDigital por la pronta respuesta y ayuda.

**Comment by TCattd** [comment]
@PatrickCaneloDigital , relax, lo resolví de otra forma. Va en 1.4.12

Si después de eso aún les figura caído Chilexpress, pueden probar cambiando al ambiente PROD.
Pero necesitarán el user y pass que no voy a compartir acá, por lo dicho en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/114#issuecomment-437449339

Saludos,
Esteban

**Comment by Rodolfinho21** [comment]
Estimados:
Gracias, actualizando al nuevo 1.4.2 y cambiando a producción, se logra que la API pueda calcular el envio,
Se agradece una API de shipping ayuda ene a canal e-commerce.
Gracias totales
Saludos,

**Comment by juanchomix** [comment]
Estimados: Felicitaciones por el gran aporte que hacen. Dicho lo anterior les comento que hace 2 días que tengo problemas con el plugin y la verdad es que a estas alturas ni idea a que se deberá el problema. Haciendo pruebas y con el plugin actualizado intente lo siguiente:
 
- Estando en modo WS PROD y con los datos proporcionados por @AndresReyesTech funcionaba bien hasta hace 2 días atras.
- Cambie a modo WS QA y elimine el usuario y contraseña que llaman a la API de Chilexpress, guarde los cambios pero aún asi no conecta para realizar los cálculos de envio.
- Cambié a modo WS PROD nuevamente, agregue los datos de usuario y contraseña proporcionados por @AndresReyesTech y nuevamente se conectó correctamente y apareció el cálculo de envío.

¿Alguna idea cuál es el problema?
¿Por qué no funciona en WS QA?
¿Alguna idea del trámite para solicitar user/pass como cliente para utilizar una API propia. Tiene algún costo en Chilexpress?

Gracias!!

**Comment by PatrickCaneloDigital** [comment]
en 1.4.12 puedo verificar el problema en ambiente QA (pese haber regrabado los ajustes)
No se si es idea mía o un tema de la coneción, pero encuentro que hoy la API está lenta.
Pero independiente  de eso el error de 1.4.12 es un error nuevo, no conectado a errores previos

En primera linea hay que saber que Chilexpress desactivó los antiguos enlaces de QA e implementó nuevas direcciones. Todo despues han sido intentos de poner el plugin al día con cambios que no tenemos documentación.

- el debug.log dice lo mencionado abajo. hay un problema en el wsdl
- es decir el esdl local no coincide con el wsdl de chilexpress
- Para que te den User/Pass en Chilexpress necesitas contrato mensual con ellos como cliente. 
Pero el problema no es user/pass, de hecho en producción para ambas APIs GeoReferencia y Tarificacion funciona el usuario de prueba.

Igual me estuve topando con un tema la última semana:
El plugin incluye los wsdl de las APIS de Chilexpress, en estricto rigor no es lo mas sensato ya que esos wsdl se definen también por el lado de la API, por ende es posible que Chilexpress haga cambios sin que "nos" enteremos y por ende el plugin dejaría de funcionar. El error apunta en esa dirección.
Los wsdl oficiales se encuentran directamente en la dirección de la API de Chilexpress:
"QA"
http://testservices.wschilexpress.com/GeoReferencia?wsdl
http://testservices.wschilexpress.com/TarificarCourier?wsdl

"PROD"
http://ws.ssichilexpress.cl/GeoReferencia?wsdl
http://ws.ssichilexpress.cl/TarificarCourier?wsdl

es decir no habría necesidad de incluir los wsdl dentro del plugin. sino llamar las URLs acá mencionadas



> [19-Nov-2018 16:48:38 UTC] PHP Fatal error:  SOAP-ERROR: Parsing Schema: can't import schema from 'http://testservices.wschilexpress.com:80/GeoReferencia?SCHEMA%2FPX_CorpGeoReferencia%2FPX000014_GeoReferencia%2FSpecification%2FWSDL%2FPX000014_CorpGR_ConsultarCoberturaRequest' in /home2/canelodi/public_html/dev/wordpress/wp-content/plugins/woo-chilexpress-shipping/includes/soap_call.php on line 53

**Comment by AndresReyesTech** [comment]
@PatrickCaneloDigital creo que el problema puede ser el siguiente (al menos el tema de velocidad y lag): el WSDL anterior se conectaba a un servidor nacional (ya que en el location aparece ssichilexpress.cl cuya IP es ) y en los nuevos se conecta a Azure que, según veo en [Microsoft](https://azure.microsoft.com/en-us/global-infrastructure/regions/) el más cercado está en Brasil.

Azure no tiene servidores en Chile sino afuera y, dependiendo del hosting, la conexión puede ser lamentable ya que los hosting nacionales usan con suerte 10mb compartido internacional.

**Comment by PatrickCaneloDigital** [comment]
si, eso mismo @AndresReyesTech También me di cuenta que cambiaron a Azure, parece que migraron la infraestructura y con eso han causado todos los problemas en el plugin...

Acabo de hacer un PullRequest con los cambios que mencioné... Los probé localmente y ocupando los wsdl en vivo (directamente de la Chilexpress API) me funciona bien el servicio en QA y PROD.

**Comment by TCattd** [comment]
Gracias @AndresReyesTech y @PatrickCaneloDigital nuevamente.

El cambio disponible en vivo en 1.4.13

**Comment by marisela72513** [comment]
hola....hice todo...cambie de ambiente borre cache transite pero no me salen sino como 5 comunas de la Región Metropolitana ...

**Comment by TCattd** [comment]
@marisela72513 https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
