### ISSUE TITLE
Calcular Impuestos

### ISSUE THREAD

**Issue by avagp** [whooohq/whq-woocommerce-chilexpress-shipping#115]
A la hora de generar los informes mensuales de ventas de mi sitio, veo también los impuestos.

Y es súper fácil, ya que tengo configurado el IVA en woocommerce.

Pero al final del día no puedo usarlo para calcular mis impuestos para la declaración mensual, ya que el informe no está contando con el IVA del envío.

![image](https://user-images.githubusercontent.com/11801254/48386123-b1c69380-e6cf-11e8-99e2-c890476895ee.png)

Y la razón es que si lo activo estaría cobrando de más.
Si es que activo el calculo el IVA al envío pasaré a cobrar 2 IVAs. Por ejemplo, en santiago los envíos salen $3.410, woocommerce me calcularía $3.410 + IVA, pero esos $3.410 ya tienen IVA incluído.

Sería ideal que pudiera configurar que los costos de envío se presentaran divididos por 1,19, de manera de poder activar el cálculo de IVA al envío y así los reportes de impuestos a final de mes estén correctos u otra solución similar que me calcula el IVA de los envíos.

Saludos!

**Comment by PatrickCaneloDigital** [comment]
A nivel de impuestos no estoy seguro si es correcto lo que pides...
La venta esta sujeta a un IVA que tu tienes que declarar.
El servicio de Chilexpress es un servicio que tu contratas, pero el cliente te lo paga previamente. Chilexpress te cobra a ti el IVA, no al cliente. Y por ese IVA pagado a Chilexpress.
Es decir en tus libros no es un IVA que tu tengas que pagar ni declarar.

Es decir por lo que sé, ese IVA no lo declara la tienda, lo declara Chilexpress.

**Comment by avagp** [comment]
A mi me entregan una boleta por el servicio a final de mes, que incluye el
envío.

**Comment by PatrickCaneloDigital** [comment]
A lo que voy es que Woocommerce en esa mascara detalla el IVA de tus ventas.
El IVA del envío es un IVA de las ventas de Chilexpress. 
La tienda es solo un intermediador. En el costo de envio, el IVA ya está incluido y el cliente lo paga a traves tuyo a Chilexpress.

O explicandolo de otra forma:
Los impuestos que aparecen en woocommerce son de tus ventas. Un IVA que tu tienes que declarar ante el SII.
El IVA del envío lo declara Chilexpress ante el SII.

**Comment by TCattd** [comment]
Aunque concuerdo con @PatrickCaneloDigital  en este caso, entiendo que va por un tema de configuración de cobros de impuestos de forma global en la tienda.

Afortunadamente, WooCommerce tiene una API para esto: http://prntscr.com/libab9
Si lo dejas en "Ninguno" (desactivado), WooCommerce no debería incluirlo en su cálculo de impuestos.

Va en la versión 1.4.11 ;)
Por default en "Ninguno" (desactivado), para que no haya cambios y no afecte a quienes actualizan el plugin.

Me avisas si va todo ok con eso @avagp, por favor.

**Comment by avagp** [comment]
Hola Esteban.
Mi woocommerce está ya configurado con el impuesto y me sirve como está,
pero efectivamente me falta el tema del envío.

Patrick, contablemente yo soy el que debe cobrar el impuesto del envío,
porque chilexpress me pasa un factura a mi. Sino estaría dando una boleta
por el valor del producto sin incluir el envío y sería un ingreso sin
declarar. Yo no contrato a chilexpress por servicio como persona por vez,
sino que como empresa un servicio mensual variable.

No solo para mi es particularmente cómodo poder ver el reporte de impuesto
correcto a final de mes y no estar haciendo cálculos en un excel, sino que
considero que cualquier empresa tener el output a final de mes es más
cómodo.

Saludos y gracias por sus comentarios!

**Comment by PatrickCaneloDigital** [comment]
Alvaro
Creo que estamos topando con un tema de comprehensión como funciona woocommerce:
Acabo de hacer una prueba en mi ambiente de desarrollo, activando los impuestos y una vez marcando la casilla "envio" y una vez "no marcandola".
En ambos casos no me cambió ninguno de los montos (ni el de impuestos ni el de costo de envío):
y no estoy seguro, si actualmente es un problema de woocommerce, que al menos en mis pruebas, independiente si la casilla esta marcada o no, el IVA es solo aplicado a los productos y no al envio, o si es un problema del plugin.

Puede ser un tema conceptual: 
En Alemania tipicamente los cotos de envio efectivamente no estan basados solo en el costo del courier, sino se le añaden costos de empaque y logistica. Ademas que el cliente no le importa con que courier funciona la empresa, simplemente paga los costos de envio.

Actualmente no sé si es un problema del plugin, que no contemplé el ajuste en la casilla "envio"
![grafik](https://user-images.githubusercontent.com/11801254/48386123-b1c69380-e6cf-11e8-99e2-c890476895ee.png)
o si tiene que ver con el hecho que el servcio queda externalizado y woocommerce lo reconoze...
Analizando a fondo creo que efectivamente los dos issues (tanto el costo de empaque, como este de calculo de IVA) tienen su fundamento y habría que cambiar el plugin bastante, tambien su enfoque, y verlo como un plugin que ofrece "Costo de envio ocupando Chilexpress". Siendo el courier casi secundario.
El gran problema que veo en esto es que esta forma de pensar aun no esta internalizada ampliamente en Chile, aun se entiende erroneamente, que el costo de envio es solo lo que te cobra starken, chilexpress o cruzdelsur para enviar una encomienda y no todo el proceso logistico.

Pero resumiendo, y te pido alvaro hacer las pruebas:
A ti te cambian los impuestos o el costo de envio si marcas la casilla de "envio" en la seccion de impuestos? A mi no. y me queda la duda si es porque el metodo de envio (segun plugin) le falta tener en cuenta ese dato, o si Woocommerce reconoze el metodo de envio chilexpress como uno que es externalizado y por ende siempre lleva el IVA incluido y no le calcula el IVA.

Para transformar el plugin al concepto mas amplio sería un trabajo masomenos mayor que sin auspicio va a ser complejo encontrar un voluntario... (bueno, la esperanza muere al último.) 

![grafik](https://user-images.githubusercontent.com/21183922/48528132-64cbf400-e86c-11e8-9d93-b66ddabd86c4.png)

**Comment by avagp** [comment]
Hola Patrick

La manera de que woocommerce te aplique el impuesto al envío es creando un
método de envío que sea imponible (la opción por defecto)
[image: image.png]

De esa manera se aplicará el impuesto.

Por lo que si el envío le colocas como costo $1.000 en el checkout te
cobrará $1.000 + IVA

Y en el caso particular del plugin, como los $3.410 que sale el envío
dentro de Santiago ya tienen incluído el IVA, cobrará una IVA adicional.

De modo, que el precio debería ser *[costo_envío]/1,19 * para que al final
al aplicar el impuesto me quede igual, y en el reporte de impuesto quede
correctamente capturado el impuesto.

Concuerdo contigo que las tiendas en Chile no están tan profesionalizadas
aún que puede que no sepan que tienen que cobrar la logística y el impuesto
al cliente. Por eso lo planteaba como una opción, pero también entiendo que
es un desarrollo que implica tiempo y dinero.

Muchas gracias por tu respuesta.

Saludos!
