### ISSUE TITLE
Chilexpress no se encuentra disponible en este momento!

### ISSUE THREAD

**Issue by Fermormac** [whooohq/whq-woocommerce-chilexpress-shipping#116]
Hola!
Mi calculadora de chilexpress dice "Chilexpress no se encuentra disponible en este momento..."
Es un problema mio o del plugin?

Saludos!

**Comment by TCattd** [comment]
Estimado,

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/114#issuecomment-438040420

Saludos,
Esteban

**Comment by Fermormac** [comment]
Gracias!
