### ISSUE TITLE
Envío Chilexpress más envío Gratuito

### ISSUE THREAD

**Issue by NVMDSN** [whooohq/whq-woocommerce-chilexpress-shipping#119]
Buenas noches. Primero que todo, gracias por este complemento, es realmente útil.
Una pregunta, normalmente Woocommerce viene con un sistema para configurar envío gratuito de acuerdo a ciertas variables, por ejemplo, por ciudad. Es posible hacer compatible el envío gratuito de WC con este plugin?
Como ejemplo: En Woocommerce, Zonas de envío, agrego RM como envío gratuito, pero el plugin de Chilexpress no tengo como configurar esto, por lo tanto una opción dice Gratis y justo abajo la de Chilexpress con su respectivo valor. Es posible hacer algo para que este también indique "Gratis" ya que está dentro de la misma zona de despacho. Gracias nuevamente.

**Comment by TCattd** [comment]
Estimado,

La compatibilidad con las zonas de envío no está lista aún.
Dejo el issue que trata este tema https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39

Saludos
Esteban
