### ISSUE TITLE
Chilexpress no disponible! 1.4.15

### ISSUE THREAD

**Issue by Rodolfinho21** [whooohq/whq-woocommerce-chilexpress-shipping#120]
Buenos días estimados:
Actualice wordpress a 5.01 hoy 13.12.2018 y ahora me figura chilexpress no disponible, tengo la versión 1.4.15 
Se habrá caído el servidor?. Lo otro que me fije que con las mismas dimensiones y peso del envío aplicándolo en la API es diferente en el portal de chilexpress (me da otro valor).

Atento a sus comentarios

Saludos,

**Comment by TCattd** [comment]
http://wpchilexpress.whooohq.com/checkout/ aún arriba http://prntscr.com/luhjwl

Aunque es posible que la API QA de Chilexpress esté abajo nuevamente. Podría ser algo temporal.

La sugerencia dada en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/114#issuecomment-439194333 sigue en pie en todo caso. Por si quieren probar.

Dejo abierto mientras, para mantener comentarios respecto a la caída en un solo issue.
Gracias por reportar, @Rodolfinho21

**Comment by Rodolfinho21** [comment]
Estimado gracias por responder,
cambie a producción y funciona correcto y se actualizo los valores (chilexpress subió los precios de envíos)

como dato adicional, a partir de 1 enero 2019 chilexpress no entregara mas bolsas plásticas y solo se recibirá encomiendas con cajas se esta alineando a la ley nueva que salio hace unos meses.
a tener en cuenta.
saludos.

**Comment by PatrickCaneloDigital** [comment]
Efectivamente @TCattd y @Rodolfinho21 es QA que de nuevo esta abajo:

Hice una página de estatus con cronjob horario que va probando disponibilidad. 
https://www.canelodigital.cl/chilexpress_status.html

En un momento que no tenga mucho que hacer voy a incluir historial y todo... por el momento es solo "snapshot" cada hora...
