### ISSUE TITLE
Status de la API de Chilexpress en configuración del plugin

### ISSUE THREAD

**Issue by TCattd** [whooohq/whq-woocommerce-chilexpress-shipping#121]
Algo simple, como lo hecho acá por @PatrickCaneloDigital https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/120#issuecomment-447113876

No tiene que tener historial de caídas ni nada. Básicamente solo un checkeo en tiempo real al momento de cargar la config del plugin, ¿vía AJAX?, para saber si la API de Chilexpress está arriba o no, y evitar issues que se repiten un montón como el #120 

Ayuda es bienvenida :)

**Comment by PatrickCaneloDigital** [comment]
si no te importa referenciar a
http://www.canelodigital.cl/chilexpress_status.html
podría hacer un PR en cosa de minutos
ese html es renovado cada hora y se puede incluir facilmente en la config...
De hecho lo hice justamente para estos fines.

Como alternativa también puedo incluir el codigo php y que se genere en ese mismo momento de la vista.
La prueba en cada carga de la config se demora si un buen rato, por eso opté de hacerlo con un cronjob y referenciar solo el html via iframe.

**Comment by TCattd** [comment]
Estimado,

Preferiría que esto estuviese contenido en el plugin, y que no dependa de un servidor de un tercero. La idea es que directamente checkee los servidores de Chilexpress (los dos activos nada más).

Me imagino que la respuesta debe ser lenta. Por lo mismo mencioné la llamada Ajax para traer esos resultados sin bloquear la carga y uso de la configuración del plugin mientras el script traiga ese status y dibuje algo ahí. No sé si me explico.

Lo puedo hacer la verdad, por eso subí el issue. Tu idea fue muy buena, y estoy muy agradecido por ella.
Pero no tengo tiempo ahora para matar esto.
Ahora si nadie más lo hace, cuando tenga tiempo libre, lo hago igual :)

No hay apuro ;)

**Comment by PatrickCaneloDigital** [comment]
Claro, entiendo. 
Mira, te envio por correo el archivo PHP que verifica el estado de las APIs, y quedaría solo pendiente incluirlo via llamada ajax... 

Si encuentro tiempo estos días te hago un PR con la implementación completa, y si te adelantas, por último tienes el avance con la verificación de las APIs ;)

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
