### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by Omariuschile** [whooohq/whq-woocommerce-chilexpress-shipping#122]
Hola
Muy buen plugin... pero me sale este error:
Warning: A non-numeric value encountered in /home/sitio/public_html/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 427

Alguna idea de como solucionarlo?
Muchas Gracias!!!

**Comment by TCattd** [comment]
¿Qué versión de WooCommerce estás corriendo, estimado?

¿Qué versión del plugin de Chilexpress tienes instalado?

**Comment by Omariuschile** [comment]
Las versiones:
woo-chilexpress-shipping.1.4.15
WordPress 4.9.9
Es extraño, ahora no aparece el error.
No he modificado nada, muchas gracias por la preocupación de todos modos!!!

**Comment by TCattd** [comment]
La linea que menciona el error que te dio, se encarga del cálculo del peso del item en WooCommerce para pasarlo a la API de Chilexpress luego.
No debería no haber un número ahí.

¿Tienes todos los productos definidos con su tamaño y peso?

**Comment by truchosky** [comment]
a mi también me apareció este error con la ultima version de todo, wordpress, woocommerce y plugin
