### ISSUE TITLE
[woocommerce_my_account] no muestra desplegables

### ISSUE THREAD

**Issue by Omariuschile** [whooohq/whq-woocommerce-chilexpress-shipping#124]
Estimados
El plugin funciona perfectamente en la página [woocommerce_checkout]
Pero al ingresar a [woocommerce_my_account] los campos de Región y Comuna no se muestran con lista desplegable, solo como campo de texto.
Para habilitar es tema de configuración o se debe modificar el código?
Muchas gracias

**Comment by TCattd** [comment]
Estimado,

Sigue las recomendaciones descritas acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Si con eso el plugin funciona y bien, es altamente probable que el problema sea de tu theme activo o algún plugin instalado modificando los default de WC.

Nos comentas, por favor.

**Comment by KraptorChile** [comment]
Hola!!!, muchas gracias por el plugin.

Lamentablemente sólo se me desplegan algunas localidades, para RM sólo se desplegan 

Alto Jahuel; Batuco; El Paico; Lonquen; Malloco; Nos; Chicureo

Tampoco calcula el total de $, el valor queda siempre en $0

Probé en Chrome y en explorer

**Comment by masterjpx** [comment]
> Hola!!!, muchas gracias por el plugin.
> 
> Lamentablemente sólo se me desplegan algunas localidades, para RM sólo se desplegan
> 
> Alto Jahuel; Batuco; El Paico; Lonquen; Malloco; Nos; Chicureo
> 
> Tampoco calcula el total de $, el valor queda siempre en $0
> 
> Probé en Chrome y en explorer

**Hola!! Me pasa exactamente lo mismo hace como 3 días. Actualicé el plugin, reinstalé WP y aún tengo el mismo problema. Ya no se que hacer.
https://unsee.cc/988099cb/**

**Comment by TCattd** [comment]
@KraptorChile @masterjpx el issue abierto no se trata de lo que están comentando acá ustedes.
Ojo con eso, por favor.

Para vuestro problema, deberían abrir otro issue.
De todas formas les comento que acá http://wpchilexpress.whooohq.com/checkout/ está funcionando sin problemas http://prntscr.com/m06ssw

Si el listado de ciudades se devolvió con menos ubicaciones, puede ser que la API de Chilexpress en el momento en que estaban consultando haya estado con problemas.
Esos listados, de regiones y ciudades en cada región, viene directo de la API de Chilexpress. Si se devuelve con menos resultados o errores, es problema con la API y no directamente del plugin.

Solo les queda esperar a que la API devuelva los resultados correctos.
De todos modos, como dije en un comienzo, en http://wpchilexpress.whooohq.com/checkout/ está funcionando sin problemas http://prntscr.com/m06ssw

Abrir otro issue si sus inconvenientes continuan, por favor. Este no tiene que ver con lo que comentan acá.

Gracias.

**Comment by KraptorChile** [comment]
Toda la razón, generaré un nuevo issue. Gracias!
