### ISSUE TITLE
Despliegue sólo de algunas Localidades/Ciudades

### ISSUE THREAD

**Issue by KraptorChile** [whooohq/whq-woocommerce-chilexpress-shipping#128]
**24/12/2018**

Hola!!!, muchas gracias por el plugin.

Lamentablemente sólo se me desplegan algunas localidades, para RM sólo se desplegan:

Alto Jahuel; Batuco; El Paico; Lonquen; Malloco; Nos; Chicureo

Tampoco calcula el total de $, el valor queda siempre en $0

Probé en Chrome y en explorer

**27/12/2018**

Verifiqué hace unos minutos y tengo el mismo problema.

**Comment by TCattd** [comment]
Como registro, copio lo dicho en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/124#issuecomment-450162197

...

De todas formas les comento que acá http://wpchilexpress.whooohq.com/checkout/ está funcionando sin problemas http://prntscr.com/m06ssw

Si el listado de ciudades se devolvió con menos ubicaciones, puede ser que la API de Chilexpress en el momento en que estaban consultando haya estado con problemas.
Esos listados, de regiones y ciudades en cada región, viene directo de la API de Chilexpress. Si se devuelve con menos resultados o errores, es problema con la API y no directamente del plugin.

Solo les queda esperar a que la API devuelva los resultados correctos.
De todos modos, como dije en un comienzo, en http://wpchilexpress.whooohq.com/checkout/ está funcionando sin problemas http://prntscr.com/m06ssw

Abrir otro issue si sus inconvenientes continuan, por favor. Este no tiene que ver con lo que comentan acá.

...

Agrego:

Por favor, instala este plugin https://wordpress.org/plugins/transients-manager/ y borra todos los cachés que comienzan con "whq_wcchp_".
Luego vuelve a intentar, y nos comentas.

**Comment by KraptorChile** [comment]
Gracias,

Plugin Instalado, whq_wcchp_ borrados todos, problema continúa

RM --> Alto Jahuel; Batuco; El Paico; Lonquen; Malloco; Nos; Chicureo

Novedad: Las siguientes comunas presentan valores distintos a $0: Batuco; Lonquen; Malloco; Chicureo

**Comment by TCattd** [comment]
Estimados,

Es problema de la API de Chilexpress. Pero solo del ambiente WS QA.
Ante eso, como plugin (y sin estar afiliados con Chilexpress), no podemos hacer nada.

Si lo desean, pueden cambiar al ambiente WS PROD, pero necesitarán el user/pass que por lo dicho acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/114#issuecomment-437449339 no voy a compartir aquí o en el plugin.

De todos modos es un dato bastante "sencillo" de Googlear.

En resumen, las opciones:
1.- Esperar a que Chilexpress arregle ese problema. Si son clientes de ellos en https://portalempresa.chilexpress.cl/HomeNew.aspx pueden intentar contactarlos a ellos para saber qué pasa con el ambiente QA de su API (Webservices).
2.- Cambiar al ambiente WS PROD.

Dejaré abierto por si llega más gente con el mismo problema.

**Comment by jpromeroo** [comment]
Encontre un usuario y pass en google , pero tampoco se arreglo el problema!

No se si sera la contraseña correcta :(

**Comment by KraptorChile** [comment]
Resuelto hasta el momento!!

Cambie a Ambiente WS PROD
Borré Cookies, Transients

Funciona, no se a que se debe, pero funciona.

Saludos y gracias

**Comment by AndresReyesTech** [comment]
Por si alguien necesita saber como borrar los transients, copien y peguen lo siguiente en el functions.php (antes de cualquier cosa respalden):

```
function chilexpress_delete_all_transients() {
 
    global $wpdb;
 
    $sql = 'DELETE FROM ' . $wpdb->options . ' WHERE option_name LIKE "% _whq_wcchp_%"';
    $wpdb->query($sql);
 
}
add_action( 'init', 'chilexpress_delete_all_transients' );
```
Esto borrará los transients sin instalar algún plugin intermedio. Ingresen a la portada del sitio y actualicen. Listo!

No se olviden de borrar estas líneas ya que si las dejan estarán borrando los trasients en cada visita y no tendrán cache de ubicaciones.

Y si alguien necesita el usuario y contraseña borrado que no puede ser publicado acá puede acceder a https://gist.github.com/AndresReyesTech/7061eabd52f3f6e32f3e16360e524cf9

**Comment by Mlizana** [comment]
Hola y gracias, para mi también funciono lo mencionado por TCattd y KraptorChile !!

Resuelto con WS PROD , borrar cookies y transients.

Gracias nuevamente

**Comment by Caro-H** [comment]
Hola, he hecho todo lo que sugieren, y si bien ahora me aparecen todas las comunas solo algunas muestran tarifas (por ejemplo Batuco) pero con otras comunas (las condes, nunca, etc) la opción de despacho con Chilexpress no me parece como disponible.

A alguien le ha pasado algo similar?

**Comment by JayEdg** [comment]
Hola y gracias! Instale plugins/transients-manager/ siguiente tus instrucciones y ahora muestra correctamente todas las comunas de RM.

**Comment by arongold** [comment]
Esteban:
Solo quería agradecerte! por tu post, no soy técnico, me ha ayudado mucho, también había estado preocupado por las comunas y todo funcionó como lo explicaste, sobretodo un tema nuevo para mí, como lo es Transients Manager!

**Comment by TCattd** [comment]
No hay de que, arongold.

Pero debemos agradecer a la comunidad también por la ayuda colectiva en este tipo de problemas.

No soy yo solo acá ;)

De todas maneras, que bueno que todo esté andando por vuestro lado con el plugin.

**Comment by crokis** [comment]
@TCattd gracias, solucionado. No había visto esto en los abiertos. Salu2!

**Comment by arongold** [comment]
Esteban: 
Tengo problemas con la nueva actualización del plugin de Chilexpress para wordpress v.5.2 
Mensaje: Este plugin aún no ha sido probado en tu versión actual de Wordpress 5.2. Cuando estará habilitada? Saludos

**Comment by TCattd** [comment]
@arongold aquel mensaje es solo una advertencia. No un error.

El plugin funciona con el último WordPress y WooCommerce.

Para que eso no "moleste" debo lanzar una actualización del plugin que solo cambia el número en estas líneas https://i.imgur.com/yHpv4tL.png

Y, personalmente, considero que es más molesto incomodarlos con una actualización que no suma nada, ni un bugfix, a... Mantener eso al día.

Puede que me equivoque y que en masa crean que es mejor que mantenga eso al día.

La verdad, no lo sé. Estoy abierto a sugerencias.

Pero... En otro issue, por favor. Este no es para tratar ese tema.

**Comment by danielirow** [comment]
instalé el plugin >> borré todos los que comienzan con "whq_wcchp_" >> en el ajuste de chileexpress cambié a WS PROD....... et voila, funciona. Gracias!

**Comment by arongold** [comment]
Gracias!

Aron Goldbaum
Celular.: +56 9 98213772

**Comment by carlosver17** [comment]
Hola! 

Junto con saludar quisiera comentar que tengo el problema con que no aparecen todas las cuidades pero sólo las de la región metropolitana. He probado otras regiones y funcionan, al parecer, correctamente.

Borré cache, transients, cambié a WS PROD, deshabilité plugins pero el problema se mantiene.

Alguna recomendación?


Saludos,

**Comment by joseguzmanww** [comment]
Hola he hecho todo lo que indican varias veces y no me funciona. 
Hay alguna solución más actual? 
Gracias

**Comment by ElMario7** [comment]
Muchas gracias por esta solución.

**Comment by ensonthode** [comment]
Amigos disculpen pero estoy super perdido aquí: si la solución a este issue especifico **(Despliegue sólo de algunas Localidades/Ciudades #128)** es cambiar a WS-PROD pero para esto hay que insertar las credenciales y para tener las credenciales hay que pasar toda una validación con el plugin oficial no es un poco como dar vueltas?

@TCattd Por favor podrías ver mi sitio y sugerirme un flujo de trabajo.
https://gmmedical.cl/checkout/
[](https://gmmedical.cl/checkout/)


Gracias de antemano por su tiempo.

**Comment by TCattd** [comment]
@ensonthode no necesitas pasar por un proceso de validación. Solo necesitas el usuario y contraseña, que puedes encontrar Googleando. Ver: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128#issuecomment-450372000

Esteban

**Comment by ensonthode** [comment]
@TCattd Muchas gracias por tu pronta respuesta, después de Googlear y con un poco de astucia... conseguí las credenciales completas: **usuario y contraseña**, también borré los transients con el plugin y utilizando el snippet que se menciona mas arriba, Pero aun nada.. sigue cargando una lista parcial de las comunas en Región metropolitana.
Es posible que esta solución ya no sea eficaz ?

**Comment by TCattd** [comment]
Esa misma solución es la que se usa en http://wpchilexpress.whooohq.com/
Si ves que funciona bien el checkout en aquel sitio, entonces no es problema de ese combo de usuario/pass ni del plugin en general.

Sin inconvenientes a esta hora: https://tppr.me/ricl0

Esteban

**Comment by ensonthode** [comment]
Perfecto ahora si funciona, resulta que por error no borré **todas** la transients con **"whq_"**  
@TCattd Gracias por el apoyo, ya estaba perdiendo la cabeza y a mi cliente en esto...

**Comment by TCattd** [comment]
@Kingxito actualiza a la última versión del plugin, por favor.
