### ISSUE TITLE
Problema "undefined" en Localidad/Ciudad

### ISSUE THREAD

**Issue by carlohj** [whooohq/whq-woocommerce-chilexpress-shipping#129]
Ayer durante la tarde nos informaron que al elegir, por ejemplo, la región de Los Lagos, aparecian solamente 2 opciones en Localidad/Ciudad. Tras esperar pensando que era un problema de Chilexpress que se solucionaría en un rato, hoy, tras ingresar Region/Provincia, aparecen solo opciones "undefined".

Ayuda!
![under](https://user-images.githubusercontent.com/46353020/50649203-09f57580-0f5c-11e9-90d1-7bd8e41aafef.png)
![undefine](https://user-images.githubusercontent.com/46353020/50649205-09f57580-0f5c-11e9-965b-c4280951837a.png)

**Comment by AndresReyesTech** [comment]
Duplicate of #128

**Comment by TCattd** [comment]
Gracias @AndresReyesTech ;)
