### ISSUE TITLE
Error: Warning: in_array() expects parameter 2 to be array, string given in 

### ISSUE THREAD

**Issue by carlospalmab** [whooohq/whq-woocommerce-chilexpress-shipping#130]
Hola, primero que todo gracias por el plugin!

Tengo dos problemas:
1 - Cuando ingreso direcciones de envio en el checkout, me indica:
"No hay métodos de envío disponibles. Por favor, asegúrate de que has introducido correctamente tu dirección, o contáctanos si necesitas ayuda."
2 - Me aparece los siguientes errores:
Warning: in_array() expects parameter 2 to be array, string given in /home4/carlospalmab/tienda.theremixstyle.com/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 749

Warning: in_array() expects parameter 2 to be array, string given in /home4/carlospalmab/tienda.theremixstyle.com/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 749

Warning: in_array() expects parameter 2 to be array, string given in /home4/carlospalmab/tienda.theremixstyle.com/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 749

Warning: in_array() expects parameter 2 to be array, string given in /home4/carlospalmab/tienda.theremixstyle.com/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 749

Segui las instrucciones, y tengo todo actualizado, storefront instalado/activado, y solamente los plugins Woocommerce y Chilexpress shipping activados.
Tambien tengo activado el WS PROD.

Que puede ser?

Saludos y gracias!

**Comment by AndresReyesTech** [comment]
Al parecer te falta seleccionar los tipos de despacho.

![screen shot 2019-01-04 at 19 08 04](https://user-images.githubusercontent.com/5054870/50713524-1bba4400-1054-11e9-8263-ef08761ff115.png)

**Comment by TCattd** [comment]
¿Alguna novedad, @carlospalmab, con lo dicho por AndresReyesTech?

Nos comentas, por favor.

**Comment by TCattd** [comment]
Reabrir si el problema persiste, por favor.
