### ISSUE TITLE
Se asignan mal las comunas a las regiones

### ISSUE THREAD

**Issue by emizadesign** [whooohq/whq-woocommerce-chilexpress-shipping#131]
Hola!

Les escribo a ver si me pueden ayudar a resolver este problema.
Las comunas de la Región metropolitana aparecen al seleccionar la Región Arica y Paranacota.
Al seleccionar la Región metropolitana me aparecen Alto Jahuel, Batuco, El Paico, Lonquen, Malloco, Nos y Chicureo.

Ya desactive todos los plugins relacionados y no se soluciona.

He leido que es algo de las API qe cargan mal, pero veo que esto le está sucediendo a varias personas.

¿Me podrían ayudar por favor?

**Comment by TCattd** [comment]
Estimado(a),

¿Hiciste el cambio sugerido en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128#issuecomment-450372000 en la configuración del plugin?

**Comment by emizadesign** [comment]
Listo! Muchas gracias!! Me funcionó perfectamente!!

**Comment by TCattd** [comment]
Duplicado de #128
