### ISSUE TITLE
Solo algunas comunas del listado tarifan

### ISSUE THREAD

**Issue by Caro-H** [whooohq/whq-woocommerce-chilexpress-shipping#134]
Hola, he hecho todo lo que sugieren en issues anteriores (128) elimine transients y cookies, y si bien ahora me aparecen todas las comunas, sólo algunas muestran tarifas (por ejemplo Batuco) pero con otras comunas (las condes, ñuñoa, providencia, etc) la opción de despacho con Chilexpress no me aparece. 

A alguien le ha pasado algo similar?

**Comment by TCattd** [comment]
https://cl.ly/ec6cca948046

https://cl.ly/472b39f39854

Puedes probar en vivo en http://wpchilexpress.whooohq.com

Asegúrate de tener los tipos de envíos seleccionados en la configuración del plugin https://cl.ly/74d1f1ed1ec2
En esa zona, nunca deberían no estar: día hábil siguiente, día hábil subsiguiente, tercer día.

**Comment by TCattd** [comment]
Nos avisas si eso no ayudó, por favor.
