### ISSUE TITLE
Regiones con comunas no correspondientes

### ISSUE THREAD

**Issue by dhenriquez** [whooohq/whq-woocommerce-chilexpress-shipping#135]
Estimados,
les comparto este error que me esta ocurriendo en mi sitio web:

[https://youtu.be/b-d6UstRnv4](url)

Luego de seleccionar alguna de las regiones, se cargan las comunas pero no son las que corresponden y en algunos casos me dice que no están definidas.

Woocommerce Versión 3.5.4
Wordpress 5.0.3

Saludos!

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128#issuecomment-450372000

Seguir instrucciones allá, por favor.
