### ISSUE TITLE
Plugin Chilexpress No arroja precios

### ISSUE THREAD

**Issue by AgenciaSchaefer** [whooohq/whq-woocommerce-chilexpress-shipping#136]
Hola. Escribo para consultar con respecto a que el plugin de Chilexpress no me arroja precios (sólo aparecen dos signos de paréntesis). He probado de varias formas y sin embargo, el plugin no me da datos de envío. Probé con el soap pero está activado. Ojalá me puedan ayudar. Saludos

**Comment by TCattd** [comment]
¿Puedes probar lo comentado acá, por favor?

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128#issuecomment-450372000

Cambio de ambiente de la API.
Nos comentas cómo te va, por favor.

**Comment by TCattd** [comment]
Reabrir si la solución no sirvió, por favor.
