### ISSUE TITLE
Incluir precio fijo a algunas regiones

### ISSUE THREAD

**Issue by ingeniumcl** [whooohq/whq-woocommerce-chilexpress-shipping#137]
Hola tengo integrado Chilexpress en el sitio web de mi cliente, pero le gustaría agregar un precio fijo para santiago. Existe algún plugin compatible para esto o alguna forma de limitarlo para regiones sin tener que entrar a editar directamente el plugin?

**Comment by TCattd** [comment]
Lo que pides está fuera del propósito de este plugin, estimado.

Puedes probar:
https://woocommerce.com/products/woocommerce-advanced-shipping-packages/
O Googlear por alguno que te sirve.

Saludos ;)
Esteban
