### ISSUE TITLE
Campo para ingresar RUT y cambiar orden de región y comuna

### ISSUE THREAD

**Issue by Rochamen** [whooohq/whq-woocommerce-chilexpress-shipping#138]
Por favor ingresar un campo para insertar Rut del cliente. 
Ademas por favor voltear campos de ingreso de región y comuna. Están al revés.

**Comment by AndresReyesTech** [comment]
Creo que el plugin no está pensado para ello. Eso puedes lograrlo con algún editor de campos del checkout de WooCommerce. El plugin es un calculador de despacho y se limita a eso. Cualquier otra gestión debe ser realizada directamente en Woocommerce y con otros plugin o código en functions.php

Ojo: Puedes agregar nuevos (como el Rut) y reordenar los campos del checkout pero **jamas** eliminar o desactivar algún campo por defecto.

**Comment by TCattd** [comment]
Como dice @AndresReyesTech (¡gracias!).

Esto ya ha sido conversado antes:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/19
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/89

Sobre el RUT, tampoco es algo que este plugin deba resolver, me parece.
El foco es el cálculo del despacio vía Chilexpress. Nada más.

Para lo que quieres, esto puede ayudarte https://wordpress.org/plugins/woo-checkout-field-editor-pro/ en ambos casos, reorden y nuevo campo con el RUT.
