### ISSUE TITLE
desconfiguración de los campos

### ISSUE THREAD

**Issue by jpccea** [whooohq/whq-woocommerce-chilexpress-shipping#139]
el problema es que en el campo de región metropolitana no muestra las comunas correspondiente y en la region de antartida chilena muestra todas las comunas de metropolitana esto estoy tratando de entender por que pasó?, gracias si me pueden ayudar

**Comment by TCattd** [comment]
Por favor, revisar: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
