### ISSUE TITLE
Undefined variable: suffix in /var/www/html/wp-content/plugins/woo-chilexpress-shipping/includes/scripts.php on line 17

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#14]
Estimados, me figura este error, no se si afecte en el funcionamiento del plugin.

**Comment by TCattd** [comment]
Eso me pasa por hacer esto tan tarde. La edad.

Resuelto.

Gracias por el aviso ;)
