### ISSUE TITLE
Campo de ciudad/comuna no se autocompleta al pasar del carro al checkout

### ISSUE THREAD

**Issue by hibamiru** [whooohq/whq-woocommerce-chilexpress-shipping#140]
En la página del carro si uno llena los datos de estado y ciudad para calcular el envío ambos datos se guardan en la sesión de woocommerce. Sin embargo al momento de proceder al checkout el único campo que aparece prellenado es el Estado, la ciudad no se autollena.

Lo anterior obliga al usuario a llenar nuevamente el campo de ciudad/comuna al momento de visitar la página del checkout.

**Comment by TCattd** [comment]
Esto tiene que ver con el delay que hay entre que el plugin debe consultar por el listado de ciudades, esperar la respuesta de la API de Chilexpress (o el transient con los datos), y cuando eso queda realmente listo después que BlockUI "suelta" ese campo y queda operativo.

Habría que ver como esperar a que BlockUI esté listo, y consultar si existe ese dato (ciudad) en la sesión de WC. Si existe, seleccionarlo.

**Comment by hibamiru** [comment]
Enterado, muchas gracias!

**Comment by TCattd** [comment]
A ti, estimado.

Una vez el tiempo acompañe, podría sentarme a ver esto.

Si es que alguien más no lo quiere tomar antes y ayudar con el plugin, claro. Pull Requests son bienvenidos ;)

**Comment by crokis** [comment]
Hola! Antes que todo agradecer por este trabajo. Es un buen aporte!

Tengo problemas con la selección de comunas y regiones en ambas partes del sitio (carro y check-out) donde las comunas que aparecen en RM no están todas y muchas me aparecen en ARICA, por ejemplo VITACURA está en ARICA y no en RM.

Tengo todo actualizado y todo el resto apagado. Desinstalé todo y volví a hacerlo con el mismo resultado. Probado en diferentes navegadores y tengo lo mismo.

Qué podría ser? Cómo saber si el problema es de Chilexpress?
Grx!

**Comment by TCattd** [comment]
@crokis no usar un issue que no tiene nada que ver con el problema que tienes, para buscar ayuda respecto a ese problema. Por favor.

Revisar issues existentes. Tu problema es un duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Gracias

**Comment by michalexvr** [comment]
Bueeeenaaa TC, de la época del antro que no te leía, me reclamaron de soporte porque había un error en la selección de ciudades y comunas en un ecommerce que hice el año pasado. Estaba viendo porqué chucha se me pisaban los campos de ciudad y región y vi que es este plugin el que provoca el conflicto. Al parecer la API de chilexpress trae de vuelta cualquier chambonada menos la región que realmente corresponde con la comuna.

Puedes darle una cachureada a mi plugin por acá, al menos hay varios que le han dado uso y funciona bien, claro, hasta que empiezan las integraciones.

https://github.com/michalexvr/woocommerce-plugin-regiones-y-ciudades-de-chile

**Comment by TCattd** [comment]
@michalexvr buen día.

Lo siento, pero lo que reportas no tiene en lo absoluto que ver con el issue original acá tratado.
Ojo con eso.

Tu problema seguramente es similar a los que se experimenta con otros plugins semejantes en funcionalidad: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-326564653

**Comment by michalexvr** [comment]
Gracias por tu respuesta, el problema, más allá de la incompatibilidad que es razonable dado que se pisan los mismos campos, si elimino mi plugin y dejo solo funcionando el de chilexpress, no aparecen correctamente las comunas con sus respectivas regiones, por ejemplo, en Tarapacá aparecen comunas que realmente corresponden a la Región Metropolitana, en otras no aparece nada, en otras un par de undefined, etc etc.

Tengo entendido que estás consumiendo la API de Chilexpress, la sensación es que el error viene de allá la verdad.

Saludos.

**Comment by TCattd** [comment]
@michalexvr https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#no-se-muestran-todas-las-ciudades-dentro-de-una-regi%C3%B3n

**Comment by michalexvr** [comment]
Buenísima, muchas gracias Esteban, un abrazo.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
