### ISSUE TITLE
Funciona en Wordpress 5.1.1?

### ISSUE THREAD

**Issue by juanand87** [whooohq/whq-woocommerce-chilexpress-shipping#141]
Hola, primero quiero felicitarlos por el plugin.

¿Quisiera saber si funciona con la versión 5.1.1 de wordpress? Ya que al seleccionar la región, la lista desplegable de ciudades me aparece incompleta en algunas regiones.

Saludos.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
