### ISSUE TITLE
Problemas con la selección de comunas y regiones en (carro y check-out

### ISSUE THREAD

**Issue by hibamiru** [whooohq/whq-woocommerce-chilexpress-shipping#142]
(removido de otro issue por no pertenecer al tema)

Hola! Antes que todo agradecer por este trabajo. Es un buen aporte!

Tengo problemas con la selección de comunas y regiones en ambas partes del sitio (carro y check-out) donde las comunas que aparecen en RM no están todas y muchas me aparecen en ARICA, por ejemplo VITACURA está en ARICA y no en RM.

Tengo todo actualizado y todo el resto apagado. Desinstalé todo y volví a hacerlo con el mismo resultado. Probado en diferentes navegadores y tengo lo mismo.

Qué podría ser? Cómo saber si el problema es de Chilexpress?
Grx!

_Originally posted by @crokis in https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/140#issuecomment-485437919_

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
