### ISSUE TITLE
Problemas con los campos de region y ciudades

### ISSUE THREAD

**Issue by PabloArlegui** [whooohq/whq-woocommerce-chilexpress-shipping#143]
Hola a todos, estoy instalando el plugin pero al elegir la region y ciudad me muestra el listado correcto pero al hacer click no lo selecciona y por ende no calcula el precio, es problema de mi pagina o instale mal el plugin, adjunto una imagen para que vean como queda después de rellenar los campos. muchas gracias de ante mano.

https://drive.google.com/file/d/1NtrO9cyBIxFFRcs1HdIt2V6aDO1_ixzX/view?usp=sharing

**Comment by TCattd** [comment]
@PabloArlegui buen día.

Por favor, sigue los pasos en el FAQ:
https://wordpress.org/plugins/woo-chilexpress-shipping/#faq

Item "¿Problemas generales, visuales (glitches) y/o funcionales en el carro o finalizar compra (checkout)?".

Nos cuentas como te va, por favor.

**Comment by TCattd** [comment]
¿Cómo te fue con esto, estimado?

**Comment by PabloArlegui** [comment]
No mucho segui los pasos pero necesito que me funcione con un theme que estoy ocupando, incluso le puse el usuario de la api de chilexpress y nada. Sabes como puedo hacerlo?? Gracias igual

**Comment by TCattd** [comment]
Seguiste los pasos, y... ¿te funcionó con el theme "default" de WooCommerce?.

Si es así, el problema es tu theme. Debes revisar que le falta, qué no tiene, comparado con lo que WC espera de un theme en WP. Storefront es una buena guía en ese sentido.

No puedo ayudarte más, si ese es tu problema (el theme).

Si te pido, por favor, que si resuelves el inconveniente, vuelvas y nos cuentes qué hiciste. Eso podrá ayudar a muchos otros usuarios a futuro.
¡Gracias!

**Comment by JohanJRinconH** [comment]
Saludos, estoy presentando el mismo inconveniente del amigo arriba, selecciono la REGIÓN O PROVINCIA y la carga en LOCALIDAD / CIUDAD es errada, no corresponde a la REGIÓN, me podrías ayudar?

Versión de WooCommerce: 3.6.3

**Comment by TCattd** [comment]
@JohanJRinconH tu problema es otro, estimado. Leer por acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by JohanJRinconH** [comment]
Gracias por la pronta respuesta, le echare un ojo y te doy feedback!!!

**Comment by TCattd** [comment]
Reabrir si lo comentado acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/143#issuecomment-495781461 no funcionó, por favor.
