### ISSUE TITLE
Problema Carga de Regiones con tienda desde 0

### ISSUE THREAD

**Issue by oscarpw** [whooohq/whq-woocommerce-chilexpress-shipping#144]
Hola, 

Hemos instalado este plugin hace un tiempo atrás y funcionó correctamente hasta hace unas semanas en la que tengo problemas con la carga de comunas y regiones.  Al poner region metropolitana solo muestra 5 comunas y al poner por ejemplo  coquimbo, aparecen todas las comunas mezcladas con las de santiago.

He probado todo lo de FAQs y probé creando una tienda de prueba en un subdominio, instalando solo woocommerce y el plugin chilexpress, obteniendo el mismo resultado.

http://store.tiendainsular.cl/tienda/

podrian verificar si es un problema del plugin o si tengo alguna configuracion mal aplicada tanto en el plugin como en el server.

Saludos y muchas gracias por este aporte a la comunidad woocommerce en Chile!

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
