### ISSUE TITLE
El Plugin se queda Colgado

### ISSUE THREAD

**Issue by GuxWebs** [whooohq/whq-woocommerce-chilexpress-shipping#145]
al finalizar la compra se queda conlgado y no deja seleccionar la comuna incluso en la pagina demo que tienen para ver las funciones, lo instale y realice todas las configuraciones y no puedo pasar de finalizar compra 

http://prntscr.com/nsf8iv
esa es mi pagina

http://prntscr.com/nsf8vd
y esta es su pagina de demo que tampoco esta funcionando

**Comment by TCattd** [comment]
Estimado,

Acabo de entrar a ver al sitio de demo: http://wpchilexpress.whooohq.com/

Y funciona sin problemas: http://prntscr.com/nsk36l

¿Habrá sido un problema de conectividad temporal con los servidores de Chilexpress?

Me confirmas si puedes ver funcionando correctamente el plugin en http://wpchilexpress.whooohq.com/ por favor.

**Comment by GuxWebs** [comment]
Hola lo acabo de ver y ya funcio a voy a revisar en mi web muchas gracias

No me deja seleccionar la comuna

**Comment by TCattd** [comment]
No te deja seleccionar la comuna en tu web?
O en el demo?

Recuerda que primero se selecciona la región.
El selector de comuna es liberado una vez que uno selecciona la región primero.

**Comment by GuxWebs** [comment]
El tema es que en el modo integración me funciona pero al cambiarlo a modo
producción y colocar el usuario y contraseña me sale un mensaje que dice
sin conexión de igual forma pro are maña a de nuevo y revisaré los datos
del usuario.

Muchas gracias por responder cualquier cosa me comunico de nuevo.

Saludos

Miguel Sanz
Programador Web
Gux
Enviado desde Android

**Comment by PatrickCaneloDigital** [comment]
Buenos días...
Yo igual estoy teniendo problemas en mi plataforma de desarrollo con los selectores de region.
Se quedan pegados eternamente cargando.
![grafik](https://user-images.githubusercontent.com/21183922/58348003-5834e380-7e2d-11e9-87a2-d222b5e27bca.png)
Traté de borrar todos los transientes, desactivar el plugin de cache, etc.etc. pero sin ninguna mejora.

Si bien recuerdo el tema storefront ha tenido una actualización reciente. Puede tener que ver con eso?
La plataforma de referencia está 100% al día? 
porque efectivamente allí no se repdoruce el problema.

**Comment by TCattd** [comment]
En http://wpchilexpress.whooohq.com/ tengo todo actualizado, incluido el theme, y funciona sin problemas @PatrickCaneloDigital :/
Storefront en 2.5.0

¿Qué dice la consola de Chrome/Firefox?
¿Algún error?

**Comment by PatrickCaneloDigital** [comment]
No, lamentablemente cero errores, 
pero despues del request regions el plugin no dice más @TCattd 

[WCCHP] in checkout whq_wcchp_checkout.js:25:12
[WCCHP] Chile detected by initial value whq_wcchp_checkout.js:31:13
[WCCHP] whq_wcchp_checkout_chile_detected() whq_wcchp_checkout.js:272:11
[WCCHP] whq_wcchp_checkout_inputs_replace whq_wcchp_checkout.js:532:11
replacing city whq_wcchp_checkout.js:537:12
replacing region whq_wcchp_checkout.js:568:12
[WCCHP] requesting regions, action: whq_wcchp_regions_ajax

Descubri el problema si. Hace poco habia cambiado a php7.0 en esa instalación (no tengo solo el wordpress) y por alguna razon exraña, eso produjo el error. Cambié a php 5.6 y las regiones aparecieron de nuevo. 
Cambié de nuevo a Php7.0 y sigue funcionando, asi que NO me queda muy claro que es lo que produjo el error, pero la causa estaba por alli escondida... al menos funciona ;-)

**Comment by GuxWebs** [comment]
Hola estimado.

Me podrías orientar como hago para cambiar la opción de envío que me salga
en vez de 1 día hábil la de 3 días hábiles? O si es posible personalizar
eso para colo ar otra información allí co. O 4 días hábiles por ejemplo.

De antemano muchas gracias

Miguel Sanz
Programador Web
Gux
Enviado desde Android

**Comment by TCattd** [comment]
Esos tiempos los controla Chilexpress. No es algo que puedas cambiar.
La API responde con los tiempos estimados que Chilexpress puede entregar dependiendo de la ubicación de origen de tus envíos, y la ubicación de destino de quién compra.

Recordar lo que menciona el plugin en aquella configuración http://prntscr.com/o1dq2f

Esteban

**Comment by TCattd** [comment]
Si el problema persiste, reabres el issue, por favor.

**Comment by laucabello** [comment]
Hola, estoy teniendo el mismo problema, se queda colgado el selector de Localidad y Ciudad en el checkout. Probe desinstalando los plugins, el theme, borrando los transitorios, y aun asi no funciona. 
Alguien que haya podido solucionrlo me daria una mano por favor?
Gracias!
Saludos

**Comment by TCattd** [comment]
@laucabello por favor, sigue las instrucciones mencionadas acá: 
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/README.md#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Luego nos comentas.

**Comment by laucabello** [comment]
Hola! gracias por tu respuesta, hice todos los pasos
1. Actualice todos los plugins
2. Apague todos los plugins
3. Cambie a StoreFront
4. Borre transitorios
y sigue estando el loader en los selectores sin dejarme avanzar :(
Tengo el ambiente en QA ahora *y da el error, probe tb con pasarlo a Prod pero no encontre (y busque por todos) el ID y pass
El error sigue :(

<img width="483" alt="Captura de Pantalla 2019-10-31 a la(s) 16 51 17" src="https://user-images.githubusercontent.com/20303739/67981360-3838f580-fbff-11e9-9359-2020275058a2.png">

**Comment by PatrickCaneloDigital** [comment]
Solo para estar seguro:
Los dropdown están invertidos: Primero aparece Localidad/Comuna y después Región
Pero obviamente primero hay que seleccionar región.

No será que puedes elegir región, pero ver el loader y el orden inverso da la sensación que aún está cargando?

**Comment by TCattd** [comment]
Gracias @PatrickCaneloDigital ,

Como bien el dice, debes seleccionar primero región para poder luego seleccionar comuna.

@laucabello si deseas cambiar ese orden, revisa este issue por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?q=is%3Aissue+orden+region+is%3Aclosed
