### ISSUE TITLE
Comunas

### ISSUE THREAD

**Issue by mattusaleen** [whooohq/whq-woocommerce-chilexpress-shipping#146]
Estimados. 

Cargue el plugin, hice todos los pasos y probe todo desactivado para testear el error y sigue pasando. 

El error es que cuando selecciono santiago, me muestra solo 7 comunas (Alto jahuel, batuco, el paico, Lonquen, malloco, nos, chicureo) 

Ni idea por que no me aparecen el resto, cualquier ayuda para tratar de solucionarlo se agradece.

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
