### ISSUE TITLE
Tengo Problemas con la localidad !!

### ISSUE THREAD

**Issue by akeronek** [whooohq/whq-woocommerce-chilexpress-shipping#147]
Buenas, tengo problemas al instalar todo el plugin perfecto  pero al colocar región metropolitana no muestra las comunas  y aparece esto 

![Captura de Pantalla 2019-06-13 a la(s) 01 57 00](https://user-images.githubusercontent.com/39720653/59407270-bf83ea80-8d7e-11e9-9fc8-c7beae3cc509.png)

Necesito ayuda !!!

**Comment by TCattd** [comment]
https://www.youtube.com/watch?v=Uyq8-7tc5Eo

Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
