### ISSUE TITLE
Region Metropilitana no da las comunas correctas

### ISSUE THREAD

**Issue by miguelsanz72** [whooohq/whq-woocommerce-chilexpress-shipping#148]
Hola estimados, quiero reportar que al seleccionar la región metropolitana no obtiene todas las comunas, esto porque pasa? en que función ejecuta ese llamado como para revisarlo.

http://prntscr.com/o82evi

Estaré atento a sus comentarios.

Saludos

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
