### ISSUE TITLE
Pestaña "Chilexpress" no aparece en las opciones de envío del administrador

### ISSUE THREAD

**Issue by Casamoya** [whooohq/whq-woocommerce-chilexpress-shipping#150]
Hola! Seguí los pasos de instalación y activación del plugin de Chilexpress en Wordpress, pero al revisar en el menú de envío del plugin de Woocommerce no aparece nada relacionado con Chilexpress. Tampoco si dentro de las zonas de envío veo las alternativas. ¿Falta algo o es que el plugin funciona bajo alguna versión específca de Woordpress / Woocommerce? 

Estoy utilizando la versión 5.2.1 de Wordpress y la versión 3.6.5 de Woocommerce.

¡¡Gracias por responder!!

<img width="707" alt="image" src="https://user-images.githubusercontent.com/53530758/62223785-87168b00-b383-11e9-925b-c3131550b1d6.png">

**Comment by TCattd** [comment]
Mantenemos un demo funcional que se auto-actualiza siempre, acá:
http://wpchilexpress.whooohq.com
Última versión de WordPress, WooCommerce y el plugin de Chilexpress.

Veo el enlace a las opciones: https://prnt.sc/omjsjv
Si funciona ahí, anda sin problemas en la última versión de este trio.

Si no, hay un problema seguro con la instalación que tienes.

Consultas:
¿Es un WordPress normal, o multi sitio?

¿Qué pasa si vas a la URL de la config del plugin directo en tu sitio? Esa es: /wp-admin/admin.php?page=wc-settings&tab=shipping&section=chilexpress

¿Puedes desactivar todo plugin, excepto WooCommerce y el de Chilexpress, y ver si funciona?

**Comment by Casamoya** [comment]
Hola! y gracias por la pronta respuesta. 

Voy por partes. 
>¿Es un WordPress normal, o multi sitio?
Es un Wordpress normal. 

> ¿Qué pasa si vas a la URL de la config del plugin directo en tu sitio? Esa es: /wp-admin/admin.php?page=wc-settings&tab=shipping&section=chilexpress

Al revisar la ruta me aparece esto : 

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/53530758/62225444-70bdfe80-b386-11e9-8cf1-83bc9997cfce.png">

> ¿Puedes desactivar todo plugin, excepto WooCommerce y el de Chilexpress, y ver si funciona?

Desactivé todos los plugins, dejando activos únicamente el de Woocomerce y el de Chilexpress, pero sigue sin aparecer. 

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/53530758/62225570-b67ac700-b386-11e9-9cf6-bdd7aaab55d3.png">

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/53530758/62225596-c09cc580-b386-11e9-9a76-765ab9a790d7.png">

**Comment by AndresReyesTech** [comment]
Hola!

Puede ser la versión de PHP? o algún Módulo de PHP que no esté correctamente configurado? Ingresa a /wp-admin/admin.php?page=wc-status, presiona "Obtener el informe del sistema" y pégalo acá para ver si podemos sacar alguna conclusión.

Yo lo probé en una instalación idéntica a la tuya y funciona, sin embargo, quizás nuestros entornos sean distintos. Yo uso MAMP Pro. 

Veo que el domino es .mac, quiere decir que es local, si es así estás usando en OSX alguna versión MAMP, la versión PHP nativa que viene con el OS o usando Local by Flywheel ¿cual usas?

**Comment by TCattd** [comment]
@Casamoya ¿alguna novedad?

**Comment by TCattd** [comment]
Si hay novedades, reabrir, por favor.
