### ISSUE TITLE
Error Region es un Campo requerido aunque el campo contenga datos

### ISSUE THREAD

**Issue by juanitagonzalez** [whooohq/whq-woocommerce-chilexpress-shipping#151]
Hola, tengo el plugin instalado y se ve todo correctamente, al seleccionar la region, muestra bien las comunas, se ve el precio, pero al tratar de pagar, da error y me dice que la Region es un campo requerido. Desactivé todos los plugin, deje solo woocommerce con el tema storefront para probar, pero sigue tirando el mismo error. Que puede ser? :/

**Comment by TCattd** [comment]
@juanitagonzalez puedes dejar la URL de la tienda acá? para ver, por favor.
Si no, vía email a esteban arroba actitud.xyz

Gracias.

**Comment by TCattd** [comment]
Era un bug efectivamente.

Si fuerzan la tienda a enviar solo a la dirección de facturación ("Forzar el envío a la dirección de facturación del cliente") https://prnt.sc/on79yr ocurría esto. No era posible terminar la compra.

Esto, porque los campos ID #shipping_ no existen en ese caso. Solo los ID #billing_
Subida la versión 1.4.17, con el fix para este error.

Muchas gracias @juanitagonzalez por el aviso y la confianza con los accesos.

Esteban

**Comment by juanitagonzalez** [comment]
Muchas gracias a ti por darte el tiempo de revisar y ayudarnos a todos :D
