### ISSUE TITLE
Selector de regiones no muestra ciudades. 

### ISSUE THREAD

**Issue by mnexbu** [whooohq/whq-woocommerce-chilexpress-shipping#153]
Hola! antes que todo muchas gracias por el aporte y esfuerzo al desarrollar este excelente plugin. Ha sido una buena herramienta al momento de integrar despachos mediante chilexpress. Mi problema puntual es que tras haber instalado el plugin, al momento de ir a la página de finalizar compra, todas las regiones que muestra el menú desplegable dan la opción de "undefined". Al principio la región Metropolitana no mostraba todas las comunas pero ahora veo que es un problema de las demás regiones también. 

Cual podría ser el error?

Saludos! 

![regiones](https://user-images.githubusercontent.com/54912980/64286920-63b7a080-cf2c-11e9-870c-5e8ad3cc4021.png)

**Comment by TCattd** [comment]
Me parece que es esto https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by mnexbu** [comment]
TCattd Muchas gracias! tienes toda la razón y ahí mismo estaba la respuesta.

Saludos!
