### ISSUE TITLE
Al cambiar entre chile -> canada -> Chile se duplica el dropdown de las regiones

### ISSUE THREAD

**Issue by garretonfco** [whooohq/whq-woocommerce-chilexpress-shipping#154]
Hola, muchas gracias por plugin primero que todo!

Tengo un problema cuando hago switch de país, chile -> cualquier otro --> chile
Cuando vuelvo a seleccionar chile el combo de las regiones o estados se duplica.
Quedando el combo1 con las regiones de chile, y el combo2 con las regiones o estados del país que seleccione antes.
Traté de pillar donde estaba el problema, pero no logré encontrarlo.
Para replicarlo, pueden entrar  a https://universidaddemonichigan.cl/product/mejor-dilo-con-monos-i-buc/ agregarlo al carrito, y llegar al checkout.
![image](https://user-images.githubusercontent.com/55566528/65292910-a635cb80-db2f-11e9-92a3-49695ccc6ae2.png)

![image](https://user-images.githubusercontent.com/55566528/65292994-ef861b00-db2f-11e9-8b96-14aaa0dcd081.png)

Ojala puedan ayudarme, por favor.
Muchas gracias
Saludos

**Comment by TCattd** [comment]
Muchas gracias por el aviso.

Resuelto en v1.4.18

Actualización cargada en WordPress.org
La verán en minutos ;)

Esteban

**Comment by garretonfco** [comment]
Muchas gracias por solucionarlo! tan rápido.
