### ISSUE TITLE
No carga Todas las comunas

### ISSUE THREAD

**Issue by cgsaavedrac** [whooohq/whq-woocommerce-chilexpress-shipping#155]
Estimados.

Al seleccionar una región no carga todas las comunas de esa región a que se puede deber, lo primero que hice fue usar el theme de Woo que indican ustedes y nada

**Comment by TCattd** [comment]
Duplicado https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by cgsaavedrac** [comment]
![image](https://user-images.githubusercontent.com/34323242/66156633-6a533980-e5f8-11e9-84a5-aa141a307135.png)
Imagen de apoyo
