### ISSUE TITLE
No se muestran las comunas de santiago

### ISSUE THREAD

**Issue by garretonfco** [whooohq/whq-woocommerce-chilexpress-shipping#156]
Hola, como están?

Revisando encontré dos cosas, las pueden revisar porfavor

La primera es que al seleccionar la RM no se muestran todas las comunas, al menos en esta región lo he notado. ¿porque puede ser?
![image](https://user-images.githubusercontent.com/55566528/66162661-1a2ea400-e605-11e9-8337-e146f89ae341.png)
![image](https://user-images.githubusercontent.com/55566528/66163292-58789300-e606-11e9-802e-a90d1d980ea4.png)
![image](https://user-images.githubusercontent.com/55566528/66163403-a2fa0f80-e606-11e9-9870-32e3e145b1d1.png)
 
La segunda, es que chilexpress ya me envió el user y pass para PROD y los wsdl a los que hay q apuntar.
Los compare con los que ustedes usan y son distintos. ¿alguna idea?
Endpoint de producción Tarificación: https://services.wschilexpress.com/TarificarCourier?wsdl   
Endpoint de producción Georeferencia: https://services.wschilexpress.com/Georeferencia?wsdl  

Saludos
Gracias

**Comment by TCattd** [comment]
Estimado,

Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

En tu caso, puedes usar los datos de acceso que Chilexpress te entregó.

Esteban

**Comment by garretonfco** [comment]
gracias!
