### ISSUE TITLE
Problema listando localidades.

### ISSUE THREAD

**Issue by hmolina2018** [whooohq/whq-woocommerce-chilexpress-shipping#157]
Hola estimados, se ve genial el plugin pero he tendido problemas para implementarlo, me aparecen valores undefined y en envíos no aparece la elección del precio fijo y el resultante del servicio de chilexpress.

mi producto de prueba tiene dimensiones y peso con un valor de 100 pesos.

Aun esta vigente?
veo que su sitio de pruebas se ve impecable.

Estoy con woocommerce 3.7.0
WordPress 5.2.3
PHP 7.3.9
Tema flatsome

**Comment by TCattd** [comment]
Estimado,

Tu problema podría ser esto:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Nos comentas como te va, por favor.

Esteban

**Comment by hmolina2018** [comment]
Como se indica, el problema no se resuelve y cuando lo hace cambiando de QA A PROD nunca resuelve bien el precio.
me rindo con este plugin.

**Comment by TCattd** [comment]
@hmolina2018, puedes dejar la URL de tu sitio acá para revisar?
Configurado como PROD y con Las credenciales que corresponden cargadas en las opciones.

Si está bien, los precios que da el plugin deberían ser los mismos que da el demo que tenemos arriba.

Ojo, además debes tener configurados los tamaños y pesos de tus productos. Chilexpress no puede estimar un costo, si no se le dice cuánto pesa y mide un producto.

Esteban
