### ISSUE TITLE
Incopatibilidad con Starken

### ISSUE THREAD

**Issue by PabloSilvaBravo** [whooohq/whq-woocommerce-chilexpress-shipping#158]
Estimado, soy usuario de este plugin hace 2 años, y te agradezco mucho porque me ha funcionado perfecto y me ha facilitado muchas labores en mi tienda. Sucede que di con una tienda chilena creada en prestashop y me percaté de que ese CMS permitía el uso de un cotizador de precios y tiempos de envío con Chilexpress y Starken, por lo que mi pregunta es, ¿habrá algun proyecto tuyo o de algun tercero que esté trabajando en lograr una compatibilidad así para wordpress? De ser negativo lo anterior, ¿crees posible que pueda haber alguna compatibilidad entre tu plugin y el plugin cotizador de Starken para woocommerce algún día?, o que se haga un plugin que ya contenga los cotizadores de más compañias logisticas ([como este](https://addons.prestashop.com/es/transportistas/29467-couriers-chilexpress-starken-correos-chile-pack.html))?.
Saludos, espero su respuesta.

**Comment by TCattd** [comment]
Mio. No por el momento.
De terceros. No lo se.

La verdad, Pablo, el problema con Starken son dos cosas:
1.- API de acceso.
2.- Tiempo.

1.- Starken no tiene una API pública.
Las APIs que existen, incluida la del plugin "Despacho vía Starken para WooCommerce", son APIs privadas. Ya sea reversando la API que pueda usar Starken mismo en su web, o bien, creando una propia haciendo un scrapper de las respuestas del mismo sitio de Starken.
Si te fijas en el plugin mencionado por ejemplo, viendo el source, los datos de la API vienen de un servicio de tercero: https://tppr.me/YNpnk probablemente del mismo creador del plugin.

Ya es difícil mantener un sistema en base a una API de terceros. Y lo es mucho más en este caso, donde Chilexpress no es muy amigable (por ahora) con la ayuda técnica cuando hay problemas con su API, o los accesos a su API SOAP.
Hay que acomodarse a cualquier cambio que pudieran hacer, que hacen sin aviso, tratar de adivinar si algo está malo por el lado nuestro o es la API o sus servers los que responden mal, etc.

Imagínate tener que hacer una API solo para un servicio nuevo (Starken) y tener que mantenerla uno mismo. Y mantener un server arriba para que los usuarios del plugin puedan usar Starken en el plugin. Gratis como lo es el plugin de Chilexpress hoy.

No tengo la intención de crear una API para Starken, y tener que mantenerla y lidiar con problemas o cambios que hagan en sus sistemas, sin documentación, etc.

No, por el punto 2.

2.- Me falta tiempo. Eso es mi problema la verdad.
Con gusto mantengo el plugin actual de Chilexpress, gratis, para la comunidad. Es una devuelta de mano a WordPress y su comunidad. Vivo de esto. Por eso lo hago.
Pero no puedo invertir más tiempo en crear una API (reversando lo que hay en la web o haciendo y manteniendo un scrapper) para un servicio que no tiene una API propia pública o semi-privada.

Si esto cambia. Si Starken ofrece una API pública para integrarse a sus servicios, sin duda el problema en 1 cambiaría, y si habrían ganas de hacer un plugin nuevo para ese servicio, y hacer que ambos co-existan si es posible. De todas maneras.

Pero hasta que eso no cambie, no habrá un proyecto por mi parte por lo menos.

Lo siento.

Esteban
