### ISSUE TITLE
Problema en la carga de cuidades y suma de montos

### ISSUE THREAD

**Issue by felipechamorrocl** [whooohq/whq-woocommerce-chilexpress-shipping#159]
1.- En el Modo QA(De Pruebas) No cargan todos las ciudades de algunas y incluso en algunas regiones esta BUG salen varias cuidades a solo 1 Region. (En Prod esto no esta pasando) .
2.- Siendo QA / PROD Funcional o no (Cargando todas las ciudades o no), No me suma el precio a la boleta por decirlo de alguna manera.
3,- Por un Momento en el Modo de Produccion me cargo todo bien, y luego salio sin servicio, infiero que probablemente fue por las API KEY´s
Adjunto Fotos (Lamento Ponerlas de este modo)
![image](https://user-images.githubusercontent.com/56491243/66708408-43d68200-ed0d-11e9-861f-3882ff804a74.png)
(Como No suma )(PD: en BioBio en Modo QA solo sale HUEPIL).
![image](https://user-images.githubusercontent.com/56491243/66708403-38835680-ed0d-11e9-81de-4218b04aae9d.png)

Saludos y muchas gracias por este PLugin!

**Comment by TCattd** [comment]
1.- En QA el tema es así. Por eso es QA, es un ambiente de pruebas nada más.

2.- Será funcional cuando selecciones Producción y cargues el user y password correspondiente. Ver más detalles acá por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

3.- Ver 2.
