### ISSUE TITLE
Chilexpress no dispoble cuando cambio de país a chile

### ISSUE THREAD

**Issue by garretonfco** [whooohq/whq-woocommerce-chilexpress-shipping#160]
Hola, necesito de su ayuda nuevamente por favor.

 estoy haciendo más pruebas y me di cuenta de que cuando paso de Chile  -> otro país -> Chile en la página de checkout en el ultimo cambio a chile el precio es reemplazado por "No disponible" y si luego hago F5 carga el valor de envío.

Puedes probar cargando al carrito el siguiente producto https://universidaddemonichigan.cl/product/mejor-dilo-con-monos-the-buc/ y luego llegar al checkout

Revisé el JS y el que esta pintando el no disponible es:

`		whq_wcchp_chilexpress_down_noselect = setInterval(function() {
			if( jQuery('body').hasClass('wc-chilexpress-down') && jQuery('input[value^="chilexpress"]').length ) {
				jQuery('input[value^="chilexpress"]').prop('disabled', true).prop('selected', false).hide().next('label').children('.amount').text('No disponible 2');
				if( jQuery('input[value^="chilexpress"]').is(':checked') ) {
				jQuery('.shipping_method').not('input[value^="chilexpress"]:first').click();
				}
			}
		}, 250);`

![image](https://user-images.githubusercontent.com/55566528/66718284-9f117e80-edb8-11e9-8797-8c489fcfe21a.png)

![image](https://user-images.githubusercontent.com/55566528/66718302-d2eca400-edb8-11e9-9b13-f535d9e37662.png)

**Comment by TCattd** [comment]
@garretonfco por favor, necesito que sigas estas instrucciones:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Me comentas luego si con todo actualizado, y theme Storefront activado, el problema persiste.

Gracias.

**Comment by garretonfco** [comment]
Okas, gracias

**Comment by TCattd** [comment]
Reabrir si hay novedades, por favor.
