### ISSUE TITLE
Warning: A non-numeric value encountered in WC_WHQ_Chilexpress_Shipping.php

### ISSUE THREAD

**Issue by everquinones** [whooohq/whq-woocommerce-chilexpress-shipping#162]
Hola. Les escribo porque recién acabo de actualizar el plugin en mi web y ahora me esta arrojando el siguiente error: Warning: A non-numeric value encountered in /home/publyscl/stopazucar.cl/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 427

El mismo es bastante molesto porque descuadra algunas imágenes de la pagina, en la versión anterior este error no sucedía. Me gustaría saber que debo modificar para poder solucionar este pequeño error. 
Adicionalmente menciono que tengo los problemas típicos con el ambiente QA en donde solo me muestra alrededor de 5 comunas para los envíos, por lo que he leido debo cambiar al ambiente de producción para solucionar este error.

**Comment by TCattd** [comment]
Buenas,

No hubo cambios al respecto en la versión 1.4.19. No con la linea que te está molestando.

Asegúrate de tener tus productos con sus pesos y tamaños bien configurados, cada uno.
En la config de WooCommerce en KG y CM: https://tppr.me/9yFCW

Para tu otro problema: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Nos comentas, por favor.

**Comment by TCattd** [comment]
Reabrir si hay novedades, por favor.

**Comment by Mario-HM** [comment]
lo tengo configurado tal cual, pero el mensaje sigue apareciendo, lo que si, los productos de forma individual no los tengo configurados con esas medidas.
Sera por eso?

**Comment by TCattd** [comment]
@Mario-HM has respondido tu consulta tu mismo, estimado ;)

**Comment by Mario-HM** [comment]
y que valor puedo colocar si no tengo realmente las medidas?

**Comment by TCattd** [comment]
@Mario-HM realmente no te podemos ayudar ahí.

La API de Chilexpress espera las medidas (CM) y peso (KG) de los productos en el carro para poder cotizar con su sistema.
No hay alternativa en ese punto. Los productos las deben tener, todos, si quieres usar este plugin.

Esto es así con casi todos los plugins de curriers de envío. Ellos deben saber el tamaño y peso de lo que se está cotizando para poder enviar un valor de vuelta al carro de compras.

Esteban

**Comment by Mario-HM** [comment]
perfecto muchas gracias por tu ayuda
voy a realizar los cambios

saludos
