### ISSUE TITLE
Para mi aún no funciona

### ISSUE THREAD

**Issue by carlanga85** [whooohq/whq-woocommerce-chilexpress-shipping#163]
Aún no logro que el pluging en ambiente QA muestre todas las comunas de Santiago.
Cómo lo resolvieron?
Al setear el plugin en ambiente productivo (WS PROD), ¿dejaron usuario y contraseña en blanco o ingresaron datos? ¿estos datos se solicitan a Chilexpress?

Agradezco ayuda u orientación.

Muchas gracias a todos.

Hola y gracias, para mi también funciono lo mencionado por TCattd y KraptorChile !!

Resuelto con WS PROD , borrar cookies y transients.

Gracias nuevamente

_Originally posted by @Mlizana in https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128#issuecomment-454921739_

**Comment by TCattd** [comment]
Duplicado https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
