### ISSUE TITLE
No muestra calculo cuando hay mas de una opcion de Chilexpress

### ISSUE THREAD

**Issue by Fenomenoide21** [whooohq/whq-woocommerce-chilexpress-shipping#164]
Hola, tengo un problema con el plugin en que algunas veces no muestra el cálculo de envío.

Noté que para las comunas donde hay solo un tipo de envio , si muestra el cálculo (Envío vía Chilexpress (DIA HABIL SIGUIENTE):)
Para cuando hay más tipos de envío ya no me aparece el cálculo, pude verlo en el sitio que das para probar. http://wpchilexpress.whooohq.com/

Mi sitio es: https://cleanbot.cl/

Ejemplo exito:
METROPOLITANA DE SANTIAGO > CHICUREO
wpchilexpress.whooohq.com: da un resultado->  Chilexpress (DIA HABIL SIGUIENTE): $3.950
cleanbot.cl: da un resultado -> Envío vía Chilexpress (DIA HABIL SIGUIENTE): $4,100

Ejemplo falla:
METROPOLITANA DE SANTIAGO > NUNOA
wpchilexpress.whooohq.com: da dos resultados-> Chilexpress (OVERNIGHT): $5.925
Chilexpress (DIA HABIL SIGUIENTE): $3.950
cleanbot.cl: no da resultados

No se si es un tema de que simplemente no caben las dos opciones en la caja de texto de mi sitio. A veces sale este error:
Warning: in_array() expects parameter 2 to be array, string given in /home/cleanbot/public_html/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 749

De momento, gracias a que tu plugin da la opción a elegir el tipo de pedido tengo que solo sea la de "día hábil siguiente" y entonces me funciona para todas las comunas, pero pierdo las opciones.

Cuéntame si es algo que ya ha sido resuelto o cómo podría arreglarlo?

Saludos!
Feno

**Comment by TCattd** [comment]
Asegúrate de tener bien configurados los tipos de envío soportados: https://tppr.me/U7YUT
Eso es lo que hay en el sitio de demo.

Como ves, aparecen correctamente los dos tipos de envío soportados: https://tppr.me/Wx5b2
Si no es tu caso, debes seguir instrucciones: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout y descartar que no sea problema de tu theme o plugins instalados.

Sobre el bug que comentas, puede ser por un problema de configuración del mismo setting que menciono al inicio.
Agregué un check extra para evitar ese problema cuando no tienen bien configurado aquel apartado.

Va en la versión 1.4.20

**Comment by TCattd** [comment]
Version 1.4.20 arriba.

Gracias por el aviso @Fenomenoide21 ;)
