### ISSUE TITLE
Faltan comunas al momento de realizar una instalación nueva

### ISSUE THREAD

**Issue by sebahernandez** [whooohq/whq-woocommerce-chilexpress-shipping#165]
Hola, 
Instale el plugin y al momento de revisar y chequear el pago, veo que no contiene la misma cantidad de comunas que aparecen en el video.

Como puedo solucionar eso?..

Saludos

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Favor leer aquel otro issue. Gracias.
