### ISSUE TITLE
Alerta de disponibilidad Chilexpress cuando Chile no está seleccionado

### ISSUE THREAD

**Issue by kikinangulo** [whooohq/whq-woocommerce-chilexpress-shipping#166]
Hola, reitero las gracias por este tremendo plugin.

Ya que me indicaron que creara un nuevo issue, les comento:

Tenemos una tienda donde usamos su plugin y funciona perfecto para Chile, pero cuando cambiamos de país (la tienda vende en pesos y dólar) se activa Fedex como pasarela de despacho, hasta aquí Chilexpress no aparece como opción, aparece fedex, pero nos aparece una alerta indicando lo siguiente: "Chilexpress no se encuentra disponible en este momento. Por favor, selecciona otro método de envío (si existiese), o iténtalo nuevamente en unos minutos."

https://user-images.githubusercontent.com/1202104/70843961-1004ff00-1e19-11ea-94bc-89d7113d3de8.png

https://prntscr.com/qand6n

La pregunta es: es necesario ese mensaje considerando que el usuario indico que no es Chile, como podría ocultarse o desactivarse?

**Comment by TCattd** [comment]
Resuelto en 1.4.45
