### ISSUE TITLE
Desactivar para ciertos productos

### ISSUE THREAD

**Issue by ftodes** [whooohq/whq-woocommerce-chilexpress-shipping#167]
Hola a todos, como puedo hacer para que en ciertos productos no se muestre la opcion de envio por chilexpress?

**Comment by TCattd** [comment]
Hoy no existe alguna opción para hacer eso, estimado.

Eso no es algo que un método de envío de WooCommerce deba resolver en todo caso.

Acá alguien tiene tu mismo requerimiento, y comentan al respecto directo desde el soporte WooCommerce https://wordpress.org/support/topic/disable-shipping-method-for-certain-products-or-categories/ Phil da una alternativa allí.

Espero te sirva.

Esteban

**Comment by ftodes** [comment]
Entiendo, el problema es que por logística hay ciertos productos que pesan demasiado o son muy voluminosos para llevarlos a la oficina de Chilexpress, por lo que solo ofrecería recogida local.

**Comment by TCattd** [comment]
Se entiende. Se entiende.

Si vas a probar la solución que recomienda WordPress ahí, y te funciona, por favor ¿podrías volver a comentar acá mismo?

Si se puede no más, claro.
