### ISSUE TITLE
Problemas con select de ciudades

### ISSUE THREAD

**Issue by AloofWave** [whooohq/whq-woocommerce-chilexpress-shipping#168]
Estimados:

Tengo dos problemas con el plugin al intentar agregarlo a la tienda, el primero de ellos es que hay un problema con el select de las ciudades al momento de elegir una de ellas después de haber elegido la region, ya que a veces aparece undefined y otras aparecen menos de las que debiera o de hecho todas las ciudades incluidas las no pertenecientes a esa region. En las fotos se puede ver que lo he probado tal como se recomienda con el theme Storefront y con solo woocommerce activado.

![regions](https://user-images.githubusercontent.com/54603994/73226803-1e507580-4150-11ea-8f42-ffb5df3bfa88.png)
![Cities](https://user-images.githubusercontent.com/54603994/73226818-27d9dd80-4150-11ea-898c-a99c04fcb870.png)

El segundo problema me paso con otro theme, en el cual por alguna razon el select de regiones pierde sus dimensiones con chile, y ademas mantiene el problema antes mencionado.

![short](https://user-images.githubusercontent.com/54603994/73227158-54422980-4151-11ea-86e5-ee91ed90ba66.png)

gracias de antemano!

**Comment by TCattd** [comment]
Para tu primer problema: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Para tu segundo problema: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout
Luego de seguir esos pasos, por favor, nos comentas como te va. Gracias.

**Comment by TCattd** [comment]
Si tienes novedades, vuelves y abres el hilo, por favor. Gracias.
