### ISSUE TITLE
No aparece metodo de envio

### ISSUE THREAD

**Issue by nicolas-ortega** [whooohq/whq-woocommerce-chilexpress-shipping#169]
Hola estimados

Estoy instalando el plugin pero no me aparece el método de envío en el carrito en el proceso de compra, también cuando le doy desactivar y/o desinstalar este no desaparece y sigue ahí, limpie caché, cookies, todo y no se soluciona.

HELP ME, porfavor.

Saludos.

**Comment by TCattd** [comment]
Nicolás,

¿Podrías pasarme el acceso al wp-admin de tu sitio, por favor?
Por email lógicamente: esteban arroba attitude.cl

Gracias.

**Comment by TCattd** [comment]
Si tienes novedades, vuelves y abres el hilo, por favor. Gracias.
