### ISSUE TITLE
Problemas con actualización

### ISSUE THREAD

**Issue by arlensot** [whooohq/whq-woocommerce-chilexpress-shipping#17]
Antes de actualizar tenía un problema con las comunas.

Aún cuando escogía que el envío fuese a la misma dirección de facturación, me pedía que llenara los datos.
Los llenaba y seguía dando el error que debía escoger una comuna válida.

Desactivé el plugin mientras llegaba una actualización.

Recientemente actualicé a la última versión disponible. Y ha quedado fatal.

Se tarda demasiado en actualizar la Región y Comuna, y si en algún momento no pierdo la paciencia y espero más de 20 ó 30 minutos, aún cuando escojo la opción Retiro en Tienda. Me da error.

Ahora, pareciera tardar incluso más en cargar la Región y la Comuna. Por lo que espero que puedan solucionar esto para poder usar felizmente el plugin.

Saludos.

PD. El sitio es https://www.besportiva.com

**Comment by TCattd** [comment]
Estimada,

El retraso en la aparición de las Ciudades es normal, y es a propósito.
Esto: https://prntscr.com/fxa39a
Eso es así.
Una vez que uno selecciona una Región, entonces el plugin carga solo las Ciudades correspondientes a esa Región.
Lo que falta allí quizás es un aviso para que la gente seleccione su región primero, y no se quede esperando por un listado de ciudades que no vendrá hasta seleccionar la región correspondiente.

Lo vamos a ver.

Esos listados quedan cacheados en local (en la última versión), por al menos 24 horas (y hasta un mes si así lo desean).
Pero si por algún motivo la API de Chilexpress no responde (fuera de nuestro control), el plugin simplemente evitará que se use Chilexpress, volviendo a dejar los campos de Región y Ciudad tal como vienen por default en WooCommerce, y no permitiendo (en teoría) que se seleccione Chilexpress como método de envío.

---

Ahora, por algún motivo en vuestro sitio solo el campo de región es poblado con el listado proveniente de la API de Chilexpress (con un select2 habilitado correctamente), pero el campo de ciudad no carga el select2 con el listado proveniente desde la API.

Personalmente mantengo una instalación totalmente limpia de WordPress, WooCommerce (con el theme Storefront, el recomendado de WooCommerce) y el plugin este, para desarrollo... y el plugin aún funciona sin inconvenientes.

La verdad es que es difícil saber que puede estar ocurriendo en vuestro caso, sin mirar directamente el sitio (wp-admin y ftp). Si deseas podemos ver más en profundidad cual puede ser el problema, pero requeriría los accesos al wp-admin de vuestro sitio para descartar que no sea conflicto con algún otro plugin primero (cosa que ha pasado https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/4#issuecomment-313159614 ).

Si deseas enviarme los accesos para poder ver el problema, podemos conversar por correo: esteban arroba actitud.xyz

¡Saludos!
Esteban

**Comment by TCattd** [comment]
Para el primer problema, va una actualización en seguida.

Ver: http://prntscr.com/fxb687 ahí el aviso.

Y como comenté, una vez seleccionada una región http://prntscr.com/fxb6m3 es posible seleccionar dentro de sus localidades/ciudades asociadas http://prntscr.com/fxb6s9

Quedo atento a lo otro, @arlensot , por si nos dejas revisar en profundidad que puede estar pasando con vuestra instalación de WordPress/WooCommerce.

¡Gracisas!

**Comment by arlensot** [comment]
Hola Esteban,

Muchas gracias por la respuesta y por la actualización del plugin. Quedó perfecto.

Lo otro que hice, fue desactivar el plugin Comunas de Chile para WooCommerce, por si acaso.

Muchas gracias, 
Arlenny

**Comment by TCattd** [comment]
Muchas gracias por confirmar, estimada.
Que bueno que esté todo ok.

Creo que lo mejor es crear una notificación, dentro del wp-admin, una vez activado el plugin (el nuestro) y solo si detectamos que está activado también algún plugin que pueda generar conflictos, para que los usuarios sepan de ello (y decidan que hacer).

Lo voy a ver en otro Issue.

Buen día ;)
