### ISSUE TITLE
No aparecen opciones de Chilexpress en /Cart/

### ISSUE THREAD

**Issue by ric7979** [whooohq/whq-woocommerce-chilexpress-shipping#170]
Hola, primero agradecer a los creadores del plugin
Lo instale en woocommerce, active el plugin , agregue dimensiones en el producto pero al agregarlo al carro solo aparece Cnvío Chileexpress () y el total sin el envío. Faltara agregar algo dentro de la confuguración? alguna pista?

![capchilexpress](https://user-images.githubusercontent.com/60587746/73618231-fd32cd80-4604-11ea-9761-c055859ae6ea.jpg)

Gracias

**Comment by TCattd** [comment]
Revisa que no sea este tu problema primero, por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by TCattd** [comment]
Si tienes novedades, vuelves y abres el hilo, por favor. Gracias.
