### ISSUE TITLE
Envío vía Chilexpress (DIA HABIL SIGUIENTE): 

### ISSUE THREAD

**Issue by rogerpasu** [whooohq/whq-woocommerce-chilexpress-shipping#171]
Una consulta como podría cambiar la parte donde dice "DIA HABIL SIGUIENTE" a "día hábil siguiente", ya que consume mucho espacio en la caja de seleccionar tipo y coste de envíos, necesito que esto sea en minúsculas y en un tipo de fuente más pequeño.

Por lo demás esta todo muy bien.

**Comment by TCattd** [comment]
@rogerpasu debes crear snippet de código en el functions.php en tu theme (o sirve un plugin solo para esto igual), para usar el filtro que el plugin provee:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/classes/WC_WHQ_Chilexpress_Shipping.php#L260

https://developer.wordpress.org/reference/functions/add_filter/

Con eso puedes alterar el array $shipments_types antes que sea devuelto al mismo plugin.
Ahí cambias los nombres de cada uno de ellos, si lo deseas.

Esteban
