### ISSUE TITLE
No se despliegan las ciudades en datos de facturación 

### ISSUE THREAD

**Issue by danielirow** [whooohq/whq-woocommerce-chilexpress-shipping#172]
Hola, Después de dar clic en "finalizar compra" en los datos de facturación solo me muestra algunas "Localidades / Ciudades"  después de seleccionar la región. Sabes a que puede deberse ?

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
