### ISSUE TITLE
Logo chilexpress en el checkout

### ISSUE THREAD

**Issue by jpromeroo** [whooohq/whq-woocommerce-chilexpress-shipping#173]
Hola Amigos!

Uso hace tiempo este plugin y funciona impecable! Trate de instalar el oficial de chilexpress pero preferi quedarme con este. Alguien sabe como agregar el logo de chilexpress al checkout como adjunto en la imagen? Cualquier ayuda se agradece.

Saludos y gracias!

 [<a href="https://imgbb.com/"><img src="https://i.ibb.co/JFH93mF/chilexpress-envio.jpg" alt="chilexpress-envio" border="0"></a>](url)

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
