### ISSUE TITLE
Chilexpress woo - app con error 

### ISSUE THREAD

**Issue by karlosjv** [whooohq/whq-woocommerce-chilexpress-shipping#174]
Hola, buenas tengo un error con el Plugins de chilexpress, al seleccionar la Region, esta no me despliega las ciudades correspondientes, mes las coloca como UNDEFINED, favor su ayuda.

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
