### ISSUE TITLE
Problema con las Ciudades

### ISSUE THREAD

**Issue by Roflxd-wq** [whooohq/whq-woocommerce-chilexpress-shipping#175]
Hola!,

Me está arrojando problemas el plugin al momento de buscar ciudades durante la Facturación del producto. Después de realizar la selección de región solo aparecen algunas ciudades o estás mismas se encuentran intercambiadas en otras regiones.

Saludos

![Problema con las ciudades](https://user-images.githubusercontent.com/64221913/80133421-324b1e00-856b-11ea-834f-757439b2489e.png)

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
