### ISSUE TITLE
No logro hacerlo funcionar

### ISSUE THREAD

**Issue by miketarazona** [whooohq/whq-woocommerce-chilexpress-shipping#176]
Hola, Instalé el plugin hoy en la pagina de un cliente (www.minimoon.cl) y no logro hacer que funcione bien. 

Al principio nisiquiera funcionaba así que desinstalé todos los plugins que podían estar causando problema como el WooCommerce Checkout Field Editor y Comunas de Chile.

Luego la lista desplegable de Comunas no me estaba arrojando las comunas correctas asi que cambie a modo WS PROD con la contraseña que encontré en Google, instalé el Transients Manager y borré todos los transients que me ustedes me indicaron y finalmente la lista de Comunas se arregló pero con todo y eso la mayoria de las Comunas no me estan arrojando ningún metodo de envio. Me dice: No hay opciones de Metodos de Envio Disponibles.

<img width="1280" alt="Captura de pantalla 2020-04-28 a la(s) 16 41 03" src="https://user-images.githubusercontent.com/64495801/80531706-095eca80-8969-11ea-896d-3dae4e1dc14b.png">

¿Que puede estar sucediendo? ¿Será un problema interno de Chileexpress? Ayuda por favor.

**Comment by TCattd** [comment]
¿Los productos en tu tienda tienen peso (kg) y tamaño (cm) asignados?

**Comment by miketarazona** [comment]
Hola amigo, gracias por responder. No todos los productos de la tienda tienen peso y tamaño asignados pero ese producto en particular si, por eso lo utilicé como prueba. Este es el producto: https://minimoon.cl/producto/destacador-tradicional-set-de-5-colores/

**Comment by TCattd** [comment]
¿Throttle?

La API de Chilexpress bloquea la IP de un server cuando detecta un "flood" de solicitudes. Este throttle que aplican, ya ha sido conversado antes: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?q=is%3Aissue+throttle+is%3Aclosed

Probablemente pegaste en eso por la cantidad de pruebas que hiciste, y terminaron bloqueando la IP de tu server automática y temporalmente.

No veo que tengas andando el plugin hoy (me metí a ver recién) así es que no puedo probar.

Esteban

**Comment by daeselixir** [comment]
Hola estimado,me podrias ayudar indicando que plugins terminaste utilizando para el calculo de los envios?

sldos

**Comment by TCattd** [comment]
Nos comentas cualquier novedad, por favor.
