### ISSUE TITLE
se queda pegado

### ISSUE THREAD

**Issue by jabeer12** [whooohq/whq-woocommerce-chilexpress-shipping#177]
acabo de pasar de la version php 7.0 a 7.3 para que me aceptara el plugin, pero al hacer la prueba se queda pegado. ¿Alguna idea de por que será esto? 

<img width="720" alt="Captura de Pantalla 2020-04-30 a la(s) 18 38 50" src="https://user-images.githubusercontent.com/64616948/80765885-1d91fb80-8b12-11ea-89ca-9037100d87b3.png">

**Comment by TCattd** [comment]
¿Probaste seleccionando la región primero?

**Comment by TCattd** [comment]
Nos comentas cualquier novedad, por favor.
