### ISSUE TITLE
No muestra todas las comunas

### ISSUE THREAD

**Issue by lubarzam** [whooohq/whq-woocommerce-chilexpress-shipping#178]
Al seleccionar algunas regiones, por ejemplo Araucanía, no me muestra todas las comunas. Y también aparecen primero la comuna y luego la región, me gustaría que fuera al revés.

**Comment by TCattd** [comment]
Duplicados de:

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/19#issuecomment-317432138
