### ISSUE TITLE
Chilexpress "sin servicio" hasta completar dirección

### ISSUE THREAD

**Issue by jpromeroo** [whooohq/whq-woocommerce-chilexpress-shipping#179]
Hola Que tal!

Me aparece en la pagina de pago ( Chilexpress SIN SERVICIO )

Pero al ingresar los datos de direccion , region y ciudad se activa y realiza el calculo de envio.

Hay alguna forma de que no aparezca SIN SERVICIO? ya que se me han caido algunas ventas ya que el cliente tiende a pensar que no hay envio disponible.

Muchas gracias!

Saludos!

![Captura](https://user-images.githubusercontent.com/33239572/81341658-e8405d00-907f-11ea-9705-58a7b65b8a3e.JPG)

**Comment by TCattd** [comment]
Explicación al respecto https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#chilexpress-ca%C3%ADdo-chilexpress-no-disponible

Ahora, como sugerencia, es bienvenida.
Creo que podríamos hacer algo para no mostrar el "sin servicio" si no se tiene completado antes los campos de dirección (que es requerido por WC para calcular envío).

**Comment by alsterxz** [comment]
Hola,

Primero que todo, gracias por el plugin, increíble trabajo. Quisiera apoyar la sugerencia jpromeroo, ya que me ha pasado la misma situación, con algunos clientes que señalan que "no funciona la opción de envío". Ojalá que este mensaje de (SIN SERVICIO) pueda no mostrarse si es que el cliente no ha ingresado toda su información, podrían reemplazar el mensaje con 
"(COMPLETE TODAS LAS CASILLAS)" o algo similar. Solo es una sugerencia.

**Comment by TCattd** [comment]
Resuelto en 1.4.45
