### ISSUE TITLE
No aparece select (región/comuna), en el Carrito, si hay un solo método de envío configurado

### ISSUE THREAD

**Issue by alvrsmp** [whooohq/whq-woocommerce-chilexpress-shipping#180]
¡Hola! Qué tal.

Primero que nada muchas gracias por el plugin y por el support, te pasaste.

Te cuento que estoy tratando de lanzar mi página web pero quiero hacerlo con el sistema de envío y de pago funcionando. Tengo todo listo a excepción de esas dos cosas.

Cuando instalé el plugin de Chilexpress tuve el error del issue #128, seguí los pasos que comentas ahí y ahora muestra bien y en su totalidad tanto las regiones como las comunas en la página del checkout. También funciona el cálculo de envío en el checkout. Lo que no he podido solucionar es que me aparezcan los select desplegables de región y comuna en la sección Calcular envío de la página del carrito. Me aparecen los campos para completarlos pero no se despliegan:

https://user-images.githubusercontent.com/64936617/81353611-81c73900-9097-11ea-88d1-756b056ce7f7.png

Los productos que agrego al carrito tienen su peso y sus medidas correctamente añadidos.

Por cierto, hice lo que mencionas en "¿Problemas generales, visuales (glitches) y/o funcionales en el carro o finalizar compra (checkout)?" y el error se mantuvo en el theme Storefront:

https://user-images.githubusercontent.com/64936617/81353488-34e36280-9097-11ea-8662-fba5480fac73.png

Te comento además que tengo instalado el plugin Checkout Field Editor for WooCommerce pero no eliminé nada, sólo cambié el nombre de algunos campos y un par los reorganicé, así que no debería ser la causa del error según lo que aparece en el issue #18 (en todo caso igual lo desactivé para asegurarme y el problema seguía).

Me he leído casi todos los issues sobre el plugin de Chilexpress acá en GitHub y ya no sé qué intentar.

¿Alguna idea de lo que puede ser?

Quedo atento.

Saludos

**Comment by TCattd** [comment]
Estimado,

¿Me puedes dar acceso admin a tu wp-admin?.

Si es así: esteban (arroba) attitude.cl

Gracias.

**Comment by TCattd** [comment]
Es un bug.

Cuando no hay otro envío aparte de Chilexpress, ocurre eso en el carro de compras.
Si agregas, por ejemplo, el "retiro en local", entonces el bug desaparece.

¡Gracias por el acceso!

Lo veré apenas pueda.

Esteban

**Comment by alvrsmp** [comment]
Esteban:

Reitero mi agradecimiento por tu tiempo y tu asistencia.
Quedo atento entonces ante cualquier avance.

¡Saludos!

**Comment by psegovias** [comment]
Alguna forma de evitar el BUG cuando se tiene solo a Chilexpress como envío?

**Comment by TCattd** [comment]
@psegovias no. No hasta que sea resuelto.

**Comment by TCattd** [comment]
Resulto en 1.4.23
