### ISSUE TITLE
Ayuda seleccionar la dirección de envío por defecto

### ISSUE THREAD

**Issue by francisco-sanchez-p** [whooohq/whq-woocommerce-chilexpress-shipping#181]
Hola, espero estés muy bien.

He instalado el plugin para woocommerce de Chilexpress y logré hacerlo funcionar, solo me queda el siguiente problemilla. Para que me muestre el combo box de regiones y comunas debo dejar por defecto que el cliente seleccione una opción de envío diferente a la dirección de facturación, porque si la cambio deja de mostrarme los combo box y, por ende, no hace el cálculo del envío. 
Como queda seleccionada por defecto enviar el producto a otra dirección hasta que no desmarco esa opción el checkbox de Chilexpress aparece como sin servicio.
Dejo imágenes que podrían ayudar a explicar más el problema.

![image](https://user-images.githubusercontent.com/65628946/82494893-488bc180-9ab8-11ea-923f-6f00b9b2398e.png)
![image](https://user-images.githubusercontent.com/65628946/82494959-60fbdc00-9ab8-11ea-8506-624db874241e.png)

Cuando desmarco la opción que queda activa por defecto de enviar a una dirección diferente funciona bien el envío por Chilexpress
![image](https://user-images.githubusercontent.com/65628946/82495057-8be63000-9ab8-11ea-949d-89b8d3893bd2.png)

Esta es la configuración de Woocommerce que me permite ver los combo box de regiones y comunas, si la cambio a dirección de facturación, que es lo óptimo se van los combobox de regiones y comunas.

![image](https://user-images.githubusercontent.com/65628946/82495314-ea131300-9ab8-11ea-8a7d-c115d9132656.png)

Quedo atento a sus comentarios.

Muchas gracias!

**Comment by TCattd** [comment]
Por favor, seguir pasos descritos en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Luego reportar de vuelta.

Gracias.

**Comment by francisco-sanchez-p** [comment]
FInalmente era un problema de la versión de woocommerce, tuve que hacer un rollback. Pero el plugin que me pasaron desde Chilexpress no me da la opción de hacer envíos al día hábil subsiguiente. 

Cómo puedo agregar esas opciones?

**Comment by TCattd** [comment]
@francisco-sanchez-p si lo que tienes es un problema con el plugin oficial de Chilexpress, entonces debes contactar a Chilexpress mismo para solicitar ayuda.

Nosotros no tenemos que ver en lo absoluto con Chilexpress.

Lo siento.
