### ISSUE TITLE
Solo puedo hacer envíos día hábil siguiente

### ISSUE THREAD

**Issue by francisco-sanchez-p** [whooohq/whq-woocommerce-chilexpress-shipping#182]
Hola! espero estén muy bien.

Necesito ayuda con una cosilla, el plugin que descargué desde developers.chilexpress no me permite hacer envíos al día hábil subsiguiente o posterior, solo por defecto trae el día hábil siguiente. Ingresé a Ajustes de Woocommerce, envíos, Chilexpress pero solo me permite activar este envío y cambiar el texto que aparece. Y desde la barra lateral de Wordpress, en el apartado Chilexpress solo puedo poner las APIs y en configuración general las direcciones de envío y devoluciones.

Dónde puedo seleccionar estas opciones de envío más económicas?

Muchas gracias

**Comment by TCattd** [comment]
@francisco-sanchez-p si lo que tienes es un problema con el plugin oficial de Chilexpress, entonces debes contactar a Chilexpress mismo para solicitar ayuda.

Nosotros no tenemos que ver en lo absoluto con Chilexpress.

Lo siento.
