### ISSUE TITLE
Regiones con tildes o acentos no funcionen

### ISSUE THREAD

**Issue by omjeremy** [whooohq/whq-woocommerce-chilexpress-shipping#183]
Al intentar pagar con facturación en regiones con tildes o acentos arroja el siguiente error:

Facturación Región no es válido. Por favor introduce uno de los siguientes: Antofagasta, Araucanía, Arica y Parinacota, Atacama, Aysén del General Carlos Ibáñez del Campo, Biobío, Coquimbo, Libertador General Bernardo O’Higgins, Los Lagos, Los Ríos, Magallanes y la Antártica Chilena, Maule, Metropolitana de Santiago, Ñuble, Tarapacá, Valparaíso

Tal vez el caché de ubicaciones tiene que ser actualizado pero no veo una manera de forzar actualizar las ubicaciones.

**Comment by TCattd** [comment]
Sin problemas acá:

https://tppr.me/j7kTb

https://tppr.me/jj5u5

https://tppr.me/HSyaj

Puedes probar en vivo en https://wpchilexpress.whooohq.com/

Por favor, seguir instrucciones en https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout para debugear tu problema.

Si no puedes replicar el problema con solo con WooCommerce, nuestro plugin de Chilexpress, Webpay activo (en el caso que lo uses) y el theme Storefront, entonces el problema está en vuestra instalación de WooCommerce, theme o algún otro plugin instalado.

Nos cuentas como te va, por favor.
Esteban

**Comment by TCattd** [comment]
Gracias por volver y confirmar cual era tu problema, @omjeremy 

Buen día ;)
