### ISSUE TITLE
Generación de Número de Seguimiento

### ISSUE THREAD

**Issue by joaqozen** [whooohq/whq-woocommerce-chilexpress-shipping#184]
¡Hola! He usado el plugin y es un muy buen trabajo. 

Tengo una duda para mejorar la experiencia del usuario. 

¿Alguien sabe cómo, si es que es posible, generar un código de seguimiento? Esto es para que las personas, una vez se entregue el pedido a ChileExpress, sepan dónde va su pedido. 

Sé que el plugin no lo genera, pero ¿hay alguna forma de complementar (con otro plugin¿?)? 

De antemano, muchísimas gracias. 

Joaquín.

**Comment by TCattd** [comment]
Aquí tienes dos caminos.

El plugin oficial de Chilexpress (debes ser cliente de ellos para poder acceder a el), o usar la extensión de @PatrickCaneloDigital https://www.canelodigital.cl/woocommerce-chilexpress-plugins/#chilexpressEtiquetas que funciona con nuestro plugin.

Esteban
