### ISSUE TITLE
No aparecen todas las ciudades 

### ISSUE THREAD

**Issue by kevingayoso** [whooohq/whq-woocommerce-chilexpress-shipping#185]
Buen día estimados,

Primero que todo muchas gracias por el plugin, es primera vez que lo uso y estoy teniendo un problema con las ciudades, resulta que en la región del Bio Bio no aparecen más ciudades que Huepil.

Adjunto imagen 

![Captura de Pantalla 2020-07-05 a la(s) 00 00 46](https://user-images.githubusercontent.com/67850439/86525237-997e2c00-be52-11ea-8d7a-a49768e9c194.png) 

Lo mismo con la región del Maule 

![Captura de Pantalla 2020-07-05 a la(s) 00 01 28](https://user-images.githubusercontent.com/67850439/86525242-b31f7380-be52-11ea-9359-1b08e433dcc1.png)

Me gustaría saber si pueden ayudarme u orientarme para solucionar mi problema.

De antemano, muchas gracias.

Saludos y felicitaciones por su gran trabajo.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
