### ISSUE TITLE
No estan todas las comunas de Chile

### ISSUE THREAD

**Issue by Jackblack210** [whooohq/whq-woocommerce-chilexpress-shipping#186]
Hola buenas tardes,

Antes que nada, felicitarlos por el plugin, sin embargo al instalarlo en la ultima version de WC cuando seleccionas la comuna que deseas enviar no aparecen todas las de la region, sera por que es la ultima version de WC? tengo el SOAP activado pero nada...

Slds.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
