### ISSUE TITLE
Campo Regiones y Ciudades con error

### ISSUE THREAD

**Issue by undermix** [whooohq/whq-woocommerce-chilexpress-shipping#187]
Tengo un problema de localización, por ejemplo selecciono Valparaíso y no aparecen algunas ciudades, pero si selecciono Tarapacá aparecen muchas e incluso las que no aparecen en Valparaíso, espero puedan ayudarme. (esta en ambiente WS QA) Soap activado.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
