### ISSUE TITLE
Problema con Localidad/Ciudad

### ISSUE THREAD

**Issue by pinwil** [whooohq/whq-woocommerce-chilexpress-shipping#188]
Hola muchas gracias por este plugin, tengo un problema cuando se selecciona algunas, localidades/ciudad muestra UNDEFINED no en todas pero la mayoria muestra este mensaje. Alguna forma de solucionar?

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
