### ISSUE TITLE
lista de ciudades por región erróneas o incompletas

### ISSUE THREAD

**Issue by joelaraya** [whooohq/whq-woocommerce-chilexpress-shipping#189]
Hola! Muchas gracias por tremendo trabajo. Hace poco me estoy metiendo en esto de configurar mi página web y cosas por el estilo y tenía casi todo hecho, pero siempre tuve problemas para mostrar las ciudades en regiones, hasta que me di cuenta que el único plug-in que causaba el error es el de Chilexpress. Ahora... para mi es súper importante mantenerlo, por lo que necesito resolver esta falla tan rara... por ejemplo, en la región de antofagasta, sólo me muestra "rodomiro tomic codelco" y no me muestra nignuna ciudad de la región... si pongo región de tarapacá, me despliega el listado de todas las ciudades de Chile. 

Help!!! :(

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
