### ISSUE TITLE
Orden de campos Región/Comuna

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#19]
Estimados,

Este issue quedó en el limbo y creo que es importante.

Se ve demasiado confuso a nivel de UI que aparezca primero el campo que se llena con el segundo. Lo ideal sería que se mostrara primero la región, o si me preguntan que sólo haya que seleccionar la comuna y que la región se poble sola.

Le pedi a un conocido que cacha más que lo mire y no fue capaz de cambiar el orden, es algo muy complejo de implementar?.

Con eso y el calculo de dimensiones el plugin quedaría perfect.

saludos

**Comment by TCattd** [comment]
No en el limbo, peor lo deseché porque ya tuvimos un problema con eso.
Es un cambio que la gente en Chile suele hacer, y nosotros no ayudamos al respecto metiendo ese cambio forzado.
Existen soluciones para eso (orden de los campos) fuera de nuestro plugin.

Ver: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18

Por eso removí el filtro que cambiaba el orden de Región y Cuidad.
El commit lo puedes ver acá: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/commit/c2a1cad456b031116e23b45a310f879618076137 en el archivo includes/woocommerce.php está el filtro que buscas.

La verdad, no se si esto sea parte de lo que este plugin debiera resolver.

De hecho, puedes instalar el mismo plugin con el que tuvimos conflictos https://wordpress.org/plugins/woo-checkout-field-editor-pro/ y reordenar tu mismo los campos al orden que desees.

Pero, ¿Qué pasa si alguna tienda no solo vende en Chile?. Chilexpress funciona en Chile, y no fuera. ¿Qué pasa si a algún dueño de una tienda le molesta que, solo porque Chile usa el sistema Región primero Ciudad después, todos los otros paises deban funcionar de la misma forma ahora por usar este plugin?.

El punto al final es esto:

El plugin nuestro es para agregar a Chilexpress como método de envío, y nada más.
Mientras menos nos metamos con WooCommerce (como viene por default), me parece que es mejor.

Lo que te molesta es algo que puedes resolver con un filtro simple (WooCommerce usa [Tinysort](http://tinysort.sjeiti.com/) en el fondo para ordenar esos bloques en el DOM) o con el uso de un plugin que está hecho específicamente para eso ([uno gratuito](https://wordpress.org/plugins/woo-checkout-field-editor-pro/), y [otro de pago](https://woocommerce.com/products/woocommerce-checkout-field-editor/)).

**Comment by llermaly** [comment]
Tienes toda la razón, no es muy buena idea reemplazar ese tipo de comportamientos. 

Instalé el plugin gratuito y pude hacer el cambio, se agradece enormemente la explicación.

Atte.

**Comment by TCattd** [comment]
No hay problema, estimado ;)

**Comment by waflessnet** [comment]
sigue sin funcionar, modifico tal cual, se indica, adicional mente probé modificando  otros campos para verificar el orden, y estos cambios si ocurren pero no en el caso de city  y state. 
Quiero subir regio y dejar comuna abajo de este.

![image](https://user-images.githubusercontent.com/6413704/82169731-6a0a6480-9890-11ea-941d-3c5dc03f8937.png)


![image](https://user-images.githubusercontent.com/6413704/82169799-9e7e2080-9890-11ea-9fb6-d0a731ee3898.png)
