### ISSUE TITLE
No encuentro forma de seleccionar envío gratuito en la comuna de origen.

### ISSUE THREAD

**Issue by jnahuelfil** [whooohq/whq-woocommerce-chilexpress-shipping#191]
Hola, de antemano me gustaría dar las gracias por tan buen plugin y me gustaría saber si lo que me ocurre es un error de configuración o de pleno estoy haciendo algo mal yo.

Resulta que mis envíos salen de Temuco (al seleccionar la comuna de envío no encuentro ningún inconveniente)

Pero al seleccionar la Región de la Araucanía, me refleja solo dos comunas (Mininco y Quepe). 
Probé seleccionando otra comuna de origen y el problema persiste.

Me gustaría dejar a temuco con despacho gratis pero no logro siquiera que figure la comuna y por ende la ciudad.

Muchísimas gracias por leer este mensaje.

**Comment by TCattd** [comment]
Comunas faltantes: duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Sobre la otra consulta, eso es algo que debes ver con WooCommerce mismo. Esto es envío Chilexpress, ninguno de sus envíos es gratuito.
La opción de configurar envíos gratuitos para ciertas localidades-zonas es algo que WC ya maneja por si solo.

Esteban
