### ISSUE TITLE
No aparecen todas las comuna de RM

### ISSUE THREAD

**Issue by avagp** [whooohq/whq-woocommerce-chilexpress-shipping#192]
Hola!

Vengo ocupando el plugin hace má de 1 año sin problemas.

Lo instalé en un nuevo sitio y funciona, pero tiene un problema, las comunas de la RM no aparecen todas, solo 10.

No sé si tiene que ver con el caché o algo, pero he desactivado todos los plugins y aún sucede.

El plugín sí indica el precio, me indica todas las regiones, pero sucede eso en particular.

Puedes revisar mi sitio https://pasalochancho.cl si quieres ver el problema tu mismo.

Espero me puedas ayudar con esto.

Saludos!
Y agracias de antemano!

**Comment by avagp** [comment]
Acabo de pillar que las comunas de RM están en la región de ARICA y PARINACOTA.

**Comment by avagp** [comment]
Desabilité todo menos woocommerce y el plugin. 

Cambie a Storefront como tema de mi sitio.

Saqué todo el css personalizado, y aún me arroja el error

:(

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by avagp** [comment]
lo borré y lo volví a instalar y parece que está todo bien
