### ISSUE TITLE
Plugins de Correos de Chile y Chilexpress colisionan

### ISSUE THREAD

**Issue by Sebastiangperez** [whooohq/whq-woocommerce-chilexpress-shipping#193]
Hola , les hago una pregunta , instale su plugin y después también instale el plugin de correoschile , pero tira un error en el cual dice que la función ya esta declarada :
Fatal error: Cannot redeclare whq_wcchp_rpship_calc_options()  ... 
Sabran cual puede ser la solución? 
Gracias.

**Comment by TCattd** [comment]
Hmmmm...

Tuve la oportunidad de integrar una instalación de WC con el plugin nuevo de Correos de Chile.

Me llamó la atención (mirando el plugin a la rápida), que su forma de inicializar el plugin https://tppr.me/YPEMD es muy muy similar a la que creamos nosotros hace años https://tppr.me/dbOz3

¿Coincidencia?. ¿Copia?. Aún si es una copia, la verdad, da lo mismo. Es código GPL v2, y aunque deberían dar crédito a los snippets que copian (por la licencia), bueno... es un alago que como plugin nos tengan en la mira para otros desarrollos.

Pero, no estaba seguro que hubiesen literalmente copiado el plugin como base para el suyo.

Con lo que me dices, @Sebastiangperez , me queda claro que usaron nuestro plugin de Chilexpress (como base) para hacer el suyo.

**No puedo resolver el problema del plugin de Correos de Chile.
¿Alguien tiene contacto con alguien que vea esto dentro de Correos de Chile y/o la empresa que les hizo el plugin?.**

Como para avisarles y pedirles que, por favor, cambien los prefijos de las funciones en su plugin a algo "de ellos" (por eso el whq_ en el nuestro, de WhoooHQ).

**Dejo abierto para ver que ocurre (con el contacto con Correos de Chile), aunque no es un bug nuestro directamente.**

Por ahora, podrías cambiar el nombre de esa función directo el plugin de Correos de Chile @Sebastiangperez.
Esa función, en el plugin de Correos, la encuentras en cch_shipping/cch_shipping.php
Debes cambiarla en estas dos instancias: https://tppr.me/y5M6w
Como el plugin de ellos no está en el repositorio oficial de wordpress.org y no cuenta con otro mecanismo de auto-actualización, el cambio que hagan sobre-vivirá hasta que actualicen ustedes mismos ese plugin a mano.

Esteban

**Comment by Sebastiangperez** [comment]
Altos ladrones resultaron, pero bueno, eso pasa con el código libre. 
Si, iba a renombrar las funciones, con respecto a la actualización, veremos si cambian algo mas adelante. 
Gracias por tu pronta respuesta.

**Comment by TCattd** [comment]
Estimados,

Tuve una excelente conversación con Correos de Chile, hoy.
No puedo darles todos los detalles, pero puedo compartirles que están trabajando en resolver este inconveniente (del que no fueron directamente responsables) y, de paso, vamos a trabajar en tratar de resolver ciertos problemas de compatibilidad entre su plugin y el nuestro acá.

Super bien.

Voy a cerrar el issue por ahora. No tiene sentido mantener esto abierto.
