### ISSUE TITLE
No hay despliegue de las aplicaciones y acceso a API

### ISSUE THREAD

**Issue by dhvasquez** [whooohq/whq-woocommerce-chilexpress-shipping#194]
Hola, resulta que estoy intentando crear el calculo de tarifa aproximada mediante una comuna, pero estas no se despliegan bien, como mencionaste antes este puede ser un bug en WS QA, y que se soluciona en WS PROD con las respectivas api usuario y api contraseña, pero no entiendo de donde obtener dichas claves, pues en chilexpress developer solo me entregan una llave para cada api y no algo como usuario y contraseña.

¿Como se haría la implementación en este caso? (recurro a ti porque la api "oficial" ni se digna en funcionar)

**Comment by TCattd** [comment]
@dhvasquez yo no voy a compartir directamente el user/pass que anda dando vueltas por varios lados en internet para la API de Chilexpress.

Por eso existe este otro issue, para que ustedes lo vean, como comunidad: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

Se de los problemas de la API de Chilexpress. Tenemos que lidiar con ella todo el tiempo. No puedo hacer nada ahí lamentablemente.
