### ISSUE TITLE
Comunas/Ciudades no congruentes.

### ISSUE THREAD

**Issue by josueCalcina** [whooohq/whq-woocommerce-chilexpress-shipping#195]
Hola, buenas tardes.

Felicidades por el trabajo y es de mucha ayuda para emprendimientos como el mio que recién están empezando y no saben que método o empresa de envió utilizar, por la DEMO en vivo pude comprobar que los combo-box de region y comunas funcionan perfectamente, por lo que lo instale sin pensarlo dos veces, realice los ajustes necesarios y probé  pero note que las comunas juntos con las regiones no concuerdan, por lo que entre al foro y pues desactive y los plugins innecesarios y actualice los necesarios, pero no hay cambio alguno, ¿Qué puedo hacer? 

Adjunto fotos 

![image](https://user-images.githubusercontent.com/51217381/91094056-43469180-e628-11ea-8d5e-6c3401aca143.png)

![image](https://user-images.githubusercontent.com/51217381/91094133-6113f680-e628-11ea-9600-3506ad010e02.png)

Es la única comuna que me aparece para la segunda Región :(

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128
