### ISSUE TITLE
Con el plugin activado, no tengo otras opciones de envío

### ISSUE THREAD

**Issue by javieraprib** [whooohq/whq-woocommerce-chilexpress-shipping#196]
Hola, tengo configuradas otros tipos de envío para la Región Metropolitana (Retiro en local), pero al activar este plugin, esas opciones ya no aparecen en el checkout. Aparece envío por chileexpress como única opción.

Ayuda! Muchas gracias

**Comment by TCattd** [comment]
@javieraprib me puedes enviar el acceso a tu wp-admin al correo esteban (arroba) actitud.xyz

Por favor.

Gracias

**Comment by javieraprib** [comment]
Enviado!

**Comment by TCattd** [comment]
Resuelto @javieraprib 

Ver: https://tppr.me/K2TTv

¿El problema?

Otro plugin no compatible: MasterBip Regiones Comunas y Pesos de Chile. Agregado a la lista de plugins con incompatibilidad.

Chilexpress ya llena los campos de región/ciudad con los valores correctos, no siendo necesaria esa modificación de aquel otro plugin.
WooCommerce ya incluye el peso Chileno por default, hace bastantes versiones la verdad. Tampoco es necesario aquel plugin para agregarlo.

Esteban
