### ISSUE TITLE
Compatibilidad con plugins Multi-Vendor

### ISSUE THREAD

**Issue by cafusinho** [whooohq/whq-woocommerce-chilexpress-shipping#197]
Hola estimados,

quisiera saber si este plugin soluciona el problema que tiene actualmente le plugin de Chilexpress el cual no es compatible con Multivendor y en caso contrario sabe como se podria solucionar?.

saludos y buen trabajo.

**Comment by TCattd** [comment]
@cafusinho no tengo idea que es el "Multivendor" que mencionas.

Si quieres puedes probar ese "Multivendor" con nuestro plugin https://wordpress.org/plugins/woo-chilexpress-shipping/ y nos cuentas luego acá mismo como te fue, por favor.

Esteban

**Comment by cafusinho** [comment]
Gracias por tu pronta respuesta, cuando me refiero con multivendor es que en un ecoomerce existan multiples tiendas(c/u con distintas direcciones de origen) y actualmente el problema radica que Chile expres toma como referencia la direción de la tienda Madre( y no la de las tiendas registradas con distintas direccioneS), no se si me explique.

Me ayudaría bastante tu comentario al respecto.


saludos.

**Comment by TCattd** [comment]
@cafusinho no tengo experiencia con ningún tipo de plugin como el que mencionas.
Si puedes, eres más que bienvenido a probar nuestro plugin en ese caso que comentas, y comentarnos de vuelta si te funcionó o no con nuestro plugin. Por favor.

Muy agradecido desde ya.

Esteban

**Comment by TCattd** [comment]
Re-abrir al tener novedades, por favor. ¡Gracias!
