### ISSUE TITLE
wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 454

### ISSUE THREAD

**Issue by Mario-HM** [whooohq/whq-woocommerce-chilexpress-shipping#198]
Estimados ayuda !!!!
al agregar productos en WooCommerce me aparece esto al pie de la pagina
**wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 454**

version de **WP** es 5.5.1
Version de **WooCommerce** es 4.5.2
Version de **Chilexpress Shipping for WooCommerce** es 1.4.28

Por favor su ayuda ya que me da miedo tener esa ruta expuesta a todo el publico

desde ya muchas gracias

**Comment by TCattd** [comment]
@Mario-HM quizás por el theme (css), no se ve el resto del mensaje de error que debería ir antes de lo que copiaste acá.
Me puedes enviar la URL del sitio, ¿por favor?.
Acá si no es problema hacerlo público. Si no, por email: esteban @ actitud.xyz

¡Gracias!

**Comment by Mario-HM** [comment]
@TCattd este es el sitio https://electronicachile.xyz
al momento de agregar un producto aparece este mensaje en la parte superior:
Warning: A non-numeric value encountered in /home/heath18/electronicachile.xyz/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 454

desde ya muchas gracias

**Comment by TCattd** [comment]
Eso es lo que faltaba @Mario-HM 

**Warning: A non-numeric value encountered**

Problema duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/162
Ahí mismo la solución, estimado.

Esteban
