### ISSUE TITLE
Problema con la Región de Valparaiso

### ISSUE THREAD

**Issue by gerardo-del-rio** [whooohq/whq-woocommerce-chilexpress-shipping#199]
Hola, muy bueno el plugin, los felicito. 

Ahora bien, el plugin me esta arrojando un problema, cuando se ingresa una dirección de la Región de Valparaiso y haces click en el botón de pagar, me arroja un mensaje. Un problema grave porque mi cliente tiene varias compras en esa region.

Me pueden ayudar a solucionarlo?

![Captura de pantalla 2020-10-02 a la(s) 15 39 36](https://user-images.githubusercontent.com/70386149/94959519-b7960f80-04c7-11eb-9fc6-0ea8afad7046.png)

**Comment by TCattd** [comment]
@gerardo-del-rio , por favor, desactiva todos los plugins excepto WooCommerce y este plugin de Chilexpress.
Luego prueba intentar hacer una compra.

Nos avisas como te va, por favor.

Gracias.

**Comment by gerardo-del-rio** [comment]
Hola!, desactivé este plugin y me funcionó: [Regiones de Chile para WooCommerce](https://es.wordpress.org/plugins/regiones-de-chile-para-woocommerce/)

**Comment by TCattd** [comment]
Gracias por el aviso @gerardo-del-rio 
Agregado a la lista de plugins incompatibles.

Ver https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-326564653

La explicación de por qué no funciona, está allá.

Muchas gracias nuevamente por la ayuda, estimado.
