### ISSUE TITLE
Poder seleccionar comunas en la opción de: Región(es) de la zona de envío

### ISSUE THREAD

**Issue by erikdeso** [whooohq/whq-woocommerce-chilexpress-shipping#200]
Hola, 

Estuve revisando los demás issues e instalé el plugin, que por lo demás es excelente. Pero hay algo que necesito y no lo puedo hacer, desconozco si podría ser algo fácil  de resolver o no. Agregó que probé el plugin oficial de chilexpress y me pasa lo mismo, no obstante, encontré una empresa que vende un plugin que si hace lo que necesito, pero es algo caro para mi.

Cómo dice el titulo, la idea que busco es que en la zona de regiones aparezcan las comunas al seleccionar zonas de envío, ya que así puede definir por comunas los métodos de envío (en mi caso, chilexpress y propio). Comparto pantallazo que resume todo lo anterior.

https://snipboard.io/xHoiTF.jpg

Muchas gracias,
Erik

**Comment by erikdeso** [comment]
Agrego pantallazo de como se ve al momento del cliente poner su dirección. Así solo debe elegir su comuna/ciudad, la cual aparece en el campo de región, pero con loco translate le cambió el nombre, eso no es problema.

Sería genial, si pudiera hacer esto en tu plugin :).

https://snipboard.io/RTmDNK.jpg


Gracias,
Erik

**Comment by TCattd** [comment]
Zonas de envío de WooCommerce https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39

No está implementado en este plugin aún.
Lo siento.
No hay ETA tampoco.

**Comment by cjrojas89** [comment]
Hola respecto a este comentario: `Estuve revisando los demás issues e instalé el plugin, que por lo demás es excelente. Pero hay algo que necesito y no lo puedo hacer, desconozco si podría ser algo fácil de resolver o no. Agregó que probé el plugin oficial de chilexpress y me pasa lo mismo, no obstante, encontré una empresa que vende un plugin que si hace lo que necesito, pero es algo caro para mi.

Cómo dice el titulo, la idea que busco es que en la zona de regiones aparezcan las comunas al seleccionar zonas de envío, ya que así puede definir por comunas los métodos de envío (en mi caso, chilexpress y propio). Comparto pantallazo que resume todo lo `anterior.``

Que empresa vende ese plug in? realmente lo necesito, estoy haciendo mi propia pagina web, y si bien este plug in funciona bien con chile express, necesito configurar unas zonas de envios de comunas en la region metropolitana con un envio por motorizado express, eso potenciará mi negocio. cuando puedas comparteme el dato de que empresa vende esta solución. saludos. mi email cjrojas89@hotmail.com
