### ISSUE TITLE
Compatibilidad con WordPress Multisite 2020

### ISSUE THREAD

**Issue by thegeomaster** [whooohq/whq-woocommerce-chilexpress-shipping#201]
Hola TCattd:

Creo que para la versión 1.4.29 de woocommerce-chilexpress-shipping en Woocommerce v4.6.0, Wordpress 5.5.1, nuevamente parece no funcionar en ambiente multisite. Inicialmente si funcionaba cuando el sitio aún no era multisite (era una de las pruebas de funcionalidad antes de pasar a multisite), y ahora revisando la operatividad del sitio, me encontré con este incidente.

Ya revisé los plugins incompatibles (Checkout field editor), y a pesar de desactivarlos para revisar, el incidente persiste.

Espero tu ayuda

Gracias

**Comment by TCattd** [comment]
@thegeomaster no funciona, ¿por?.
¿Podrías explayarte en el problema que tienes, por favor?

¿Lo puedes activar?
¿Se ve o no la config del plugin dentro de WooCommerce?
¿Problemas con el carro o checkout?.

¡Gracias!

**Comment by thegeomaster** [comment]
Es simple. El acceso a la configuración no aparece en entorno multisite.
Aquí se ve que el plugin está activado...
![image](https://user-images.githubusercontent.com/43662332/97053197-d03e9600-1558-11eb-9746-d9316859ba14.png)

Pero acá no aparece el enlace o el acceso a la configuración...
![image](https://user-images.githubusercontent.com/43662332/97054329-ff560700-155a-11eb-9d2a-2dfd46ee5430.png)

En cambio en el sitio clon en entorno único, el plugin funciona correcto...
![image](https://user-images.githubusercontent.com/43662332/97053379-3cb99500-1559-11eb-8fca-f252fa52fd14.png)

Como te mencioné anteriormente, el sitio se construyó en entorno único. Luego que se confirmó que funcionara todo correctamente (incluido este plugi), se habilitó para entorno multisite, y ahí dejó de aparecer el acceso a la configuración.

Apelo a tu ayuda para resolverlo, porque el plugin oficial no funciona correctamente en entorno multisite, y de parte de ellos no hay respuesta ante esta incidencia.

Gracias por tu soporte

**Comment by TCattd** [comment]
@thegeomaster estimado,

Pude revisar el tema recién.
Sabes, no puedo replicar el problema.

Ver:
https://tppr.me/Fzt1B

https://tppr.me/rQ5MI

Funcionando sin problemas en un WP Multisite nuevo, recién creado.

Por favor, asegúrate que estás usando la última versión de WP, WC y que no sea un problema de compatibilidad con un plugin de terceros.

Gracias.

**Comment by thegeomaster** [comment]
Súper compadre... mira que como es para una tienda con sucursales, tuve que hacer el juego de sitios independientes dentro del mismo hosting... un quebradero de cabeza al no tener el control transversal de los complementos.
Lo vuelvo a revisar y te aviso...

**Comment by TCattd** [comment]
Reabres si hay novedades, por favor. Gracias.
