### ISSUE TITLE
Envío gratuito solo en la localidad de santiago?

### ISSUE THREAD

**Issue by toby12222** [whooohq/whq-woocommerce-chilexpress-shipping#202]
Estimado, muy buen plugin, seria posible agregar solo envio gratuito a la región de santiago? ya que en los shipping zones no aparece santiago, solo chile, es decir puedo colocarle envío gratuito a todo chile pero no a una sola localidad :(

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/191#issuecomment-671529298

No es algo que este plugin deba tratar, estimado. Lo siento.

Esteban
