### ISSUE TITLE
Envío a RM y Valparaíso

### ISSUE THREAD

**Issue by camilagibli** [whooohq/whq-woocommerce-chilexpress-shipping#204]
Hola, el plugin me funciona excelente con envios a todas las regones, excepto a RM  y Valparaíso, no calcula el costo de envio ni permite seleccionarlo como metodo de envio, como puedo solucionarlo? agradezco su ayuda!

**Comment by TCattd** [comment]
@camilagibli quizás es un duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#no-se-muestran-todas-las-ciudades-dentro-de-una-regi%C3%B3n

Revisa, por favor.

**Comment by camilagibli** [comment]
no, a mi si me cargan todas las ciudades de las regiones pero al seleccionar por ejemplo Providencia, no me muestra valor asociado ni me permite seleccionarlo como método de envío, en cambio si pruebo con la Región de los Ríos, ciudad Valdivia, me muestra el valor y lo puedo seleccionar.

**Comment by TCattd** [comment]
Podría ser esto entonces: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/27#issuecomment-321929605

Throttle.
Si lo es, frente a eso no puedo hacer nada, Camila.

Probando en https://wpchilexpress.whooohq.com no hay inconvenientes con RM y Valparaíso.
Ver:
https://tppr.me/Y03vb
https://tppr.me/TGaCf

**Comment by TCattd** [comment]
Ah, lo otro es que te asegures que los tipos de envío recomendado estén seleccionados.
Ver: https://tppr.me/Vg2tY
Eso es importante. Si no, dependiendo del origen de los envíos, Chilexpress podría no mostrar valores si limitaron las opciones a una que no esté disponible entre el origen-destino de la compra del cliente.

**Comment by camilagibli** [comment]
sii era el problema desde los ajustes, está limitada la opción de envio al dia siguiente. 
Muchas gracias por tu ayuda!

**Comment by TCattd** [comment]
;)

Gracias por confirmar.

Esteban
