### ISSUE TITLE
Glitch visual campo región en el checkout

### ISSUE THREAD

**Issue by jparesl** [whooohq/whq-woocommerce-chilexpress-shipping#206]
Tengo el problema que al usar el plug de Chilexpress en la pantalla de finalizar la compra la casilla de región me aparece cortada y no puedo seleccionar.

<img width="703" alt="Captura de Pantalla 2020-11-18 a la(s) 15 04 27" src="https://user-images.githubusercontent.com/74677592/99570640-fec15c80-29b0-11eb-828a-1ba7c61433bb.png">

gracias.

**Comment by TCattd** [comment]
@jparesl , por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Luego nos comentas.
Gracias.

**Comment by TCattd** [comment]
Reabres si nos tienes novedades, por favor.
