### ISSUE TITLE
Compatibilidad con las zonas de envio

### ISSUE THREAD

**Issue by toby12222** [whooohq/whq-woocommerce-chilexpress-shipping#207]
Excelente plugin, sería posible de alguna forma poder agregar más zonas de envíos o distintos precios por comuna o ciudad? por favor seria muy util que funcionaran las zonas de envío por ciudad o comuna, por ejemplo envíos gratuitos o contra entrega en algunas zonas en específico. gracias

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39
