### ISSUE TITLE
Error al Seleccionar - ¿Enviar a una dirección diferente?

### ISSUE THREAD

**Issue by KraptorChile** [whooohq/whq-woocommerce-chilexpress-shipping#208]
Hola a todos,

Un cliente me reportó problemas para concretar una compra, logré reproducir el error

Sólo aparece cuando el comprador quiere enviar a una dirección **diferente** a la suya. (¿Enviar a una dirección diferente?)

Al seleccionar el flag:

1.- No aparece el servicio de Chilexpress como método de envío
2.- La Comuna y Región de la dirección del comprador (No dirección de despacho) se desmarca.
3.- Al seleccionar nuevamente Región y Comuna en la dirección del comprador y en la dirección de despacho, no aparece el método de envío de Chilexpress y además aparece el siguiente error: Envío Región es un campo requerido.

Le ha pasado esto a alguien?

Saludos

**Comment by TCattd** [comment]
@KraptorChile 

WP limpio, última versión del plugin de Chilexpress nuestro, y última versión de Storefront:
https://tppr.me/opOo6

https://tppr.me/vPIL6

Ningún problema por acá.

Por favor:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout

Nos comentas luego.
Gracias!

**Comment by KraptorChile** [comment]
Hola!

Gracias por la respuesta, no he logrado resolver el problema

Después de navidad voy a desactivar todos los plugins y probar alguna incompatibilidad.

Saludos y Gracias!

**Comment by TCattd** [comment]
Reabres y comentas si tienes novedades, por favor. ¡Gracias!
