### ISSUE TITLE
Chilexpress desaparece tras elegirlo como método

### ISSUE THREAD

**Issue by rsseguel** [whooohq/whq-woocommerce-chilexpress-shipping#210]

**Comment by rsseguel** [comment]
He hecho algunas pruebas con el plugin y la verdad funciona a veces. Hace poco intenté volver a elegirlo como medio de pago pero ahora simplemente desaparece. He hecho todo de cero y sigue igual. La cosa es que debo montarlo en un sitio para la empresa y no se como fiarme si a veces aparece y otras veces no.

Antes de publicar esto, volví a hacer otra prueba pero vuelve a desaparecer sin motivo alguno.

¿Alguien sabe si es se puede confiar en él o está fuera de desarrollo o algo así? ¿Se puede solucionar o hay que inscribirse en Chilexpress y tener el TCC y usar el oficial?

Saludos y juro que los amo se me ayudan a resolver eso :(

[
<img width="919" alt="Captura de pantalla 2021-01-23 163139" src="https://user-images.githubusercontent.com/77898172/105612145-e860c400-5d98-11eb-9b37-24132dc6df12.png">
](url)

**Comment by TCattd** [comment]
Es porque usas el plugin de correos de chile junto con este.
No son compatibles uno con otro.

Hemos conversado con ellos, hay ideas, lo que no he tenido por mi parte al menos es tiempo para poder implementarlas.

Lo siento.

El plugin nuestro funciona. Puedes verlo andando en vivo en https://wpchilexpress.whooohq.com/

Debes elegir uno de los dos plugins, lamentablemente.

Esteban

**Comment by rsseguel** [comment]
Hay algún plugin de Correos de Chile que si se pueda usar en conjunto con el de Chilexpress?

**Comment by TCattd** [comment]
No lo sé, la verdad, no lo sé.
Lo siento.

Esteban
