### ISSUE TITLE
Algunas zonas con valor, otras sin valor. 

### ISSUE THREAD

**Issue by andreschy** [whooohq/whq-woocommerce-chilexpress-shipping#211]
Hola estimados muchas gracias por la ayuda. 
Estuve buscnado solución a mi problema, vi que alguien levanto el mismo problema pero sin solución, por lo cual pregunto nuevamente.
Antes tenia el error de que me mostraba pocas comunas, hice lo de WP PROD y borrar los transients, todo ok hasta ahi, se cargaron todas las comunas y pensé que estaría solucionado, sin embargo al momento de ingresar las regiones y la comuna, en algunas localidades me arroja la tarifa real, y en otras no arroja nada. Por ejemplo si selecciono Valparaiso --> Cartagena, me arroja la tarifa real.. pero si selecciono "quillota" o "Casablanca" me arroja error de "No hay opciones de métodos de envío disponibles. Por favor, asegúrate de que has introducido correctamente tu dirección, o contáctanos si necesitas ayuda."
Favor si alguien pudiera ayudarme con esto?

**Comment by TCattd** [comment]
Buenas,

¿Puedes dejar un pantallazo de la configuración del plugin en las opciones de envío de WooCommerce, por favor?

Gracias.

**Comment by andreschy** [comment]
muchas gracias por tu respuesta te dejo pantallazos con el error de ejemplo y con las opciones de envío en woocommerce.
![ev1](https://user-images.githubusercontent.com/78291549/106478806-5cc9f000-6488-11eb-821c-1bddb939ed31.JPG)
![ev2](https://user-images.githubusercontent.com/78291549/106478807-5dfb1d00-6488-11eb-8650-70329a10eee9.JPG)
![plugin](https://user-images.githubusercontent.com/78291549/106478808-5e93b380-6488-11eb-9fb3-05149b459c6c.png)

**Comment by TCattd** [comment]
@andreschy acá está tu problema: https://tppr.me/U7Z4d

> Considera que dependiendo de la ubicación de origen de tus envíos, algunas localidades extremas podrían no contar con un tipo de envío normal (día hábil siguiente), y solo tener disponible envío al tercer día, por lo que lo recomendado es que selecciones al menos "Prioritario", "Express" y "Extendido".
> Ten presente que los envíos Ultra Rápidos y Overnight están disponibles solo en ciertas ciudades de origen y para algunos destinos.

Si seleccionas solo Express, como lo hiciste ahí, y entre la comuna de origen de tus envíos (Vitacura en este caso) y la de destino del usuario NO existe el envío Express de Chilexpress, entonces Chilexpress simplemente NO mostrará un tipo de envío disponible.

Eso es lo que te está ocurriendo.
Problema de configuración de vuestra parte.

Cualquier otra cosa nos avisas, por favor, y reabres.
Gracias.

Esteban
