### ISSUE TITLE
No aparece en Ajustes Chilexpress

### ISSUE THREAD

**Issue by NamitasCl** [whooohq/whq-woocommerce-chilexpress-shipping#214]
Hola, acabo de instalar wordpress y woocommerce, y encontre el plugin del que hablan en este lugar, la verdad no tengo muchos conocimientos de desarrollo web, pero lo instalo y activo y no aparece en las opciones de envio de ajustes de woocommerce, me podrías señalar por favor como puedo hacer que aparezca?

Muchas gracias!

**Comment by TCattd** [comment]
WooCommerce -> Ajustes -> Envío -> Chilexpress.

O en la lista de plugins, tienes acceso a la configuración directamente en el mismo plugin: https://tppr.me/1OIH1

Esteban
