### ISSUE TITLE
Plugins incompatibles - opción para añadir un campo? 

### ISSUE THREAD

**Issue by renataqb** [whooohq/whq-woocommerce-chilexpress-shipping#215]
Hola, aparte de estos plugins incompatible, qué opciones quedan para agregar un importante campo en Chile, que es la cédula de identidad, información sin la cual no es posible emitir boletas?

Agradezco las sugerencias y agradezco el plugin!

--------------
Plugins **parcialmente** incompatibles con el nuestro:

- [Woo Checkout Field Editor](https://wordpress.org/plugins/woo-checkout-field-editor-pro/), **incompatibilidad parcial**. No necesariamente incompatible, pero si remueven el campo de país (y otros campos default de WooCommerce), el plugin nuestro no funciona. Incluso el autor de aquel plugin [no recomienda remover campos default](http://prntscr.com/g3w25m) de WooCommerce. [Ref](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/4#issuecomment-313159614).

- [WooCommerce Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/), **incompatibilidad parcial**. Al igual que otros "Checkout Field Editor", no es incompatibilidad total. Pero deben saber que si remueven items que vienen por default en WooCommerce, como lo es el campo de país, no solo pueden tener problemas con nuestro plugin, si no también con muchos otros que dependen de las funcionalidades que por default vienen en WooCommerce. WooCommerce mismo [advierte al respecto](http://prntscr.com/g3vww9) en su [documentación](https://docs.woocommerce.com/document/checkout-field-editor/). [Ref](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/4#issuecomment-313159614).

_Originally posted by @TCattd in https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-326564625_

**Comment by TCattd** [comment]
Parcialmente incompatible. No necesariamente incompatible https://tppr.me/qPHmT

Lo puedes usar. Ciertamente puedes agregar campos al checkout sin mayor inconveniente. Eso no debería ser un problema.

Pero si algo en nuestro plugin deja de funcionar por usar un plugin como ese (los motivos los menciona el mismo texto que has citado), no lo vamos a arreglar por nuestro lado.

Buen día.

Esteban
