### ISSUE TITLE
Spinner en selección de ciudad en el checkout

### ISSUE THREAD

**Issue by ya-casi** [whooohq/whq-woocommerce-chilexpress-shipping#216]
Hola!
He usado este plugin desde hace un tiempo y me parece una super buena alternativa al plugin oficial.

Tengo la duda si el Spinner (como si la pagina estuviera cargando todo el tiempo) que aparece antes de completar los datos de despacho se puede quitar, resulta confuso para el cliente saber que puede ingresar los datos aun cuando aparezca eso.
adjunto captura 

https://postimg.cc/qzHtp19Y

Saludos...

**Comment by TCattd** [comment]
El problema es que, sin el, recibíamos quejas al revés de lo que nos comentas. Gente que se quejaba de que sus usuarios no entendían que debían seleccionar primero la región para luego poder seleccionar la ciudad, que decían que veían que no había ciudades disponibles porque claro, no seleccionaban la región primero.

¿Qué hacer entonces?.

Removerlo por que si, bajo esas experiencias previas, no lo creo.
Mejorar el procedimiento o lo que ven los usuarios: si, sin duda.

Sugerencias son bienvenidas.

**Comment by ya-casi** [comment]
Entiendo, tal vez si el Dropdown de la comuna fuese dinámico y estuviera oculto inicialmente y que aparezca luego de seleccionar la region sería una buena alternativa

**Comment by danidev3** [comment]
Hola soy nuevo y me gusto mas este plugin que el oficial. Justamente me tope con el spinner. Que tal si se deshabilita el spinner de ciudad para que el usuario seleccione la region primero?

Saludos.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
