### ISSUE TITLE
Diferencia de $1799 entre el cálculo del plugin versus el cotizador de Chilexpress

### ISSUE THREAD

**Issue by namoracinom** [whooohq/whq-woocommerce-chilexpress-shipping#217]
Hola Esteban. Instalé el plugin y no entiendo por qué en cada cálculo hay una diferencia de $1799 con respecto al resultado, si lo comparo con lo que que entrega la página de cotización de Chilexpress. Será que el algoritmo de cálculo del plugin utiliza una tarifa unitaria que no esté actualizada? He hecho la prueba simulando diferentes comunas de destino, pero la diferencia persiste. Agradeceré tu pronta respuesta y ayuda.

**Comment by TCattd** [comment]
Chilexpress.cl

Origen: https://tppr.me/D0qMZ
Paquete de 1kg, 10x10x10cm: https://tppr.me/Yu9F8
Destino: https://tppr.me/LkECk
Envíos disponibles: https://tppr.me/uqOrk
Valores: $7497 y $5015

Tienda local con plugin.

Origen: https://tppr.me/fqrll
Sin extra por embalaje: https://tppr.me/fK5Jc
Producto de 1kb, 10x10x10cm: https://tppr.me/XBVb0
Destino y envíos disponibles: https://tppr.me/k9OVg
Valores: $7447 y $4965

Bastante cercano a lo que muestra Chilexpress online en su cotizador.
La diferencia en este caso puede ser por que el cotizador de Chilexpress pide declarar el precio del producto, y eso suma un % al costo final. Declaré un producto de CLP$100.000.

Dicho eso, la diferencia en este caso fueron 50 pesos en ambos casos.

Ignoro si el valor en el cotizador de Chilexpress viene de la misma API pública que el resto tenemos que usar.
En el caso del plugin, el valor que devuelve la API es muy cercano al que entrega el cotizador de Chilexpress.

Prácticamente es el mismo valor.
La diferencia la pueden prevenir utilizando estas dos configuraciones del plugin: https://tppr.me/NV2bC

Debes revisar la configuración de tu tienda, estimado.

Esteban

**Comment by namoracinom** [comment]
Muchas gracias Esteban por tu pronta respuesta. Acabamos de hacer varias pruebas con nuestros productos (precios y dimensiones) comparando con el cotizador oficial y efectivamente hay una diferencia de $150 por unidad. Lo resolveremos con el mecanismo de las configuraciones que sugieres. 👍🏻
