### ISSUE TITLE
Disminuir Valor de Envio

### ISSUE THREAD

**Issue by javieriveros** [whooohq/whq-woocommerce-chilexpress-shipping#219]
Es posible en la configuración ajustar los valores de envio, por ejemplo aplicar una rebaja de $1.000.

Saludos

**Comment by TCattd** [comment]
Javier,

Realmente no tengo idea por qué alguien querría hacer esto, pero... andando en la versión 1.4.34

El "costo extra por embalaje" acepta valores negativos ahora. Lo que permite efectivamente restar precio de envío por producto.

Espero te sirva.

Esteban
