### ISSUE TITLE
No muestra combo box de las Ciudades/Comunas

### ISSUE THREAD

**Issue by albetix** [whooohq/whq-woocommerce-chilexpress-shipping#22]
@TCattd,

Algo más modificaste en el último release porque ahora no está desplegando el combo box de la Comuna/Ciudad:

- Carro de compras: [http://prntscr.com/g1l9hu](http://prntscr.com/g1l9hu)
- Checkout: [http://prntscr.com/g1la9l](http://prntscr.com/g1la9l)

Por favor revisar.

**Comment by TCattd** [comment]
Creo que no es un error de algún cambio en la última versión.
De hecho, antes de lanzar, siempre pruebo en una instancia limpia 100% de WordPress/WooCommerce con Storefront ([como menciono acá](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/CONTRIBUTING.md)).

Si vas acá https://wordpress.org/plugins/woo-chilexpress-shipping/advanced/ y bajas una versión anterior: http://prntscr.com/g1lpw4 e instalas aquella versión en un entorno de pruebas, el error persiste.

Me parece que es un problema de conexión con la API de Chilexpress.

Acá lo hice así. Bajé la versión 1.1.8, instale, y tengo el mismo problema.
Lo mismo ocurre con la 1.1.7 también.

Algo pasa con la API de Chilexpress lamentablemente. ¿Caída?. ¿Cambiaron algo?.

**Comment by albetix** [comment]
Que frustrante. Quizás sería bueno agregar un timeout a la consulta a Chilexpress para desplegar un mensaje si no responde en un tiempo determinado.

**Comment by TCattd** [comment]
Se fue un nuevo release en vivo.

Mejora la detección (en este caso en particular) de la "caída" de la API de Chilexpress (no puedo estar seguro que están haciendo la verdad o que les está pasando).

En este caso, si aún hay regiones en el transient local de WordPress, luego de seleccionar la región... si la API no responde correctamente... el carro y checkout se restauran a como estaban antes, con el mensaje ya existente de "Chilexpress no disponible en estos momentos".

De todos modos, hay que ver en profundidad que pasa con esto si sigue así de aquí a mañana.

**Comment by albetix** [comment]
Si bien despliega el mensaje, igual permite realizar la compra ya que no quita la selección del medio de despacho. Esto es problemático porque si alguien compra, implica realizar una anulación o despachar con un costo distinto al real.

Acá va la imagen: [https://prnt.sc/g1mkji](https://prnt.sc/g1mkji)

**Comment by TCattd** [comment]
Resuelto http://prntscr.com/g1nerk (espero).
Va la actualización.

Me comentan si hay algún otro error, por favor.

Gracias por la ayuda con esto igual @albetix ;)

**Comment by TCattd** [comment]
Apliqué un work-around al problema del listado de ciudades.

Puesto que la API aún no responde con el listado de ciudades, el plugin ahora tiene un backup del listado de ciudades de manera fija (hard-coded, el que alguna vez usamos).
En caso de que la API de Chilexpress no responda con el listado de ciudades para una región específica (como ahora), entonces se traerá el listado completo de ciudades, independiente de la región seleccionada.

Nada que hacer por ahora (respecto al listado completo de ciudades y no por región), a menos que se "mapeen" a mano cada región con su ciudad en el array de la clase que aloja el listado, cosa para la que aún no tengo tiempo la verdad. De todos modos el select2 en ese campo debería alivianar el problema pudiendo tipear el nombre de la localidad para filtrar rápidamente.

De esta forma (por último) es posible aún utilizar el servicio de Chilexpress en caso de caída del listado de ciudades, puesto que las llamadas al "cotizador" de la API aún funcionan.

**Comment by albetix** [comment]
Quedó perfecto en el checkout pero sigue mostrando el mensaje de Chilexpress caído en el carro. Si quieres déjame esa a parte a mi. Lo puedo revisar más tarde o mañana en la mañana.

**Comment by TCattd** [comment]
No me di cuenta del carro. Lo siento.

Agradecido por la ayuda desde ya. Bienvenida sea.

**Comment by TCattd** [comment]
La API de Chilexpress volvió arriba, pero cambiaron algo. Y las ciudades vuelven con un 2 al final.
Revisando...

**Comment by TCattd** [comment]
En la lista hard-coded que mantenemos, hay N localidades que tienen un código que no corresponde, y otras que no estaban y deberían estar.
Voy a actualizar esa lista a mano (240 localidades).

Lanzado un update con el fix al cambio de la API de Chilexpress.

Actualizando la lista a mano. Lanzo un segundo update luego con esas listas corregidas.

Bienvenida la ayuda con lo del carro aún, por si acaso. Si quieres simular la caida de la API en ese punto, dejé una linea comentada en ajax.php: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/includes/ajax.php linea 55.
Al dejar $cities en false, obtiene la lista hard-coded de ciudades, y puedes trabajar en lo otro. Si aún quieres ayudar, estimado ;) (y agradecido desde ya)

**Comment by TCattd** [comment]
Arriba el update con las listas hard-coded actualizadas.

Ahora son dos, una de localidades aptas para recepción de paquetes, y otra con localidades aptas para retirar envíos (según API de Chilexpress, no todas las localidades están habilitadas para ambos casos).

Ahora las listas están separadas, y actualizadas.

**Comment by albetix** [comment]
Quedó listo el pull request con las mejoras para el carro de compras.

Consulta aparte, ¿de dónde se puede obtener la documentación de la API de Chilexpress? para poder entender mejor las diferentes opciones que ofrece ahora.

**Comment by TCattd** [comment]
Excelente. Agradecido nuevamente, estimado.

Lo otro. Correo: esteban arroba actitud.xyz
Por favor ;)
