### ISSUE TITLE
Agregar comunas como zonas de envío

### ISSUE THREAD

**Issue by gportillap** [whooohq/whq-woocommerce-chilexpress-shipping#220]
Estimados,

Tengo una web en la que quiero que además de Chilexpress exista otra opción con precio fijo según algunas comunas de Santiago.

Por ejemplo, si selecciono Region Metropolitana, La Reina, que me aparezca La opción de Chilexpress y también la opción de envío a la reina con un precio fijo.

Veo que el plugin incluye las regiones y comunas de chile, pero las comunas no son seleccionables en las opciones de Envío (Zonas de envío) de WooCommerce.

Por lo mismo instalé un plugin (https://wordpress.org/plugins/wc-ciudades-y-regiones-de-chile/) que dice tener compatibilidad con el suyo y añade las comunas. Pude hacer lo que quería, pero aún así tengo problemas ya que la opción de Chilexpress me aparece SIN SERVICIO con ciertas comunas, cosa que no pasa cuando desactivo este plugin externo.

En resumen, quiero saber si existe alguna posibilidad de hacer esto agregando de alguna forma (vía código u opciones) las comunas que incorpora este plugin, sin usar plugins externos.

De antemano muchas gracias!

**Comment by TCattd** [comment]
Duplicado de https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39
