### ISSUE TITLE
Hay algunas ciudades que no hace el cálculo

### ISSUE THREAD

**Issue by cristiansilvada** [whooohq/whq-woocommerce-chilexpress-shipping#225]
Hola. primero que todo felicitar por el pluggin y hacer todo esto más sencillo del ecommerce.

Quería preguntar lo siguiente: cuando yo coloco Región Los Lagos comuna Castro, me aparece lo siguiente

"no hay opciones de métodos de envío disponibles. por favor asegúrate de que has introducido correctamente tu dirección o contáctanos si necesitas ayuda"

me pasa con esa y con otra, pero no me acuerdo cuál. ¿A qué se debe y cómo se puede solucionar?

Tengo la última versión.

Saludos

**Comment by TCattd** [comment]
Buen día,

Tienda de demo en vivo, resultado: https://i.imgur.com/m7DMKtk.png
Puedes probar en vivo acá: https://wpchilexpress.whooohq.com/

Se debe a esto, en las opciones del plugin: https://i.imgur.com/Dr2bhFJ.png
Debes configurarlo correctamente, como dice en las opciones (a menos que tengas una buena excusa para no seleccionar Extendido, por ejemplo).

Esteban

**Comment by cristiansilvada** [comment]
Muchas gracias. Se solucionó, muchos saludos y buen pluggin.
