### ISSUE TITLE
Como editar el mensaje "Sin Servicio"

### ISSUE THREAD

**Issue by AtrixTrash** [whooohq/whq-woocommerce-chilexpress-shipping#226]
Hola estimados, alguna idea de como editar o borrar el mensaje de "SIN SERVICIO" que aparece cuando aún no completas todos los datos de la dirección?

Intenté en el archivo whq_wcchp_cart.js y el whq_wcchp_checkout.js directamente desde el editor de Plugin pero no funcionó.
Desconozco si no es la forma o sí no es la ubicación correcta donde se encuentra ese mensaje.

Espero alguien me pueda orientar, muchas gracias.

**Comment by TCattd** [comment]
Buenas.

Opción "Renombrar tipos de envíos" en la configuración del plugin.
