### ISSUE TITLE
WP Multi-Site: no aparece en ajustes la opción "Chilexpress"

### ISSUE THREAD

**Issue by fcastro12** [whooohq/whq-woocommerce-chilexpress-shipping#229]
Hola. Instalé y activé el plugin pero no aparece "Chilexpress" en las opciones de envío de ajustes de WooCommerce, intente también n ingresar a los ajustes directamente desde el plugin pero tampoco aparece la opción.

Espero me puedan ayudar, desde ya agradecido.

![plugin2](https://user-images.githubusercontent.com/9133716/147505439-1d30f818-bbaf-4e46-acc8-3e0565df0f81.JPG)
![plugin1](https://user-images.githubusercontent.com/9133716/147505440-1f0c5e97-17d2-4842-8d67-173449315754.JPG)

**Comment by TCattd** [comment]
¿@fcastro12 es un WordPress Multi-Site Network de casualidad?

**Comment by fcastro12** [comment]
Si, WordPress Multi-Site

**Comment by TCattd** [comment]
Estimado,

Si es posible, ¿me puedes enviar el acceso admin a tu WP y el acceso FTP/SFTP/cPanel también?, para poder revisar, por favor.
Si es posible, nada más. Si es así, escríbeme con esos accesos a esteban (arroba) actitud.xyz

Gracias.

**Comment by fcastro12** [comment]
Hola Esteban!. Finalmente ayer elimine todo e instale nuevamente desde 0 Wordpress, esta vez sin Multi-Site y me funcionó el plugin sin problemas, por tiempo lo tuve que hacer así. Saludos y muchas gracias igual por haber respondido mi caso.
![image](https://user-images.githubusercontent.com/9133716/147770863-db915200-36b9-49e0-bb36-60a243683196.png)

**Comment by TCattd** [comment]
Ok, estimado. Lo siento, no pude responder antes.

Muchas gracias por el aviso.

Cualquier otra cosa, atento por acá ;)

Esteban
