### ISSUE TITLE
Problema datos en Transients luego de update a 1.4.40

### ISSUE THREAD

**Issue by 2xffwd** [whooohq/whq-woocommerce-chilexpress-shipping#230]
Estoy presentando la dificultad que no carga la comunas (sale "undefined") una vez seleccionada la región cuando no estás logueado solamente.

Vi el post acerca de esto (que no carga las comunas) y como solucionarlo, sin embargo ninguna solucion funciono. Tratando de diagnosticar el problema me sale este error al log:

PHP Notice:  Undefined index: codregion in /public_html/wp-content/plugins/woo-chilexpress-shipping/includes/ajax.php on line 61

Me da la impresión de que puede estar relacionado con lo que me esta pasando.

Cualquier ayuda se los agradezco

WP 5.8.2 WC 6.0.0 PHP 7.3

**Comment by 2xffwd** [comment]
Después de hoy volver a borrar los transients y pasar a QA, borrar cookies, volver a PROD parece que se soluciono.

No se a que atribuir la solución....cierro el tema.

Excelente el plugin gracias por todo.

**Comment by TCattd** [comment]
Toda la razón.

Si los transients contienen datos de las regiones anteriores a WC6.0, la llamada falla.
Agregada versión del plugin a los transients generados, de tal forma que este tipo de actualizaciones no genere problemas.

Gracias por el aviso @2xffwd 

Esteban

**Comment by 2xffwd** [comment]
Actualice a la ultima version 1.4.43 y me vuelve el problema que aparece "undefined" en las comunas y aparece igualmente en el log el mismo error:

[08-Jan-2022 04:51:13 UTC] PHP Notice:  Undefined index: codregion in /home/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/ajax.php on line 61

Borre transients nuevamente cambie de QA a PROD, eventualmente se va a arreglar supongo pero no se que pasos seguir cada vez que pasa porque borrar solamente los transient que comienzan con "whq" no soluciona el problema.

**Comment by TCattd** [comment]
@2xffwd ¿de casualidad tu problema ahora es en el checkout o en el carro de compras? ¿o ambos?

**Comment by TCattd** [comment]
Gracias @2xffwd. Ahora puedo duplicar esto.

Chilexpress cambió algo en la API (ahora si). No se ve bien.

Denme un momento para ver que puedo hacer.

**Comment by TCattd** [comment]
@2xffwd disponible versión 1.4.44 https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/CHANGELOG.md

Actualiza, y me avisas como te va, por favor.
Gracias!

**Comment by 2xffwd** [comment]
Ahi si! Perfecto!

Muchas gracias

**Comment by TCattd** [comment]
Gracias ati @2xffwd por el aviso. Muy, muy agradecido.

¡Buen día!
