### ISSUE TITLE
No puedo encontrar las opciones del plugin

### ISSUE THREAD

**Issue by NVMGFC** [whooohq/whq-woocommerce-chilexpress-shipping#236]
Hola. 
Chicos, tal vez esto suene idiota pero es cierto, tengo la última versión de Wordpress, de Woocommerce, del tema, todo actualizado, PHP 7.4 y SOAP habilitado, pero no veo el menú de opciones CHILEXPRESS en Woocommerce -> Ajustes -> Envíos. Por lo tanto en Checkout no aparece como opción Chilexpress.

Intenté con el tema Storefront, desactivando todos los plugins menos Woocommerce y nada, lo mismo. No aparece Chilexpress como opción donde debe aparecer.

Sabrían a que se puede deber esto?
Les agradezco un montón.

**Comment by sergioaraos** [comment]
Hola!  Lo mismo por acá. 

![image](https://user-images.githubusercontent.com/64826895/155758777-de5ce2c4-317a-4a82-85ad-0e0e0445d6d5.png)

**Comment by TCattd** [comment]
Funcionando sin problemas en el sitio demo del plugin: https://i.imgur.com/igkrrVA.png

@NVMGFC @sergioaraos de casualidad sus WP son multi sitio?

**Comment by juanjxxx** [comment]
Hola! me ocurre exactamente lo mismo, estaba operativo y ya no aparece. Realice instalación nuevamente y sigue lo mismo. 

que podra ser? desactive otros  plugin para probar y sigue ocurriendo 
<img width="1250" alt="Captura de Pantalla 2022-02-26 a la(s) 12 09 43" src="https://user-images.githubusercontent.com/100480086/155848216-2d2a732d-328a-40c3-a3f8-c7e534167262.png">

**Comment by TCattd** [comment]
@juanjxxx lo mismo que la duda anterior, por favor.

**Comment by juanjxxx** [comment]
no es multisitio

**Comment by juanjxxx** [comment]
@TCattd disculpa la ignorancia, que se refiere que sea multisitio?  es un wordpress en siteground.

**Comment by NVMGFC** [comment]
Hola. No, en mi caso no es multisitio.  (Esto es que desde una sola instalación, se pueden tener varios otros sitios o micrositios, para el amigo que consultó).

**Comment by TCattd** [comment]
Lo pude reproducir. Viene fix, pronto.

Gracias por la paciencia.

**Comment by TCattd** [comment]
Corregido en 1.4.46
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/CHANGELOG.md

¡Gracias nuevamente por la paciencia!

**Comment by NVMGFC** [comment]
Hola Esteban. Muy amable por tu preocupación y nada, gracias a ti. Como no pude solucionar lo de la última versión, estoy usando la penúltima: 1.4.43 y funciona de maravilla con todo lo demás al día, Wordpress (5.9.1) & Woocommerce (6.2.1) y el tema además actualizado a su última versión

**Comment by TCattd** [comment]
Ojo @NVMGFC con los downgrades. No lo recomiendo, para nada: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/231#issuecomment-1005949027

Pueden actualizar hoy en todo caso, sin problemas, a la versión 1.4.46, y verán las opciones en la versión más reciente del plugin.
