### ISSUE TITLE
Hubo un error crítico en tu sitio web.

### ISSUE THREAD

**Issue by juanitagonzalez** [whooohq/whq-woocommerce-chilexpress-shipping#241]
Estimado, escribo despues de haber seguido todos los pasos segun las instrucciones, activé Storefront, desactivé todos los plugins menos el de woocommerce y el de Chilexpress. y el error sigue apareciendo.
No me permite agregar al carro, en mi tema anterior, quedaba eternamente cargando, con las pruebas actuales, usando el theme recomendado, me genera el error "Hubo un error crítico en tu sitio web."
Muestro a continuación pantallazos:
Plugins activados
![C](https://user-images.githubusercontent.com/53576044/158629020-fa9091a8-83b1-4f02-84fb-715c6b823bf9.jpg)

![D](https://user-images.githubusercontent.com/53576044/158629262-a25d50d8-e2f3-4452-b920-3774ca04aee8.jpg)

Theme Activado:
![E](https://user-images.githubusercontent.com/53576044/158629345-a1003514-e280-4f95-b4b1-27a07feefe8c.jpg)

Prueba y Error:
![A](https://user-images.githubusercontent.com/53576044/158629409-1a480dc0-2449-4c40-8b59-00bfeb34f038.jpg)
![B](https://user-images.githubusercontent.com/53576044/158629436-4f53e041-7d6b-4ef9-bbf4-fcb658241f1a.jpg)

No tengo muchos antecedentes mas :c Pense por un momento que quiza estaba habiendo un conflicto con AJAX, ahora no lo se.
Seguiré investigando a ver que encuentro, mientras tanto dejo esto aqui, por si a alguien mas le esta pasando lo mismo, o si alguien encontró ya una solución :) 

Muchas gracias!

**Comment by juanitagonzalez** [comment]
Limpie el Log para ver exacto el problema y esto es lo que sale:

[16-Mar-2022 18:01:26 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /home2/regionan/public_html/zonagsh/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php:663
Stack trace:
#0 /home2/regionan/public_html/zonagsh/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php(633): WC_WHQ_Chilexpress_Shipping->calculate_shipping_by_shortest_side(Array)
#1 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(233): WC_WHQ_Chilexpress_Shipping->calculate_shipping(Array)
#2 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(348): WC_Shipping_Method->get_rates_for_package(Array)
#3 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(260): WC_Shipping->calculate_shipping_for_package(Array, 0)
#4 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1420): WC_Shipping->calculate_shipping(Array)
#5 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(339): WC_Cart->calculate_shipping()
#6 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(850): WC_Cart_Totals->get_shipping_from_cart()
#7 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(144): WC_Cart_Totals->calculate_shipping_totals()
#8 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(134): WC_Cart_Totals->calculate()
#9 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1398): WC_Cart_Totals->__construct(Object(WC_Cart))
#10 /home2/regionan/public_html/zonagsh/wp-includes/class-wp-hook.php(305): WC_Cart->calculate_totals()
#11 /home2/regionan/public_html/zonagsh/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#12 /home2/regionan/public_html/zonagsh/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#13 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1276): do_action('woocommerce_add...', 'fa422daa80f57e8...', 3054, 1, 3056, Array, Array)
#14 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(918): WC_Cart->add_to_cart(3054, 1, 3056, Array)
#15 /home2/regionan/public_html/zonagsh/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(790): WC_Form_Handler::add_to_cart_handler_variable(3054)
#16 /home2/regionan/public_html/zonagsh/wp-includes/class-wp-hook.php(307): WC_Form_Handler::add_to_cart_action('')
#17 /home2/regionan/public_html/zonagsh/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#18 /home2/regionan/public_html/zonagsh/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#19 /home2/regionan/public_html/zonagsh/wp-settings.php(609): do_action('wp_loaded')
#20 /home2/regionan/public_html/zonagsh/wp-config.php(91): require_once('/home2/regionan...')
#21 /home2/regionan/public_html/zonagsh/wp-load.php(50): require_once('/home2/regionan...')
#22 /home2/regionan/public_html/zonagsh/wp-blog-header.php(13): require_once('/home2/regionan...')
#23 /home2/regionan/public_html/zonagsh/index.php(17): require('/home2/regionan...')
#24 {main}
  thrown in /home2/regionan/public_html/zonagsh/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 663

**Comment by TCattd** [comment]
@juanitagonzalez no. El informe en tu admin de WooCommerce > Status > botón Get System Report > Copy for Support.
Todo ese texto, en un paste.ee, por favor. Gracias.

**Comment by juanitagonzalez** [comment]
[Woocommerce Status.txt](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/8272848/Woocommerce.Status.txt)

**Comment by TCattd** [comment]
Estimada, gracias.

Estás usando PHP 8.016

Lamentablemente, WordPress mismo aún no es compatible con PHP 8.x, y muchos de sus plugins (no solo el nuestro), no lo serán al 100, hasta que WP complete esa transición.
Por ahora, no es el caso https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/

Baja la versión de PHP de tu servidor a PHP 7.4, y nos comentas si el problema desaparece así, por favor.

Esteban

**Comment by juanitagonzalez** [comment]
ohhh MUCHAS GRACIAS!!!!!!!!! efectivamente, eso era, actualizaron el servidor a la ultima version hace poco XD, te agradezco monton tu tiempo. Dejare todos los sitios q tienen este genial plugin en la version 7.4 antes de que empiecen a llegarme mas issues jiji

Saludos!!

**Comment by TCattd** [comment]
Gracias a ti por confirmar, @juanitagonzalez 

Sobre PHP 8.x,

Espero trabajar en la compatibilidad con PHP 8.x para cuando WP anuncie fecha de lanzamiento para la versión 6.0, puesto que en ese caso, en teoría, WP será compatible al 100 con PHP 8.x. En teoría. No lo han confirmado aún.

Se que es algo que se que se debe hacer con este plugin y, espero, se hará. Cuando corresponda. Cuando WP fije fecha.
Por tiempo, más que nada. A esto le dedico solo tiempo libre.

Agradezco desde ya a todos ustedes (los que usan el plugin) la comprensión al respecto.

Esteban
