### ISSUE TITLE
Plugin habilitado pero no se visualiza en opciones de envío

### ISSUE THREAD

**Issue by vasquezmunoz** [whooohq/whq-woocommerce-chilexpress-shipping#242]
Hola!
Como indica el título de esta nota, el plugin se encuentra instalado y habilitado pero no se visualiza en las opciones de envío, incluso tras seleccionar Región y Localidad/Ciudad.
Me podrías indicar si hay algún cambio o problema con el complemento, por favor.
Muchas gracias por este complemento, ha sido de gran utilidad para nuestro sitio web.
Saludos!

**Comment by TCattd** [comment]
Estimado, buen día.

El plugin, el día de hoy, continua funcionando.

Ver tienda demo: https://wpchilexpress.whooohq.com/
Pantallazo de hoy: https://imgur.com/wfULPs1

Por favor, sigue los pasos aquí descritos para descartar problemas con tu theme y/u otros plugins: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout
Cuando tengas novedades, reabres el issue y nos comentas, por favor.

Gracias.

**Comment by vasquezmunoz** [comment]
Muchas gracias por tu atenta respuesta.
Deshabilité y habilité el complemento y volvió a funcionar.
Curioso... pero todo bien.
Saludos!

**Comment by TCattd** [comment]
Gracias por confirmar que está todo ok, estimado. Buen día.
