### ISSUE TITLE
Reporte de algunos problemas

### ISSUE THREAD

**Issue by 2xffwd** [whooohq/whq-woocommerce-chilexpress-shipping#245]
Hola

Hay dos problemas que he encontrado.

- En algunas ocasiones cuando la informacion de la region y comuna se ingresa una vez y el cliente no termina el checkout y vuelve a otra pagina y despues va a terminar el checkout, te dice que el campo de comuna es requerido cuando ya esta seleccionado previamente.

- El otro problema que igual genera inconvenientes a los clientes es que en algunas ocasiones cuando tienes un metodo de envio manual si seleccionas chilexpress no se selecciona realmente y se cambia al metodo manual de envio y hay que volver a seleccionar chilexpress una segunda oportunidad, muchos no se dan cuenta que se cambio y te entra una orden con un metodo de envio que no era el deseado por el cliente.

Esto sucede en mi ambiente de produccioon pero lo probe en un ambiente de prueba con woocommerce, chilexpress, mercado pago y transbank como plugins y hice un pequeño video donde podras darte cuenta de ambos problemas.

Aqui esta la captura https://drive.google.com/file/d/1i5s4qPndy_Io7Jt4THEoAUsPsb6w0ycF/view?usp=sharing

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 6.7.0
REST API Version: ✔ 6.7.0
WC Blocks Version: ✔ 7.8.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.28
PHP Post Max Size: 135 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.34-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.7.0
WC Database Prefix: wp_
Total Database Size: 4.78MB
Database Data Size: 3.18MB
Database Index Size: 1.60MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_url: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_litespeed_url_file: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_transbank_inscriptions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_webpay_rest_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
page: 7
post: 2
product: 1
shop_order: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Transbank Webpay REST: by TransbankDevelopers – 1.5.4
Chilexpress Shipping for WooCommerce: by Whooo & contributors – 1.5.2
Mercado Pago payments for WooCommerce: by Mercado Pago – 6.0.2
WooCommerce: by Automattic – 6.7.0

### Inactive Plugins (1) ###

LiteSpeed Cache: by LiteSpeed Technologies – 4.6

### Must Use Plugins (1) ###

closte-requirements.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: CLP ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-21 18:25:24 +00:00
Options: ✔
Notes: 42
Onboarding: completed

### Action Scheduler ###

Complete: 28
Oldest: 2022-07-19 18:27:35 +0000
Newest: 2022-07-20 19:28:16 +0000

Pending: 1
Oldest: 2022-07-21 19:11:59 +0000
Newest: 2022-07-21 19:11:59 +0000

### Status report information ###

Generated at: 2022-07-20 19:37:26 +00:00
`

**Comment by TCattd** [comment]
@2xffwd ojalá todos los reportes de errores fueran como lo que acabas de publicar acá.
Super, super bien.

Estimado,
¿La verdad?: hay poco tiempo, y por lo que comenté acá (*), no se si valga la pena invertir más tiempo en este plugin.
(*) lectura: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/234#issuecomment-1036572654

Eso mismo es lo que te (nos) afecta cuando una localidad aparece sin servicio.

Lamentablemente Chilexpress ya no está soportando la vieja API WSDL, y no hay mucho más que podamos hacer, como expliqué en aquel enlace anterior.

Considerando que Chilexpress tiene su plugin oficial ahora, aunque de pago (como se explicó ahí también), y la API WSDL cada vez va a ser menos efectiva (cae, no entrega resultados, no está actualizada, faltan ubicaciones, puede no entregar el mismo valor que la nueva API, etc)... creo que no es sano que les recomiende seguir usando este plugin en producción.

Quizás, quizás, ha llegado el tiempo de dar de baja este plugin oficialmente.

¿O no?

**Comment by TCattd** [comment]
Ping a @PatrickCaneloDigital que ha sido alguien que, a lo largo de los años, ha ayudado bastante por acá (gracias por eso).

**Comment by PatrickCaneloDigital** [comment]
@TCattd:
Si, los puntos que mencionaste los comparto, inclusive el poco tiempo para seguir desarrollandolo.

Sobre todo los puntos mencionados en este request, me los he topado también y probablemente habría que rediseñar el tema de como manejar comunas y regiones y eventualmente la seleccion del metodo de envio, para adaptarlo a las nuevas versiones de wordpress/woocommerce (a la rapida sospecho que por allí surgen los problemas mencionados)

De mi perspectiva optaria a dejarlo configurado de fijo con la API Rest (Alli asumiendo que la API DEV devuelve valores reales) y dejar el plugin sin soporte.

Efectivamente me faltaría también el tiempo para poner el plugin bien al día (creo que haría falta un rediseño bastante de a fondo para dejarlo funcionando y aun así estarían allí los problemas que tu mencionas: API WS/WPI Rest y posibles diferencias de datos DEV/PROD (aunque este ultimo item creo que no es un peligro agudo, la pagina de developers.chilexpress ofrece dentro de su funcionalidad esas opciones para pruebas de integración, etc. Los problemas WS deben nacer netamente del hecho que les urge cambiar todos los usuarios a REST y asi fuerzan la descontinuacion y segun mi experiencia botaria en un rediseño esa opcion, porque en cualquier momento la pueden cortar)

**Comment by TCattd** [comment]
@PatrickCaneloDigital buenas. El problema de dejar apuntado por default a la API REST, es que no todos tendrán acceso a crear llaves para eso y usarlas en producción.

A estas alturas, considerando el plugin oficial de Chilexpress, creo que la implementación REST en este plugin es más opcional que oficial.

Creo que es tiempo de planificar el fin del soporte de este plugin. No veo el sentido de continuar, mucho menos sin tener la opción de poder "competir" de igual a igual con Chilexpress, sin contar con el acceso a probar la API REST en producción (sin tener que pagarles, cosa que no tengo intención de hacer).

Voy a crear otro hilo acá para conversar al aire el como hacerlo.

**Comment by TCattd** [comment]
@PatrickCaneloDigital https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/246

**Comment by PatrickCaneloDigital** [comment]
Disculpa la demora en contestar.
Me parece planificar el fin de soporte, aunque en respecto a Rest o WS discrepo en el sentido que: 
- Si bien con REST no hay acceso a la APi de producción, la implementación DEV (donde si se pueden adquirir las llaves) creo que sigue siendo mejor alternativa que dejarlo sin soporte con WS PROD, ya que como vimos, la calidad de datos está disminuyendo en esa API y sospecho que la calidad de la API Rest DEV sigue siendo mejor, y el salto a PROD no sería tan grave (definiciones de los servidores PROD Rest me las entregó un cliente en su momento)

Ahora para no rompernos el craneo nosotros, se podría dejar esa consulta abierta para el otro hilo y definir allí como dar el fin de soporte.

Pero claro está que si no aparece un patrón/esponsor, que esté dispuesto a financiar la actualización de los mayores pendientes, claramente hay que dar fin al soporte.
A mi me encantaría mantenerlo vigente, pero no estoy en situación en el momento para poder invertir el tiempo necesario de mi propio bolsillo/tiempo libre.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
