### ISSUE TITLE
Hubo un error: Invalid Request

### ISSUE THREAD

**Issue by Nicoore90** [whooohq/whq-woocommerce-chilexpress-shipping#249]
Hola!! Estoy instalando el plugin de chilexpress para uno de mis clientes y cuando quiero probar hacer un pedido me aparece el error del titulo. Ya segui todas las indicaciones de este instructivo https://github.com/whooohq/whq-woocommerce-chilexpress-shipping#problemas-generales-visuales-glitches-yo-funcionales-en-el-carro-o-finalizar-compra-checkout y sigue sin funcionar.

Adjunto imagen del error.

![image](https://user-images.githubusercontent.com/76071926/195714891-d401e930-73db-4e59-bd9b-02e4c52198a8.png)

**Comment by TCattd** [comment]
Estimado,

Consulta, ¿leíste esto? https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248

Es probable que la vieja API de Chilexpress haya estado abajo en el momento en que intentaste probar el plugin.
No podemos saberlo.

Lo relevante acá, es que este plugin tiene fecha de término, y no recomendamos para nada su uso en producción.
Como se comenta en el mismo mensaje enlazado acá, si Chilexpress decide dar de baja su API SOAP antes del plazo que nosotros entregamos de soporte para este plugin, tampoco podemos hacer nada al respecto. Lamentablemente, nada.

Lo siento, estimado. Revisa por favor las alternativas entregadas ahí mismo en el mensaje: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248

Gracias.
