### ISSUE TITLE
Error: array_key_exists() luego de activar el plugin

### ISSUE THREAD

**Issue by masterbip** [whooohq/whq-woocommerce-chilexpress-shipping#25]
Error luego de activar el plugin
https://www.awesomescreenshot.com/showImage?img_id=2706304

Warning: array_key_exists() expects parameter 2 to be array, boolean given in /home/tumallon/public_html/wp-content/plugins/woo-chilexpress-shipping/classes/WC_WHQ_Chilexpress_Shipping.php on line 117

Repetido 5 veces en mi admin.
SOAP esta habilitado.
Que puede ser?

**Comment by masterbip** [comment]
He deshabilitado dos plugins:
- WooCommerce Chilean Peso + Chilean States
- Woo Checkout Field Editor Pro

Ahora el error desapareció y el sistema funciona mejor que a la perfeccion.

FA-BU-LO-SO !!!!

**Comment by TCattd** [comment]
Bueno saberlo.

Como referencia:
Mantengo una instancia de WordPress limpia para desarrollo. Solo con estos plugins instalados y corriendo: Transients Manager, WooCommerce, y WooCommerce Chilexpress Shipping lógicamente. Y el theme Storefront de WooCommerce.

Con esa instancia limpia, los pesos Chilenos igual aparecen en WooCommerce: http://prntscr.com/g3hkhi no es necesario agregar ningún plugin para obtenerlos.

---

Respecto a https://wordpress.org/plugins/woocommerce-chilean-peso-currency/

Entiendo que WooCommerce inicialmente no los tenía, pero hoy, WooCommerce 3.x, si tiene los CLP integrados en el core.

Ahora, me parece que aquel plugin hace algo más (cambio de moneda CLP a USD para pagar con dólares), pero... creo que es algo que Cristian debiera ver (el desarrollador del plugin aquel).
El agregar los CLP a WooCommerce está de más hoy; viene en el core. El auto-convertir de CLP a USD para pagar con dólares (PayPal) es algo que podría ser util por cierto, pero me parece que debería ser un plugin aparte, o con otro nombre, ya que WooCommerce ya agrega los CLP por default.
No se si me explico.

Lo de agregar las regiones (en aquel plugin) también es algo que dentro del contexto del CLP está "de más". Bienvenido es, sin duda, pero... podría ser una opción.

Como comenté acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/19#issuecomment-317432138 el que debamos agregar nosotros valores fijos para la región y ciudad es un efecto colateral de la necesidad de la API de Chilexpress de usar esos valores fijos y sus códigos siempre.

No podríamos calcular el costo de envío, si alguien coloca "biobio" en caso de referirse a la octava región, o incluso "8va región", o el sin fin de formas de escribirlo: "octava", "octava región", "octava region" (sin tilde), "8va", "8va región", "biobio", "bio-bio", "bio bio", etc. Chilexpress requiere que esos campos (región y ciudad) lleven un formato específico. Por esa necesidad es que el plugin nuestro los pre-completa con los valores permitidos por Chilexpress.

---

Respecto a Woo Checkout Field Editor Pro https://wordpress.org/plugins/woo-checkout-field-editor-pro/

Es este mismo reporte, si no me equivoco: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-316447919

¿Es ese mismo plugin, estimado? ¿O es otra versión de otro Checkout Field Editor?
Pregunto, porque hay varios plugins que hacen lo mismo. Incluido el oficial de WooCommerce.
De todos modos el reporte de incompatibilidad corre igual, si llegaron a remover (por ejemplo) el campo de país dentro del checkout de WooCommerce.

No es recomendado, como los mismos desarrolladores comentan: http://prntscr.com/g3hpqc porque saben que eso genera problemas en otros plugins (no solo nosotros).

---

Lanzada una actualización con un checkeo para el error que mencionas en nuestro plugin.

Agregado aviso de incompatibilidad con el plugin https://wordpress.org/plugins/woocommerce-chilean-peso-currency/

¡Gracias por el reporte, estimado! ;)

**Comment by masterbip** [comment]
Al contrario gracias a ustedes. Efectivamente antes Woo no traia pesos chilenos por defectos hasta estas ultimas versiones, por lo que de a poco estoy actualizando instalaciones/proyectos... y tambien sacandolo de mi sistema pues por defecto siempre lo instalaba junto con woo.

Gracias a ustedes nuevamente. Un aporte del tamaño de un  granito de humilde arena pero un saco lleno de agradecimientos por este plugin tan necesario para nosotros.

Saludos!

**Comment by fluido21** [comment]
Muchas gracias por este magnifico plugin!!! un gran paso.
estoy probandolo en mi tienda, con el theme shopkeeper. 
clp pluging desinstalado y form fields editor tambien... me funciona bien cuando se trata de despachar a la direccion de facturacion, pero cuando haces click en la opcion de despaco a otra direccion, ahi solo carga la region pero el campo de ciudades queda en blanco por lo tanto el valor total de la orden no se actualiza... o sea no agrega ningun valor de envio...

alguna idea de que puede estar pasando? 
de antemano muchas gracias!! 
![screen shot 2017-08-05 at 12 49 54 am](https://user-images.githubusercontent.com/30326298/28994972-0839fdc2-7978-11e7-933e-517b4486f8f4.png)

**Comment by TCattd** [comment]
@fluido21 por favor, abre otro issue con tu problema (que no tiene que ver con el problema reportado originalmente acá).

E incluye tanto detalle como sea posible. Versión de WP, versión de WooCommerce, versión del plugin nuestro instalada, theme utilizado, si probaste o no con el theme storefront, y lista de plugins instalados.

Por favor.
