### ISSUE TITLE
problema con algunas localidades

### ISSUE THREAD

**Issue by brcl17** [whooohq/whq-woocommerce-chilexpress-shipping#26]
hola que tal, es normal que en algunas localidades no me calcule el precio?, si es problema de chilexpress puedo borrar directamente del código las localidades con problemas?, saludos.

(adjunto captura de pantalla)
[http://i65.tinypic.com/99neyr.png](url)

edit. https://preview.ibb.co/j0NXWa/clxps.png

**Comment by TCattd** [comment]
Estimado

¿Última versión de WP instalada?
¿Última versión de WooCommerce instalada?
¿Última versión del plugin nuestro instalada?

¿Tienes una URL donde poder ver el problema en vivo?. Si quieres entregar datos en privado, mail: esteban arroba actitud.xyz

¡Gracias!

**Comment by TCattd** [comment]
Recibido el mail, estimado. Continuamos ahí. Dejo abierto para comentar luego que ocurrió.

**Comment by TCattd** [comment]
En la RM, las ubicaciones que presentan problemas y no calcula el envío:
```
calera de tango
el monte
enea express
isla de maipo
internacional
la granja
la pintana
padre hurtado
san ramon
til til
cerro navia
```

Esto gracias a @brcl17 (por mail).

Voy a tener que revisar en local si esto pasa o no en la copia limpia.

**Comment by brcl17** [comment]
Revise las demás regiones y esto encontré

Región Antofagasta
Sierra gorda
Tocopilla
Maria Elena

Región de Atacama
Tierra Amarilla

Región de Valparaiso
El Tabo

Región de O'higgins
San Francisco de Mostazal

Región del Bio Bio
Coihueco
San Rosendo
San Ignacio

Región de Los Rios 
Lago Ranco

Región de Los Lagos
Puyehue
San Pablo

**Comment by TCattd** [comment]
Resulta que el problema es porque los costos dependen de la ciudad de origen desde donde se realiza el envío y el destino a donde va el paquete.
Dependiendo de la combinación (origen/destino), Chilexpress podría o no tener disponible alguno de estos envíos: Ultra Rápido, Overnight, Día hábil siguiente, Día hábil subsiguiente, Tercer día.

Ese era el impedimento en muchas ubicaciones, por la condicional ciudad de origen de los envíos y el destino.

Dicho eso, no creo que sea seguro remover localidades.
Esto afectaría a usuarios cuyas tiendas, por ejemplo, estén ubicadas en esas zonas o en otras zonas "extremas" del país, donde no hay envíos normales de Chilexpress (día hábil siguiente).
Teniendo en cuenta que esas localidades existen en el cotizador de http://www.chilexpress.cl/cotizador-envios-de-encomiendas-tarifas creo que están ahí por algo. Si la API de Chilexpress las retorna, para algo será.
Nunca podré estar seguro, porque no trabajo con ellos como he comentado en otros issues anteriores.

Lo que hice fue expandir el sistema de envíos, para no dejar fijo el tipo de envío "día hábil siguiente". Al haber dejado fijo solo ese tipo de envío, algunas combinaciones origen/destino no entregaban valor para ese servicio (porque no se encuentra disponible por razones obvias, geográficas) y Chilexpress aparecía como sin valor en el plugin.

Ahora tomamos el valor de los servicios entregados por Chilexpress, y los mostramos todos (los disponibles para el combo origen/destino): http://prntscr.com/g8cwf1

Y si no hay servicio, mostramos el mensaje que la API de Chilexpress devuelve: http://prntscr.com/g8db5e
Evitando que los usuarios puedan seleccionar esa opción.
(Como dije, desconozco el motivo por el cual la API de Chilexpress responde así en ciertas circunstancias, y la documentación no lo menciona, por lo que no puedo darles una mejor alternativa acá)
 
Además, los tipo de envíos habilitados los pueden configurar ustedes mismos en las opciones del plugin: http://prntscr.com/g8cwzm
Ahí seleccionan los que desean soportar en sus tiendas.
Ojo con el texto en la opción, leer bien antes de tomar una decisión.

Con esto no deberían tener inconvenientes con localidades extremas o lejanas a la ciudad de origen desde donde envían los productos de sus tiendas. Y si los hay, aparecerá "sin servicio" (lo que la API de Chilexpress retorna) en el frente indicándole al usuario que no podrá utilizar Chilexpress.

Va el update en unos minutos. Espero les sirva, estimados.
Buen día ;)

Esteban
