### ISSUE TITLE
Plugin Chilexpress no funciona

### ISSUE THREAD

**Issue by arturojao** [whooohq/whq-woocommerce-chilexpress-shipping#27]
Estimados, la última actualización del plugin no funciona en mi sitio. Desactive WooCommerce Fiel Editor Pro y nada. Dice "Chilexpress no se encuentra disponible por el momento. Por favor intente más tarde." Adjunto pantallazo.

Favor su ayuda!
www.dobletraccion.cl

Arturo
[pantallazo.pdf](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/1219162/pantallazo.pdf)

**Comment by TCattd** [comment]
Estimado,

Aquel error que ves es mostrado cuando tu servidor no puede contactar a la API de Chilexpress.

Si no se puede contactar a la API de Chilexpress, por cualquier motivo, se evita que los usuarios puedan seleccionar Chilexpress, para no permitir cobros de envío que no sean ajustados a la realidad.

La verdad es que puede ser que la API de ellos (Chilexpress) esté momentáneamente abajo.

Pero también puede ser que tu servidor haya pegado en algún límite o throttle temporal que hagan ellos automáticamente en caso de muchos requests seguidos a la API.

Lo menciono porque veo vuestro sitio está en modo de pruebas; avisas dentro que las órdenes no se procesan por estar en modo de prueba, y entonces es posible que algo así haya ocurrido si estabas haciendo muchos ensayos seguidos, solicitando múltiples combinaciones de envío (región, ciudad, múltiples productos) para ver el resultado.

Lo comento porque me ha pasado en el entorno de desarrollo. Cuando abuso haciendo solicitudes a la API de ellos, el servidor deja de responder, pero solo a mi. Muy seguro, puesto que desarrollo esto de forma local, con un dominio y un tld que no existen. Y en momentos en que deja de responder, en otro dominio donde el plugin está en vivo, este continúa funcionando sin inconvenientes.

Es por este motivo que el plugin guarda un caché de algunos días de la información que se puede guardar sin afectar el precio calculado (como las regiones y ciudades). Pero el resto de la info debe continuar dinámica, o si no el plugin guardaría precios que no serían los correctos para cierto día y destino de envío.

Pueden ser algunas otras cosas, pero todo se resume en un problema de conectividad de tu sitio/servidor, con la API de Chilexpress.

Ante eso no podemos hacer nada, estimado, tal cual como lo mencionamos en las preguntas frecuentes del plugin.

Lo siento.
Acá funciona bien aún, en un sitio en vivo donde el plugin está instalado. Probado recién, y todo ok.

Si quieres puedes descargar una versión anterior del plugin y probar. Eso lo puedes hacer acá https://wordpress.org/plugins/woo-chilexpress-shipping/advanced/
Pero no te lo recomiendo.
Que no se vea ese mensaje de error no significa que el plugin está funcionando.
Si descargas una versión vieja, que no verificaba si la API estaba respondiendo o no, corres el enorme riesgo que la gente pueda comprar, seleccionar un envío por Chilexpress, y que se le cobre un monto más bajo del que debería o peor aún: que se le cobre 0 pesos, e igual puedan seleccionar Chilexpress, debiendo tu luego correr con el gasto de envío por completo.

Espero haberme explicado correctamente, estimado.

**Comment by TCattd** [comment]
Probado en un segundo sitio donde está instalado el plugin. También funcionando hoy, a esta hora.

**Comment by arturojao** [comment]
Muchas gracias por tu pronta y detallada respuesta.

Es raro porque a pesar que la pagina está en desarrollo, no funcionó desde el primer intento.

Hablaré con soporte del servidor.

 

Muchas gracias!

 

Arturo Aguirre

 

 

De: Esteban <notifications@github.com>
Responder a: whooohq/whq-woocommerce-chilexpress-shipping <reply@reply.github.com>
Fecha: viernes, 11 de agosto de 2017, 6:22 p.m.
Para: whooohq/whq-woocommerce-chilexpress-shipping <whq-woocommerce-chilexpress-shipping@noreply.github.com>
CC: arturojao <arturo.jao@gmail.com>, Author <author@noreply.github.com>
Asunto: Re: [whooohq/whq-woocommerce-chilexpress-shipping] Plugin Chilexpress no funciona (#27)

 

Probado en un segundo sitio donde está instalado el plugin. También funcionando hoy, a esta hora.

**Comment by TCattd** [comment]
;)
