### ISSUE TITLE
Problema en la actualización de las opciones y tarifas.

### ISSUE THREAD

**Issue by albetix** [whooohq/whq-woocommerce-chilexpress-shipping#29]
@TCattd,

Está sucediendo algo muy extraño. Si realizas un proceso de compra en forma anónima (utilizando ventana de incógnito para simular un nuevo usuario que recién visita la tienda y no ha comprado nunca), en el checkout no se están refrescando las opciones de envío ni las tarifas asociadas cuando cambias la región o comuna a través de los combo box respectivos. Sólo lo hace cuando uno selecciona o deselecciona el envío a otra dirección. En cambio si haces la compra como usuario registrado y logueado, funciona sin problema y refresca las opciones y tarifas en cada cambio de región o comuna.

Las pruebas las realicé tanto el Chrome como en Firefox, en forma anónima y utilizando dos sitios. El primero que es el que estoy puliendo para salir a producción (que utiliza el tema Enfold) y otro que tiene lo mismo que tu plataforma de pruebas (WP, woocommerce, storefront y el plugin).

Esto es super delicado ya que el usuario puede seleccionar una comuna con despacho barato y despues puede cambiar la región y comuna manteniendo el valor barato y colocar la orden.

**Comment by TCattd** [comment]
@albetix, primero que todo, agradecido por el PR ;)

Lo que comentas no lo puedo reproducir.
Mira:
https://www.youtube.com/watch?v=1CvjBgbAdpg
Probado en incognito, sin estar registrado. Entorno de desarrollo limpio.

Ojo que el comportamiento del video es el estándar de WC. WC no mostrará el gasto de envío hasta que el usuario coloque su dirección (y no solo la región y ciudad); me refiero a la calle y número.

Puedes ver que en un comienzo WC no muestra gastos de envío aunque selecciono la región y ciudad. Solo lo hace una vez que ingreso una dirección. Como decía, es el estándar de WC, que de verdad preferiría no modificar.

Nosotros (al menos yo acá en la prueba) estamos enfocados en probar el tema del plugin, por lo que vamos de cabeza a llenar la región y ciudad a ver si funciona, pero la verdad es que el usuario común tiende a llenar los campos de arriba a abajo, y va a partir por colocar su nombre, apellido y dirección, antes de seleccionar la ciudad y región. Hay que considerar que esos campos iniciales son requeridos por WC, por lo que nadie podrá procesar un pedido sin introducir esos datos primero.

¿Es con esto con lo que tienes inconvenientes, @albetix?

Ojo, puedes bajar la versión nueva del master acá en el repo (1.2.1, https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/archive/master.zip). Añadí un montón de logs en el javascript del plugin, que solo se ven si tienen habilitado el WP_DEBUG en el wp-config.php de WordPress, para poder "ver" lo que está haciendo el plugin en la consola de Chrome o Firefox.

Esteban

**Comment by albetix** [comment]
@TCattd  efectivamente ese es el problema. Llenando el resto de los campos funciona sin problemas. Parece que anoche, entre prueba y prueba, sólo estaba poniendo atención al comportamiento de los combo box y olvidé el contexto.

Buen cambio el que hiciste dejando sólo una función para la carga de las ciudades. Era algo que quería hacer anoche, pero ya era muy tarde y lo dejé anotado como próxima mejora.

¡Gracias por la ayuda!

Alberto

**Comment by TCattd** [comment]
Bien entonces :)
Gracias por confirmar, Alberto.

Voy a lanzar el update en breve.

Esteban
