### ISSUE TITLE
No me deja ingresar Comuna y región

### ISSUE THREAD

**Issue by Paula12345** [whooohq/whq-woocommerce-chilexpress-shipping#30]
Hola! 

Agradecería si alguien puede ayudarme a resolver este problemilla con el plugin woocommerce chilexpress. Lo instalé y modifiqué los ajustes, sin embargo al probarlo, la sección para ingresar ciudad/comuna y región queda eternamente cargando. ¿A qué se debe?

Gracias!

<img width="1363" alt="captura de pantalla 2017-08-31 a la s 15 09 44" src="https://user-images.githubusercontent.com/31518308/29938230-7b01ab84-8e5e-11e7-963c-e585d61e36b9.png">

**Comment by TCattd** [comment]
@Paula12345 , de casualidad podemos ver en algún lado la tienda públicamente?
Si no, de forma privada? (email: esteban (arroba) actitud.xyz)

¡Gracias!

**Comment by Paula12345** [comment]
Hola Esteban! Gracias por tu respuesta. Puedes ver la pagina aquí, con este producto, que es el único que tiene los parámetros de peso y volumen: http://zonacero-online.com/tienda/camaras-deportiva/camara-deportiva-dmc-ts30/

Por otro lado, ¿es posible que el error esté dado por la "API Username"? por alguna razón no me deja quitar esos datos que están allí para que funcione el sistema por defecto. ¿Sabes cómo puedo quitarlos? por más que borro y guardo los cambios, vuelve a aparece. 

<img width="1341" alt="captura de pantalla 2017-08-31 a la s 15 28 32" src="https://user-images.githubusercontent.com/31518308/29939076-10c81fb6-8e61-11e7-9ab9-db6b9733ee31.png">

**Comment by TCattd** [comment]
Estimada,

No es eso. Lo del campo de user/password de la API.
Eso que ves ahí es el valor del auto-completado de Chrome, nada más. Pero no es válido (a menos que guardes con ellos ahí puestos).

Relax.

Mira: http://prntscr.com/gfiaas
Las regiones están.

Después de seleccionar una, puedo elegir la ciudad sin problemas también: http://prntscr.com/gfiatf

El problema, me parece, es por el error de Javascript que tienes en el theme que estás utilizando.
Al haber un error de Javascript, la ejecución completa de otros eventos, incluido pero no limitado al plugin nuestro, deja de funcionar.

Lo que no se está gatillando es un proceso que de hecho es nativo de WooCommerce. Nosotros solo lo usamos, pero viene con WooCommerce, que es el uso de [BlockUI](http://malsup.com/jquery/block/). Eso es lo que usa WooCommerce para mostrar esos círculos de espera. Es lo que usamos nosotros, desde WooCommerce con una API que ellos proveen para utilizarlo, y no directamente.

Por lo que asumo que es ese error javascript en tu theme el problema; el por qué esos elementos de bloqueo de UI no desaparecen.

¿Cómo asegurarse que es eso o algún otro plugin?.

Primero, tendrías que ver de donde sale ese request a Google Maps. Si no tienen bien configurada esa API, va a seguir fallando.
No se si es el theme o es algún plugin que están usando, pero está generándoles problemas.
Podría ser un plugin para añadir mapas en el sitio. No puedo saberlo.

Lo otro sería que instales el theme "default" de WooCommerce, [Storefront](https://woocommerce.com/storefront/), y lo actives pero utilizando [este plugin (WP Theme Test)](https://wordpress.org/plugins/wp-theme-test/), de tal forma que solo un admin conectado vea el theme recién instalado y el resto de la gente siga viendo el sitio normal.
Así podrás probar la tienda con el theme que WooCommerce mismo desarrolla. Si el problema no se presenta, es algo del theme que tienen activado actualmente entonces.

Eso, estimada. Espero te sirva.
Quedo atento. Si logras descubrir que es, nos avisas por favor? Agradecidos desde ya.

Esteban

**Comment by Paula12345** [comment]
Muchas gracias, 
Haré algunas pruebas y te cuento cómo me va 👍

**Comment by Paula12345** [comment]
Hola nuevamente!

Te cuento que revisando los plugins encontré que estaba activo este: https://cl.wordpress.org/plugins/calculo-de-despacho-via-starken-para-woocommerce/

Lo desactivé y se solucionó el problema 👏  👏 


Lo único ahora, es que me quedó repetido el título de "localidad y región" y los asteriscos. ¿Sabes de dónde puede venir eso? 

<img width="1368" alt="captura de pantalla 2017-08-31 a la s 17 20 20" src="https://user-images.githubusercontent.com/31518308/29943919-b8b64c6a-8e71-11e7-977f-e986c5254f6b.png">

**Comment by Paula12345** [comment]
@TCattd  ¿Es posible que el problema tenga que ver con SOAP en mi servidor? yo solicité que estuviera activo, pero no me han informado sobre eso.

**Comment by TCattd** [comment]
Gracias por el aviso, @Paula12345 
Lamentablemente el plugin que enlazas modifica los campos de región y ciudad, cosa que nosotros también debemos hacer para poder "conversar" con Chilexpress. Chilexpress espera ciertos valores específicos de región/ciudad para poder devolver los resultados desde la API.

Vamos a añadir el plugin en el listado de plugins incompatibles: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/18#issuecomment-316447919

Sobre SOAP, no, no lo es. El plugin nuestro de hecho detecta si SOAP está instalado y activo en el servidor, y si no lo está, se muestra un aviso al momento de activar el plugin.
Puedes confirmar simplemente desactivando el plugin nuestro, y luego volver a activarlo.
Si no aparece ningún aviso al momento de activar el plugin, entonces cumples con los requerimientos (incluido SOAP).

**Comment by TCattd** [comment]
Reabre si es necesario, estimada.

**Comment by Paula12345** [comment]
Hola Esteban! 
Espero que estés muy bien. Quería hacerte una consulta, pues me había quedado pendiente el tema del los asteriscos y palabras duplicadas. 
Nosotros estamos usando el theme Salient, y la página web es esta: http://zonacero-online.com/

Quería saber si tu trabajas como freelance y pudieras hacernos una cotización por solucionar este problema. Si pudieras, puedes escribirnos a soporte@whynotmedia.cl

Quedo atenta a tus comentarios. 

![captura de pantalla 2017-10-17 a la s 15 47 24](https://user-images.githubusercontent.com/31518308/31683124-71902cec-b352-11e7-8497-f8703b055291.png)

**Comment by TCattd** [comment]
@Paula12345: esteban (arroba) actitud.xyz
Por si desean conversar.

Saludos ;)
Esteban
