### ISSUE TITLE
 Fatal error: Can't use function return value in write context in /woo-chilexpress-shipping/includes/wordpress.php on line 49

### ISSUE THREAD

**Issue by masterjpx** [whooohq/whq-woocommerce-chilexpress-shipping#31]
Hola, al activar el plugin me aparece esto: 

**El plugin no ha podido activarse porque ha provocado un error fatal.

Fatal error: Can't use function return value in write context in /home/wlfc/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 49**

No pude encontrar respuesta en los otros issues, que puede ser?

Saludos y muchas gracias!

**Comment by TCattd** [comment]
Estimado,

¿Qué versión de php está corriendo el servidor donde estás tratando de activar el plugin?

**Comment by masterjpx** [comment]
Hola, tenías toda la razón. No me di cuenta y estaba corriendo una version muy antigua, actualizé a la 56 y funciona perfecto! gracias!

**Comment by TCattd** [comment]
Lo extraño es que tenemos un checkeo de la versión de PHP en el plugin, en includes/activation.php, y debería haber parado la activación del plugin en una versión de PHP menor a la 5.6

Voy a probar en local, de nuevo, a ver si esto está funcionando.

Pensando a futuro, ya subimos el tag de compatibilidad de PHP al plugin http://prntscr.com/gjr8bp y eventualmente WordPress en el core usará eso para evitar la instalación de algún plugin que pida una versión de PHP no compatible con la detectada en el servidor.

Gracias igual por confirmar que está todo ok ahora ;)
Esteban
