### ISSUE TITLE
Select box de region bloqueado despues de actualización

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#32]
Hola, 

El plugin funcionaba perfecto hasta que decidí actualizarlo y ahora no puedo pinchar el campo "region" , está visible pero al clickear no pasa nada.

La e-store es www.carovestuario.cl 

Lo extraño es que si marco la casilla "enviar a otra dirección", sí funciona el select en este segundo formulario.

![image](https://user-images.githubusercontent.com/8575569/30299269-56261d02-9725-11e7-9b1c-e57fd565155f.png)

Alguna sugerencia?.

Saludos y gracias!

**Comment by TCattd** [comment]
Tal como ocurrió acá:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/30

Pareciera que algún plugin/theme/script está evitando que blockUI haga su trabajo. Ver: http://prntscr.com/gjzs8k

Es posible que algún plugin esté afectando el correcto funcionamiento del checkout de WooCommerce.

Esta es una URL que puedo dar http://emporioumbela.cl/finalizar-comprar/ (pueden añadir un producto primero http://emporioumbela.cl/producto/aceite-esencial-geranio-de-egipto-naturel-5-ml/ y luego pasar al checkout) donde está funcionando el plugin con la última versión de WP y WC, sin problemas, estimado.

Sugerencia: probar sin plugins que modifiquen el comportamiento default de WooCommerce, y ojo con el theme. Puedes ayudarte de https://wordpress.org/plugins/wp-theme-test/ para instalar el theme https://woocommerce.com/storefront/ y probarlo sin que nadie más que tu como admin lo vea en el frente, y salir de dudas (si es problema del theme o no).

**Comment by llermaly** [comment]
Estimado, 

Entiendo perfectamente que la culpa no es de plugin, pero igual preguntaba por si tenias algun dato.

Lo extraño es que no instalé nada nuevo, habia ocupado el plugin para cambiar el orden de los campos y me habia andado todo OK, ahora incluso lo borré y nada.

Instalar otro theme no es opción por el momento.

Solución parche: 

Repartir los campos de billing y shipping para que el envío quede en shipping.

![image](https://user-images.githubusercontent.com/8575569/30301078-c541b328-972e-11e7-95f2-14e7cb5641ba.png)

en functions.php (ocupo plugin Custom Functions para mantener el orden)

[add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
 
function custom_override_checkout_fields( $fields ) {
    unset($fields['billing']['billing_company']);
    unset($fields['billing']['billing_address_1']);
    unset($fields['billing']['billing_address_2']);
    unset($fields['billing']['billing_city']);
    unset($fields['billing']['billing_postcode']);
    unset($fields['billing']['billing_country']);
    unset($fields['billing']['billing_state']);
    unset($fields['billing']['billing_address_2']);
    unset($fields['billing']['billing_postcode']);
    unset($fields['billing']['billing_company']);
    unset($fields['billing']['billing_city']);
    
   unset($fields['shipping']['shipping_postcode']);
   unset($fields['shipping']['shipping_first_name']);
   unset($fields['shipping']['shipping_last_name']);
   unset($fields['shipping']['shipping_company']);


    return $fields;
}](url)

**Comment by TCattd** [comment]
Lamentablemente no puedo dar soporte a modificaciones de WooCommerce. Siendo uno solo, me volvería loco tratando de acomodar el plugin a cada caso.

PR son más que bienvenidos si quieren introducir una característica nueva, opcional, que arregle vuestro problema.

O si desean solicitar filtros o acciones ([hooks](https://developer.wordpress.org/plugins/hooks/)) para modificar el comportamiento oficial del plugin (indicando que quieren filtrar o donde necesitan añadir una acción), y escribir un plugin-extensión del plugin actual, para resolver vuestra necesidad, mejor aún.

Fuera de eso, no puedo hacer mucho más.
Lo siento, estimado.
