### ISSUE TITLE
Porque hay tanta diferencia de precio entre la pagina de chilexpress y el plug in

### ISSUE THREAD

**Issue by pgkh** [whooohq/whq-woocommerce-chilexpress-shipping#33]
Hola soy bastante ignorante en este tema pero no consigo que me de precios de envio razonables para el tipo de productos que estamos enviando, me da precios de $30.000 por enviar una crema a antofagasta, cuando lo hago por la pagina me da un precio de $8000 estoy haciendo algo mal?

**Comment by TCattd** [comment]
Estimado,

¿Tienes añadidos tamaño y peso a tus productos en la tienda?.
¿Configuraste correctamente la ciudad de origen de los envíos en el plugin?.
¿Añadiste algún valor a los CM extra a sumar en la configuración del plugin? ( http://prntscr.com/gk7xo9 ). Eso afecta el tamaño final del paquete que se usa para calcular el costo con Chilexpress.

¿Tienes alguna URL pública donde ver la tienda y, de paso, saber las medidas y peso exacto de un solo producto ahí para hacer la comparación con el cotizador de Chilexpress?.

**Comment by AnglDavd** [comment]
Es muy importante que los productos tengan las medidas correctas (las de la caja si es que vienen en cajas) y el peso correcto en gramos.

**Comment by TCattd** [comment]
@pgkh ¿nos puedes comentar y poner al día con tu problema?, por favor.

**Comment by misserinia** [comment]
![plugin chilexpress error](https://user-images.githubusercontent.com/32210773/30768504-8802a716-9fde-11e7-8918-fc51bb84bd83.png)
Me da exactamente el mismo error. Cuando doy la opción de envío por Chilexpress me cobra sólo el envío, no el verdadero total (producto + envío).

**Comment by TCattd** [comment]
@misserinia, creo que tu error es otro y no tiene que ver con lo que inicialmente reportaron acá.

Me parece que , en tu caso, podría ser un problema de configuración de productos variables en WooCommerce.

Fijarse que el precio de envío de Chilexpress aparece con comas como separador de miles, pero el precio del producto arriba tiene un punto como separador de miles.
Puede ser solo configuración de WooCommerce el problema ahí.

Podrían ser otras cosas las que estén afectando el precio final también.

El plugin nuestro acá es "solamente" un nuevo método de envío y, como tal, se enfrasca en los límites que WooCommerce establece para añadir un el costo de envío con la API que ellos mismos proveen. Como tal, no restan valor al producto en el carro de compras.

Ojo con eso.

**Comment by TCattd** [comment]
@pgkh reitero lo dicho antes, que también comentó AnglDavd, respecto a los tamaños (medidas) y peso de cada producto en la tienda WC. Importantísimo.

Si necesitas reabrir el issue para aportar más datos, bienvenido sea, estimado.
