### ISSUE TITLE
Problema formulario autocompletado

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#34]
Estimados,

Ya sea comprando como invitado con los campos autocompletados por chrome, o pinchando "tengo cuenta" e ingresando usuario y contraseña, cuando los campos no los relleno a mano arroja error al pinchar "Realizar el pedido" , arroja: Facturación Localidad / Ciudad es un campo requerido.

Si vuelvo a elegir region, y luego comuna puedo hacer el pedido sin problemas, pero esto un cliente no lo va a hacer.

Para descartar que sea mi plantilla probé con una de las páginas de ejemplo (http://emporioumbela.cl) y ocurre lo mismo. 

Atte

**Comment by AnglDavd** [comment]
A mi me da la impresión de que siempre trata de hacer una conexión con la API de Chilexpress y crea un conflicto con el autocompletado.

**Comment by llermaly** [comment]
Lo extraño es que el costo ya aparece calculado osea que el problema es a nivel ui solamente pienso.

Si apareciera sin servicio entonces podría pensarse que la llamada a la api solo se ejecuta en el onchange y no al cargar los select, o me equivoco ?

**Comment by TCattd** [comment]
Estimado,

Por ningún motivo emporioumbela.cl es un sitio de ejemplo, demo oficial o algo para guiarse y ver si está funcionando bien o mal.
Por favor, no lo usen como tal. Aquel sitio también puede sufrir errores por otros plugins o el theme que utiliza.

Es un sitio de un cliente de quién auspicia este plugin. Sitio público, por cierto, pero NO un sitio de pruebas, demo o ejemplo.

Habiendo aclarado eso...

¿Es esto con lo que tienes problema? ¿El auto-completado de Chrome?:

https://www.youtube.com/watch?v=FqtN1o_ceZA

En el sitio de pruebas limpio, funciona sin inconvenientes como puedes ver (si es que es eso el problema que dices tener).

Si no era eso, no entendí lo que trataste de explicar, estimado.

**Comment by TCattd** [comment]
Estimado, ¿es, lo que mostré en el video, vuestro problema?.

**Comment by llermaly** [comment]
Estimado disculpa la demora.

Me ocurre tanto cuando lo datos vienen completados en modo invitado (asumo
que es chrome quien los completa) como cuando entro logeado y vienen
completados por wordpress.

Atte.

**Comment by TCattd** [comment]
@llermaly, disculpa lo insistente, es para entender que te ocurre: ¿es lo que mostré en el video?. Por favor.

**Comment by llermaly** [comment]
Creo que si. Ya que en el video viene marcada la region y te muestra un
costo pero no pinchas "Place order" hasta que no ingresas de nuevo ciudad y
region.

A mi el formulario me aparece con todos los datos correctamente ingresados
 y costo de envio correctamente calculado (ya sea porque estoy logeado o
porque chrome guarda datos de invitado) entonces directamente pincho
"finalizar" y me dice que no he ingresado la region, por lo que tengo que
ingresarla nuevamente.

**Comment by TCattd** [comment]
👍 

Entendido, reproducido, y arreglado el problema: https://www.youtube.com/watch?v=0jzBOLxNnp8&t=0m17s

Va el update a wp.org

**Comment by dvera666** [comment]
@TCattd Estimado, me ocurre lo mismo con la versión Versión 1.4.45, pero el video ya no está disponible, ¿me puedes ayudar? gracias
