### ISSUE TITLE
Opción de dejar comunas con opción de envio gratis

### ISSUE THREAD

**Issue by masterjpx** [whooohq/whq-woocommerce-chilexpress-shipping#35]
Hola, muchas gracias por el plugin. Mi cliente entrega gratis en 3 comunas, hay alguna opción de configurar el valor de envio a estas comunas como gratis? Muchas Gracias por su ayuda.

**Comment by TCattd** [comment]
Estimado,

La verdad es que lo que pides está fuera de lo que este plugin pretende resolver.

Lo que necesitas es utilizar las zonas de envío de WooCommerce.
O algún plugin para extender WooCommerce como este: https://woocommerce.com/products/woocommerce-advanced-shipping-packages/ donde puedes configurar zonas avanzadas en base a ciertas condicionales.

Si eso no sirve, no puedo ayudarte más la verdad.
Como comenté, eso está fuera de lo que este plugin intenta resolver (ofrecer envíos vía Chilexpress).

Saludos,
Esteban
