### ISSUE TITLE
No aparece selector de comunas

### ISSUE THREAD

**Issue by draveau** [whooohq/whq-woocommerce-chilexpress-shipping#36]
Hola, 
Instalé el plugin en un WordPress con Woocommerce, y tengo el problema que no aparece el selector de comunas y regiones en el formulario de registro de la página Checkout, por tanto el plugin no puede calcular el envío.

Datos:

- WordPress versión 4.8.2
- Woocommerce versión 3.1.2
- No tengo plugins instalados que sean incompatibles con Woocommerce Chilexpress Shipping; tenía instalado "Chilean peso" pero lo desinstalé por problemas de incompatibilidad.
- En el servidor, PHP versión 7
- La plantilla WordPress es creada por mí
- URL: https://techoza.cl

Les agradeceré muchísimo su pronta ayuda.
Saludos y gracias de antemano

Daniel.

**Comment by TCattd** [comment]
@draveau 

En estos momentos, este es el error que veo en vuestro sitio: http://prntscr.com/gor2oq
Ese error ocurre cuando el servidor vuestro, por algún motivo, no puede contactarse con el servidor de Chilexpress (donde alojan la API SOAP).

Al respecto (de vuestro problema) comenté por acá: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/27
Todo lo dicho ahí aplica en este caso.

No hay sitio oficial de "prueba" para mostrar que está funcionando aún.
Pero en este sitio que NO ES DE PRUEBA http://emporioumbela.cl/finalizar-comprar/ está funcionando. Pantallazo: http://prntscr.com/gor4nk
Recalco: NO ES DE PRUEBA.
Acabo de probar en un sitio local, mi sitio de pruebas local, y funciona: http://prntscr.com/gor66p

Consejos:

Primero, usando este plugin https://wordpress.org/plugins/wp-theme-test/ o este otro https://wordpress.org/plugins/theme-test-drive/ activa este theme https://woocommerce.com/storefront/ gratuito, y pruébalo como administrador.
Descarta que no sea problema del theme que tienes actualmente activo.
Lo digo por la cantidad de errores que veo en la consola de Chrome: http://prntscr.com/gor6uy
Hay plugins que tienes instalados (según lo que dice la consola) que no están pudiendo descargar la parte javascript que c/u de ellos necesita.

Seguro, no hay plugins incompatibles instalados... hasta donde sabemos. Las incompatibilidades las conocemos recién gracias a que algún usuario (como tu) topó con algún problema con uno específico, y nos ayudó averiguándolo acá.
Es imposible para nosotros probar los miles de plugins de WordPress que existen, a mano, para determinar si generan incompatibilidad con el nuestro o no.

Dicho eso, en segundo lugar: desactiva todos los plugins, menos WooCommerce y el nuestro de Chilexpress, y ve que ocurre. Mejor aún si lo haces con el theme Storefront activado en ese momento también.

Por favor.

---

Nota aparte: creo que de verdad debería subir un sitio de pruebas para que la gente vea como funciona y si está funcionando o no aún, para casos como estos.

**Comment by draveau** [comment]
Hola Esteban,
muchas gracias por tu dedicada respuesta.

Descarté problemas del theme, tal como me lo sugeriste: desinstalé el theme actual e instalé Storefront; además de eso desactivé todos los plugins excepto el de ustedes y el de Woocommerce, y nada, sigue sin funcionar.

Lamentablemente la gente que me provee el hosting se está desentendiendo del tema, por lo cual me veo medio forzado a aprender de cosas que escapan a mi conociemiento como diseñador y desarrollador front-end para ver si es que puedo poner a funcionar el plugin.

Por lo anterior, quisiera pedirte algo de tu ayuda experta: en tu opinión, ¿qué problemas precisos de servidor podrían estar generando el no funcionamiento del plugin? ¿En qué opciones del Cpanel debiera fijarme para acercarme a resolver el problema? Sé que es una pregunta muy general, pero te agradecería mucho toda la ayuda que pudieras prestarme, la verdad este tema empieza a volverse una piedra en el zapato.

Quedo atento a ti.
Un abrazo y gracias,
Daniel

**Comment by TCattd** [comment]
Estimado,

El servidor debería poder conectarse (vía SOAP) a www.chilexpress.cl y qaws.ssichilexpress.cl:80
