### ISSUE TITLE
Comunas sin servicios

### ISSUE THREAD

**Issue by AnglDavd** [whooohq/whq-woocommerce-chilexpress-shipping#37]
Hay algunas comunas que las muestra "SIN SERVICIO" por ejemplo LA GRANJA no se si sera problema de la API o del plugin, pero me pareció buena idea mencionarlo.

**Comment by AnglDavd** [comment]
otra cosa, es posible que el orden de los campos a elegir sea diferente? quiero decir:

Primero la Región
Segundo la comuna

En ocaciones es confuso que hay que elegir primero la Región (obvio si es que no esta habilitada la Geolocalizacion) pero el campo esta debajo de la selección de la comuna.

**Comment by TCattd** [comment]
Estimado,

Sobre las comunas sin servicio y su remoción, la verdad es que alguien ya reportó ese detalle y fue conversado. Leer, por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/26#issuecomment-322225367

Relevante:
```
Teniendo en cuenta que esas localidades existen en el cotizador de http://www.chilexpress.cl/cotizador-envios-de-encomiendas-tarifas creo que están ahí por algo. Si la API de Chilexpress las retorna, para algo será.
Nunca podré estar seguro, porque no trabajo con ellos como he comentado en otros issues anteriores.
```

Sobre el orden de la región y comuna, también fue algo conversado. Ver por favor: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/19#issuecomment-317432138

Relevante:
Alterar el comportamiento default de WC más allá de lo necesario para que el cálculo de envíos de Chilexpress funcione, no es algo que persigamos. Mientras más acotados a un "método de envío" (en el marco que WC entrega como API para ellos) nos mantengamos, mejor para el funcionamiento a futuro del plugin y para evitar quebrar otras cosas (plugins, themes, otros desarrollos de terceros) como ya ocurrió.

Ahora, si alguien tiene una buena idea al respecto, bienvenido sea. Y si alguien quiere cooperar con un PR con esa idea, mejor aún :)

Saludos ;)
Esteban
