### ISSUE TITLE
No logro hacerlo funcionar

### ISSUE THREAD

**Issue by rorozamorano** [whooohq/whq-woocommerce-chilexpress-shipping#4]
Hola, instale el plug-in y no me funciona. Hay q agregar las comunas? 

Espero sus comentario.

Saludos

**Comment by jhoynerk** [comment]
Hola!, @rorozamorano podrias colocar un screenshot del problema. y ampliar información donde se origina el problema. 

Saludos.

**Comment by TCattd** [comment]
No, no hay que colocar comunas ni localidades.

Al detectar a Chile como país de envío, el plugin automáticamente trae las regiones y localidades en Chile que Chilexpress necesita (exigen un formato único para todos esos nombres, por lo que el plugin los trae desde la misma API de Chilexpress en el formato requerido).

Por eso cuando carga la página del checkout, pasa esto primero: http://prntscr.com/frynxx mientras el plugin trae los listados desde la API (hay un caché en medio para hacer que consultas sub-secuentes no demoren tanto y no pegar negativamente en la API de Chilexpress tampoco).

Luego esos dos campos se transforman en un select (con Select2 habilitado ahora): http://prntscr.com/fryos2 con los nombres que Chilexpress espera como opciones válidas para envíos.

Finalmente (una vez seleccionada localidad y región) el precio es calculado y actualizado abajo: http://prntscr.com/fryq0g

Ahora, tal como Jhoynerk comenta, sería ideal que pudieras colocar un screenshot de tu problema, o dejarnos un demo en vivo de donde estás teniendo inconvenientes, para poder mirar. Por favor.

Saludos,
Esteban

**Comment by rorozamorano** [comment]
Gracias por las respuestas.
 
El problema que tenia era en plug-in Woo Checkout Field Editor, tenia desactivada la opción país. Al agregarlo me apareció la opción de envío, ahora funciona y calcula los costos de envíos.

El único pero que tengo es que el select de comuna y región me lo tira como ultima opción http://prntscr.com/fs0643 , pero al momento de comenzar la carga del la pagina checkout los carga en el orden que corresponde http://prntscr.com/fs06po. Cual podría ser el problema?

Lo otro que en la pagina del carrito, en el calculador de envíos no me aparece http://prntscr.com/fs09wu, debiese aparecer ahí también o no?

Espero sus comentarios.

Saludos y gracias.

**Comment by rorozamorano** [comment]
Olvide comentarles que el sitio donde lo estoy implementado es www.tupolera.cl. 

Saludos

**Comment by TCattd** [comment]
Gracias por confirmar lo del problema (Checkout Field Editor). Bueno saber que lo resolviste.

Subí un update recién, debería resolver el problema de los campos de Comuna y Región cambiando de orden, y agregué una opción en la configuración del método de envío que permite no ocultar la calculadora rápida: http://prntscr.com/fs133k
El motivo está explicado en la misma opción. Es algo que falta por implementar; voy a crear un Issue nuevo pendiente para aquello.

En unos minutos debería estar disponible la actualización directamente en WordPress.org

**Comment by TCattd** [comment]
@rorozamorano me comentas, por favor, si con la actualización (ya disponible) está todo bien.

Gracias desde ya ;)

**Comment by rorozamorano** [comment]
Actualice a las versión 1.0.5 y ahora me aparecen los select de forma ordenada http://prntscr.com/fs1bgs.

La nueva opción para desactivar la calculadora de costos de envíos no se desactiva al tener la opción seleccionada, pero lo puede desactivar desde WooCommerce/Ajustes/Opciones de envío Activar la calculadora de envíos en la página de compra.

 Si quiero agregar envío gratis en la región metropolitana como podría hacerlo? ya que no hay zonas agregadas. Si agrego las regiones en las zonas como las lista el plug-in whq-woocommerce-chilexpress-shipping funcionaran ambas opciones de envío?

Muchas gracias por la ayuda.

**Comment by TCattd** [comment]
Excelente. Gracias por confirmar.

Si, hay que pasar manualmente por esa opción para ocultar o mostrar la calculadora de envío.

¿Envío gratis en Santiago?
Me imagino que desde la misma configuración de WooCommerce -> Envío -> Zonas de envío. O usando algo como esto https://wordpress.org/plugins/flat-rate-per-countryregion-for-woocommerce/ o esto https://wordpress.org/plugins/woocommerce-advanced-free-shipping/

Eso no depende de este plugin la verdad. Este plugin añade un nuevo método de envío (Chilexpress), no toca nada más dentro de WooCommerce, y no tiene que ver con un método de envío gratuito tampoco (Chilexpress no lo es).

Lo siento. No puedo ayudarte más allá con eso aquí.

Gracias nuevamente por confirmar, estimado ;)
Buen día.

Esteban
