### ISSUE TITLE
Error to active plugin  WooCommerce Chilexpress Shipping

### ISSUE THREAD

**Issue by Mlizana** [whooohq/whq-woocommerce-chilexpress-shipping#40]
When I try to active plugin  WooCommerce Chilexpress Shipping says error: Fatal error: Can't use function return value in write context in /home/infotecn/public_html/infotecnicastore.cl/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 49

Please can you help me ?

Thanks
Marco Lizana

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/41
