### ISSUE TITLE
Error al activar el plugin WooCommerce Chilexpress Shipping

### ISSUE THREAD

**Issue by Mlizana** [whooohq/whq-woocommerce-chilexpress-shipping#41]
Hola buenas tardes, instale el plugin WooCommerce Chilexpress Shipping, cuando le doy activar, me sale el siguiente error: Fatal error: Can't use function return value in write context in /home/infotecn/public_html/infotecnicastore.cl/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 49

Hasta el momento no se que pueda estar ocasionando el error, y quisiera saber si es posible que me ayudes, desde ya gracias.

Saludos
Marco Lizana

**Comment by TCattd** [comment]
Estimado,

¿Versión de PHP en vuestro servidor?

**Comment by Mlizana** [comment]
Hola la version es la 5.6 te adjunto captura de version 
![captura de pantalla 2017-10-18 a la s 09 29 01](https://user-images.githubusercontent.com/32885461/31718599-e7f82490-b3e6-11e7-9b0b-85498ace2748.png) gracias.

**Comment by TCattd** [comment]
Estimado,

Puedes entrar en tu sitio a infotecnicastore.cl/wp-admin/admin.php?page=wc-status y decirme que versión de PHP 5.6 es específicamente?

Me interesa esto dentro de esa página: http://prntscr.com/gyxz9b
Todo el bloque de server environment.

Probé instalar y activar el plugin con PHP 5.6 acá, y no tuve problemas. Por eso necesito esos datos, por favor.

**Comment by TCattd** [comment]
Ref: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/31

Por eso consulto por el output de WooCommerce a ver que versión de PHP reporta.
Si es 5.6, sería extraño de verdad.

**Comment by Mlizana** [comment]
Esteban gracias por responder, te adjunto al información.

Además te comento que ya pude instalar el plugin y activado.

Realice unas pruebas y me dice chilexpress no disponible, pero después de un rato hice otra prueba y si funciono. Después de un rato realice otra prueba y no funciono diciendo el mismo mensaje chilexpress no disponible.

Quedo atento a tus comentarios, gracias



Saludos

Marco Lizana
[cid:D13E052B-D4CF-40A8-B40E-DC68E28FB9D0]

El 18-10-2017, a las 10:32, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


Estimado,

Puedes entrar en tu sitio a infotecnicastore.cl/wp-admin/admin.php?page=wc-status y decirme que versión de PHP 5.6 es específicamente?

Me interesa esto dentro de esa página: http://prntscr.com/gyxz9b
Todo el bloque de server environment.

Probé instalar y activar el plugin con PHP 5.6 acá, y no tuve problemas. Por eso necesito esos datos, por favor.

**Comment by TCattd** [comment]
@Mlizana los adjuntos de respuestas vía email no aparecen en GitHub.

¿Puedes subir el pantallazo a imgur.com o usar [LightShot](https://app.prntscr.com/en/index.html) para compartir la imagen, por favor?

El otro problema, respondido en el otro issue que abriste.

**Comment by Mlizana** [comment]
Esteban ahí va el link con la imagen http://prntscr.com/gyyh5x

Gracias.


Saludos

Marco Lizana

El 18-10-2017, a las 10:55, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


@Mlizana<https://github.com/mlizana> los adjuntos de respuestas vía email no aparecen en GitHub.

¿Puedes subir el pantallazo a imgur.com<http://imgur.com> o usar LightShot<https://app.prntscr.com/en/index.html> para compartir la imagen, por favor?

El otro problema, respondido en el otro issue que abriste.

**Comment by TCattd** [comment]
¡Gracias!

¿Me dices que pudiste activarlo al final?
¿Hiciste algún cambio para poder activarlo? ¿Estabas usando PHP 5.4 o 5.5 antes? ¿O siempre estuvo en el 5.6?
Solo para saber. Me comentas, por favor.

De todos modos hice un cambio en la detección de la versión de PHP para tratar que esto no siga pasando a futuro. Está igualado a como WooCommerce detecta la versión de PHP ahora.

**Comment by Mlizana** [comment]
Esteban, ayer a ultima hora cambie la Version del php y pude instalarlo.

Después no cargaban las comunas y ciudades. Luego de eso y de pasado un rato si las mostraba pero el servicio decía no disponible.

Hoy en la mañana realice una prueba y si funciono ok. Después hice otra prueba y decía no disponible ahora recién hice otra prueba y funciono ok.

Te mantendré informado de su funcionamiento, muchas gracias por la preocupación y gentileza.


Saludos

Marco Lizan

El 18-10-2017, a las 11:27, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


¡Gracias!

¿Me dices que pudiste activarlo al final?
¿Hiciste algún cambio para poder activarlo? ¿Estabas usando PHP 5.4 o 5.5 antes? ¿O siempre estuvo en el 5.6?
Solo para saber. Me comentas, por favor.

De todos modos hice un cambio en la detección de la versión de PHP para tratar que esto no siga pasando a futuro. Está igualado a como WooCommerce detecta la versión de PHP ahora.

**Comment by TCattd** [comment]
Gracias por la confirmación entonces.

Espero que el cambio que hice en la detección de la versión de PHP evite este tipo de issues a futuro (ha pasado).

Saludos!
Esteban
