### ISSUE TITLE
Chilexpress no disponible

### ISSUE THREAD

**Issue by Mlizana** [whooohq/whq-woocommerce-chilexpress-shipping#42]
Hola cuando le doy finalizar compra me sale el mensaje: Envío vía Chilexpress (No Disponible)

Tampoco me muestra las comunas y regiones, revise y no tengo ningún plugin incompatible.

Que podría estar afectando?

Gracias
Marco Lizana

**Comment by TCattd** [comment]
Acá aplica lo dicho en: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/27#issuecomment-321929605

Eventualmente voy a montar un sitio de demo con el plugin para que vean si está o no funcionando correctamente.

**Comment by Paula12345** [comment]
Hola! Gracias por la información compartida, es de mucha utilidad.
Me pasa lo mismo que a Mlizana. En base a la experiencia, si hubiera un problema momentáneo de conectividad ¿en cuánto tiempo más podría volver a funcionar? 

De antemano, gracias por cualquier ayuda

**Comment by TCattd** [comment]
Hubo una vez que la API de Chilexpress estuvo caída por cuatro días (ver https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/22).

Pero eso puramente anecdótico.

Cuando ocurren problemas de conectividad, y si es que es efectivamente la API de Chilexpress la que está caída (y no son sus servidores, algún firewall en medio, un throttle de la API limitándolos por abuso, etc), no puedo saber cuando volverá.

**Comment by Mlizana** [comment]
Sí leí ese artículo. A modo de sugerencia tal vez dejar la info de chilexpress en alguna tabla temporal por un tiempo?


Saludos



El 18-10-2017, a las 11:47, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


Hubo una vez que la API de Chilexpress estuvo caída por cuatro días (ver #22<https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/22>).

Pero eso puramente anecdótico.

Cuando ocurren problemas de conectividad, y si es que es efectivamente la API de Chilexpress la que está caída (y no son sus servidores, algún firewall en medio, un throttle de la API limitándolos por abuso, etc), no puedo saber cuando volverá.

**Comment by TCattd** [comment]
La API de Chilexpress entrega valores dinámicos. No es una tabla discreta simple.

Primero, toma en cuenta el tamaño y peso del paquete.
Luego, toma en cuenta la ciudad de orien.
Después, la ciudad de destino.
Finalmente, si en esa distancia está o no disponible alguno de los envíos prioritarios, o solo disponible envío al tercer día.

¿Cómo guardar entonces combinaciones ilimitadas de peso de paquetes, tamaño de paquetes, ciudades de origen, de destino, y los tipos de envíos disponibles?

Serían cientos de combinaciones posibles (y quizás me quedo corto en el "cientos").

Kilos: 1, 1.1, 1.2, 1.3... 5, 5.1, 5,2... 9, 9.1, 9.2...
Tamaño (cm): 10, 10.1, 10.2, 10.3... 50, 50.1, 50,2... 90, 90.1, 90.2... y esto por tres (largo, alto, ancho)
Ciudad origen: 201 opciones (que pueden aumentar en cualquier momento).
Ciudad destino: 240 opciones (que podrían aumentar, no seguido, pero podría ser).

Los usuarios correrían el riesgo de que un valor X guardado no sea el que la API calcularía realmente para su paquete con el tamaño y peso que ellos definieron, con el tamaño extra que configuraron para la caja (si es que usan ese valor). ¿Quién paga el error del cálculo de envío si guardamos valores discretos que no son los que provee Chilexpress de forma dinámica?.

Es muy arriesgado.

Es por eso que el plugin se esfuerza en detectar si está caído o no Chilexpress (que puede ser un problema de conectividad de sus sitios/servidores con Chilexpress y no un problema de Chilexpress también), para evitar que la gente pueda seleccionar Chilexpress y no deban correr con un envío pagado ustedes.

Lo siento, estimado.

Pueden continuar en #22 , aunque finalmente son ustedes los que deben debugear el problema de conexión de vuestros sitios con Chilexpress. No podemos, aquí, ayudarlos con eso.
