### ISSUE TITLE
crear zonas de envío con plugin Chilexpress y Woocommerce

### ISSUE THREAD

**Issue by draveau** [whooohq/whq-woocommerce-chilexpress-shipping#43]
Hola,

He instalado el plugin Woocommerce Chilexpress Schipping, y funciona a la perfección! muchas gracias por ese "humilde" aporte de Whooo (no es nada de humilde, es absolutamente útil y necesario! :) )

Hay algo que necesito hacer, pero no sé cómo hacerlo (y no sé si se pueda hacer), y se los planteo: queremos ofrecer envíos gratis a la región metropolitana por compras superiores a $50.000, y envíos gratis a regiones de Chile por compras mayores a $100.000. 

Eso no sería problema con Woocommerce, que permite crear zonas de envío y darles la característica de despacho gratis a partir de cierto monto de compra. El problema, es que el selector que Chilexpress carga  en la página de Checkout, para que el cliente elija la región a la que quiere que se le envíe la compra, NO se carga en el backend de Woocommerce, en particular en el apartado que permite crear zonas de envío. Por tanto, no puedo crear zonas de envío en ciertas regiones y conectarlas con los selectores de comunas y regiones de Chilexpress.

¿Se les ocurre cómo podría hacerse esa conexión? y antes que eso, ¿se podrá hacer?

Quedo atento a ustedes.
Gracias y saludos!

**Comment by TCattd** [comment]
De nada, estimado.

Lo mismo (Zonas de Envío) está siendo conversado acá: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/39
Voy a mantener la conversación en ese issue, por orden.

Eres bienvenido a exponer vuestro punto de vista ahí dentro, considerando que lo que comentas es de verdad útil en ese tema.
