### ISSUE TITLE
No deja eliminar user y password

### ISSUE THREAD

**Issue by Mlizana** [whooohq/whq-woocommerce-chilexpress-shipping#45]
Hola al configurar el modulo donde indica user y password ue debería estar en blanco, me deja por defecto un user y una password, las elimino le doy guardar cambios y las sigue dejando. Además al agregar un producto no me muestra el metodo de envío, te adjunto imagenes.
Desisntale el plugin y lo reinstale nuevamente y sigue pasando lo mismo.

Gracias
Marco Lizana
![captura de pantalla 2017-10-19 a la s 13 31 32](https://user-images.githubusercontent.com/32885461/31783928-4de92962-b4d6-11e7-9071-4a3fc2da6e5f.png)
![captura de pantalla 2017-10-19 a la s 13 32 49](https://user-images.githubusercontent.com/32885461/31783929-4e09a232-b4d6-11e7-9e21-681bf7333763.png)

**Comment by TCattd** [comment]
@Mlizana 

Respecto a lo primero: eso es el autofill de Chrome, puesto que hay un input del tipo password ahí (el que guarda el password opcional para la API de Chilexpress). Que aparezca un valor ahí **con fondo amarillo** no significa que el valor del input sea ese.

La Clase de Envío no es para configurar un método de envío.
Eso es configuración de WooCommerce.

Si está activado y bien configurado, Chilexpress aparecerá en el frente del sitio, en el carro de compras y en el checkout. No en la configuración de un producto individual.

Si tienes dudas en como configurar WooCommerce, puedes consultar [la documentación de WooCommerce](https://docs.woocommerce.com/) directamente.

**Comment by Mlizana** [comment]
Hola, y gracias por responder si tenias razón revise el autofill de chrome y lo elimine y ahí pude eliminar los datos.

También revise y apareció el campo envío.

Ahora al hacer la compra aparece todo, pero dice servicio no disponible, y asumo que se debe a que todavía no refresca con la página de chilexpress, ¿ o no ?

Quedo atento, gracias


Saludos

Marco Lizana



El 19-10-2017, a las 14:44, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


@Mlizana<https://github.com/mlizana>

Respecto a lo primero: eso es el autofill de Chrome, puesto que hay un input del tipo password ahí (el que guarda el password opcional para la API de Chilexpress). Que aparezca un valor ahí con fondo amarillo no significa que el valor del input sea ese.

La Clase de Envío no es para configurar un método de envío.
Eso es configuración de WooCommerce.

Si está activado y bien configurado, Chilexpress aparecerá en el frente del sitio, en el carro de compras y en el checkout. No en la configuración de un producto individual.

Si tienes dudas en como configurar WooCommerce, puedes consultar la documentación de WooCommerce<https://docs.woocommerce.com/> directamente.

**Comment by TCattd** [comment]
Sobre tu nueva duda, esto está explicado en las preguntas frecuentes del plugin: https://wordpress.org/plugins/woo-chilexpress-shipping/#faq

Revísalas, por favor.

**Comment by Mlizana** [comment]
Ok, gracias, otra consulta saves tu si el tema mediacenter es compatible con el plugin de chilexpress?


Saludos



El 19-10-2017, a las 14:53, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


Sobre tu nueva duda, esto está explicado en las preguntas frecuentes del plugin: https://wordpress.org/plugins/woo-chilexpress-shipping/#faq

Revísalas, por favor.

**Comment by Mlizana** [comment]
Esteban buenas tardes, me podrías recomendar algún tema de tienda electrónica que sea compatible con el plugin de chilexpress por favor?

Gracias.


Saludos



El 19-10-2017, a las 14:53, Esteban <notifications@github.com<mailto:notifications@github.com>> escribió:


Sobre tu nueva duda, esto está explicado en las preguntas frecuentes del plugin: https://wordpress.org/plugins/woo-chilexpress-shipping/#faq

Revísalas, por favor.
