### ISSUE TITLE
Problemas con formulario

### ISSUE THREAD

**Issue by L0uzher** [whooohq/whq-woocommerce-chilexpress-shipping#46]
Hoy instalé el Plugins y al momento de revisar su funcionamiento me di cuenta que las regiones no despliega correctamente, cambié el tema, desactive plugin por plugin por si uno me afectaba, pero nada.
Favor si es posible ayudarme, ya que me interesa bastante poder incluirlo en mi web.

Imagen:
https://image.ibb.co/cCtxRR/22662428_10214897304488677_158614784_o.png

Web: www.laciguenastore.cl

**Comment by TCattd** [comment]
No veo el plugin activo en vuestro sitio: http://prntscr.com/gzrd0m

**Comment by L0uzher** [comment]
Tuve que desactivarlo, para que la gente no tuviese problemas al momento de comprar, de todas formas lo activo nuevamente. Saludos.

**Comment by TCattd** [comment]
Tu problema es gráfico. Css probablemente.

El formulario aparece. Se puede seleccionar la región: http://prntscr.com/gzrxvw (que es lo primero que se debe seleccionar). Y luego se puede seleccionar la ciudad: http://prntscr.com/gzryax

El problema de estilo del theme lo debes solucionar tu, estimado.
Lo siento.

Saludos,
Esteban

**Comment by L0uzher** [comment]
La solución que tengo es cambiar el width de "24px" a "100%". Favor si es posible ayudarme a cambiar esta parte.

https://prnt.sc/gzs67g

**Comment by TCattd** [comment]
Edita el archivo https://www.laciguenastore.cl/wp-content/themes/kidz-child/style.css y pon la modificación de tu CSS ahí (la que mencionaste), estimado.

Saludos,
Esteban
