### ISSUE TITLE
Calculadora de precios en el carro de compras

### ISSUE THREAD

**Issue by TCattd** [whooohq/whq-woocommerce-chilexpress-shipping#5]
Como se menciona en #4, el cálculo de gastos de envío no está implementado en la calculadora rápida de gastos que WooCommerce muestra en el Carro de Compras.

Actualmente los gastos de envío se calculan y muestran en la página de Checkout/Finalizar Compra.

Existe una opción (ahora) que permite mostrar u ocultar la calculadora desde el carro de compras https://prnt.sc/fs133k
El usuario elige al final que le acomoda en este caso (por ahora).

A futuro, lo ideal sería ver si se puede implementar el cálculo de los gastos de envío en la calculadora del carro de compras también.

La verdad no se siquiera si sea posible fácilmente, considerando que Chilexpress necesita que el usuario seleccione una región y localidad primero para poder mostrar el costo del gasto de envío, lo que implica que deberíamos colocar dos select extra en la calculadora rápida (que dejaría de ser rápida) del carro de compras, espacio que es reducido.

Ideas son bienvenidas. PR también son bienvenidos y agradecidos.

**Comment by AnglDavd** [comment]
deberia ser posible si se establece el orgen de los paquetes (direccion de la tienda) y por geolocalizacion se determinana la direccion del cliente.

**Comment by TCattd** [comment]
La geolocalización es un tema que WooCommerce ya tiene implementado por si solo, @AnglDavd , pero si no me equivoco en Chrome y Firefox, requiere que el usuario utilice HTTPS en su sitio para que dicha geolocalización funcione (no estoy seguro).

De todos modos el problema con Chilexpress es que este NO acepta cualquier dirección para estimar un precio.
Chilexpress requiere localidades, ciudades y nombres de regiones específicas para poder entregar resultados desde su API.
Es por ese motivo que el plugin reemplaza los campos de ciudad y region por unos con select2, con opciones predeterminadas.
Ante eso (los requerimientos de Chilexpress) no podemos hacer mucho la verdad.

De todos modos me parece que no es algo prioritario. Ayuda y PR son bienvenidas si alguien quiere ponerse a trabajar en eso.

Este issue de todos modos es específicamente para hacer funcionar el cotizador de precios en el carro de compras, nada más.

Sobre la demora de entrega en los precios, es por la API de Chilexpress también.
Si la API se demora en responder, no podemos hacer mucho tampoco.

Los resultados ya se a cachean por una hora en cada tienda, para las combinaciones de ciudad/región, peso y tamaño, que algún usuario haya seleccionado (y pase al checkout con ese producto).

Tampoco sería seguro cachear esos resultados por más tiempo. Precisamente porque los precios son dinámicos, y si Chilexpress decide cambiar uno, subiendo o bajando el valor, un caché de esos resultados por más tiempo no reflejaría el valor real que cobrará Chilexpress por un paquete de ese tamaño y peso por el cual se está consultando. Problema mayor para quien vende.

Me parece que no podemos hacer mucho más en ese tema tampoco, estimado.

**Comment by AnglDavd** [comment]
Pues a mi me parece que la implementacion de el plugin esta super bien, si pudiera pedir algo, seria la impresion de la etiqueta del paquete

**Comment by TCattd** [comment]
Andando.

Se viene en la siguiente actualización del plugin:
https://www.youtube.com/watch?v=ZSlcECM9Frk
