### ISSUE TITLE
Problema en la instalación

### ISSUE THREAD

**Issue by betalien** [whooohq/whq-woocommerce-chilexpress-shipping#50]
Hola!
Tengo problemas en la instalación. Cuando intento activar el plugin aparece el siguiente mensaje:

"El plugin no ha podido activarse porque ha provocado un **error fatal**."

**Fatal error:** Can't use function return value in write context in **/var/www/restbar/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php** on line **50**

Adjunto pantallazo
http://prntscr.com/h4bcdl

Por favor sería genial si lo solucionan, necesito echarlo a correr,
Gracias desde ya!!!

**Comment by TCattd** [comment]
Estimado,

Puedes entrar a tu sitio, en esta ruta: /wp-admin/admin.php?page=wc-status (es dentro del wp-admin) y decirme (o enviar pantallazo) de todo el "entorno del servidor", por favor?

(Me interesa la versión de PHP)

Gracias

**Comment by betalien** [comment]
Gracias por la pronta respuesta!!!

Te adjunto pantallazo de lo que me pides ;) 

http://prntscr.com/h4bjay

**Comment by TCattd** [comment]
Es la versión de PHP.

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/41
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/31

Como puedes ver acá http://php.net/supported-versions.php la versión 5.4 de PHP dejó de ser soportada durante algún punto del 2015.

Tienes que actualizar a la versión 5.6 de PHP como mínimo.
Está en la página del plugin aquel requerimiento de hecho: http://prntscr.com/h4c2yz

Lo extraño es que la detección de la versión de PHP que tenemos andando (que ahora es igual a la que usa WC), siga sin funcionar correctamente.
Lo voy a tener que ver.

Pero en tu caso, estimado, como dije antes solo te queda un cosa por hacer: actualizar la versión de PHP.
