### ISSUE TITLE
WooCommerce: g v/s kg y cálculo de precio

### ISSUE THREAD

**Issue by betalien** [whooohq/whq-woocommerce-chilexpress-shipping#51]
Hola! tengo duda con respecto al cálculo de valores, no sé si por problema de plugin, o la API retorna mal los datos, o tengo algo mal configurado :S

Dejo aquí las pantallas:

1) Producto utilizado en ejemplo - https://prnt.sc/h74h3h
2) Datos de envío del producto ejemplo - http://prntscr.com/h74hae
3) Configuracion Envio Chilexpress WooCommerce- http://prntscr.com/h74hpa
4) Checkout del producto ejemplo - http://prntscr.com/h75rfa
VALOR ENVIO: 8.930 (DIA HABIL SGTE)
5) Cotizacion con mismo datos en sitio Chilexpress - https://prnt.sc/h74k54
VALOR ENVIO: 2.960 (DIA HABIL SGTE)  

Si se fijan son las mismas medidas, y en ambos casos el envio y el destino es Santiago Centro.

Quedo atento y gracias desde ya por la ayuda, así como por el plugin!
Saludos!

**Comment by truchosky** [comment]
mis pesos están en kg, y funciona sin problemas, probaste ingresar 0.03 en vez de 30 ?

**Comment by betalien** [comment]
el producto estaba en 30 ya que la configuracion de WooCommerce estaba en gramos -> http://prntscr.com/h7mshb

he cambiado la configuracion de la tienda a kg, y he editado el producto como lo sugeriste -> http://prntscr.com/h7mt32

he revisado ahora el envío y me aparece el mismo valor del cotizador -> http://prntscr.com/h7mtyh
=D

Gracias por la sugerencia. 
Ha considerar, con el caso de prueba, habría un bug en el que la componente funcione con la tienda configurada en kg, y no en gramos. ya que en al parecer 30 gramos no dan el mismo resultado que 0.03 kg. 

Es un detalle que no empaña el tremendo aporte que han hecho con esta publicacion, mil gracias de nuevo.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
