### ISSUE TITLE
No se Habilita el Plugin

### ISSUE THREAD

**Issue by Babyrock2018** [whooohq/whq-woocommerce-chilexpress-shipping#52]
Estoy intentando habilitar el plugin y cuando le doy guardar no se habilita

**Comment by TCattd** [comment]
Estimado,

¿Qué error en particular te da WordPress al intentar habilitar el plugin?

Puedes entrar a esta ruta en tu sitio: /wp-admin/admin.php?page=wc-status
Eso es dentro del wp-admin.
Me dejas un pantallazo de todo el bloque de "entorno del servidor". Me interesa la versión de PHP en particular (aunque todo el resto ayuda igual).
Por favor.

**Comment by Babyrock2018** [comment]
Estimado, el PHP es de 5.6.32
![image](https://user-images.githubusercontent.com/33558347/32728870-c3df8830-c860-11e7-9f77-42ef09540b62.png)
Error Active el Plugin y no se activo:
![image](https://user-images.githubusercontent.com/33558347/32729001-247d763e-c861-11e7-8797-ece0a4e5dac6.png)

**Comment by TCattd** [comment]
El plugin está activado (dentro de WP), pero no "encendido" o habilitado desde las opciones.
Ahora entiendo el problema.

Dudas:

¿Qué pasa si cambias alguna de las otras opciones? ¿Esas se guardan? El título, el origen de los envíos, etc. Si los cambias, ¿esos cambios persisten? ¿o también vuelven a cero?.

¿Estás usando la última versión del plugin?, v1.3.6 al día de hoy.

**Comment by Babyrock2018** [comment]
Exactamente no se habilita
Respuesta a tus dudas: Las opciones Vuelven a Cero 
La version del plugin  1.3.6

**Comment by TCattd** [comment]
¿Te pido un favor?

Puedes desactivar el plugin, y luego borrarlo, pero así: http://prntscr.com/h9x3nj
Exactamente así.

Eso debería gatillar la rutina de limpieza del plugin, y remover todas las opciones que tiene en la DB.

Luego de borrado, vuelve a instalar el plugin, y ver si todo funciona correctamente en la configuración.

Por favor.

**Comment by Babyrock2018** [comment]
Proceso tal cual me comentate y al intentar habilitar el plugin no se activa 
![image](https://user-images.githubusercontent.com/33558347/32735043-77e07b12-c872-11e7-9950-c490d15b6b08.png)

**Comment by TCattd** [comment]
Que extraño.

¿De casualidad utilizas algún plugin de caché para WordPress?
Alguno que pudiese cachear la tabla wp options.
W3 Total Cache, Batcache, WP Rocket, u otro?

De nuevo, dentro de /wp-admin/admin.php?page=wc-status ¿Me puedes entregar el listado completo de plugins activos en tu instalación de WordPress?, por favor.

**Comment by Babyrock2018** [comment]
No ninguno de ellos, solo uno de optimizacion de css y jquery
Resultado:
![image](https://user-images.githubusercontent.com/33558347/32735879-bfa12788-c874-11e7-87bb-ee98c92dcd8c.png)
![image](https://user-images.githubusercontent.com/33558347/32735890-c8f959c2-c874-11e7-9cc3-2e5c20f6894c.png)

**Comment by TCattd** [comment]
Oh, esos son un montón de plugins en una sola instalación de WP :)

Estimado,

Hice lo siguiente recién.
Abrí Local by Flywheel. Cree una nueva instancia de WP, desde cero y limpia. Con tu misma configuración de servidor como base: http://prntscr.com/h9zrwh
Vía el wp-admin de ese nuevo WP, instalé WooCommerce y el plugin, directo desde el repo de WP.org
Activados ambos plugins. Y no puedo reproducir tu problema.

Ver: https://www.youtube.com/watch?v=SenXosMPhQY

¿Qué creo que es?.
La versión de WooCommerce y/o WordPress.

La de WordPress no es tan vieja, y debería ser compatible con WC igual. El pero es que tienes varios parches de seguridad en las últimas versiones 4.8.x de WP, que deberías aplicar.

Creo que el culpable principal es la versión de WC.
Es extremadamente vieja. Y como dice el header del plugin http://prntscr.com/ha00mg esta extensión requiere al menos WC 3.0 o superior.

Te expones a varios problemas de seguridad si no actualizas tu versión de WP y otros plugins dentro de el, estimado. Ojo con eso.

Prueba actualizando WC (y WP si puedes), por favor.

**Comment by Babyrock2018** [comment]
hola exactamente era eso pero ahora no me da las tarifas al pagar
![image](https://user-images.githubusercontent.com/33558347/32855155-bd440ada-ca1f-11e7-9e14-7e113b4ee1c6.png)

**Comment by TCattd** [comment]
Pasos a seguir, estimado:

1.- Descartar que no sea otro plugin el problema.
Desactiva todo plugin menos WooCommerce y el plugin de Chilexpress.
Luego vuelve a probar.
Si funciona, entonces ve activando los plugins uno a uno, verificando que funcione la entrega de precios, hasta que des con el plugin con conflicto. Y nos avisas acá, por favor, para ver si puedo duplicar el problema acá en local.

2.- Descartar que no sea tu theme el problema.
Instala este https://woocommerce.com/storefront/ es gratuito, activas y pruebas nuevamente.
Si funciona con aquel theme, entonces el problema está en el theme que estabas utilizando.

Gracias por confirmar el error de la activación (WooCommerce muy viejo).
En una de esas, podría colocar una verificación a la versión de WC en el plugin durante la activación, para evitar que corra en un WC muy viejo.
Lo voy a tener en consideración.

Saludos,
Esteban
