### ISSUE TITLE
Envío vía Chilexpress (SIN SERVICIO)

### ISSUE THREAD

**Issue by davecast** [whooohq/whq-woocommerce-chilexpress-shipping#53]
Solo quisiera saber cuando ale así SIN SERVICIO que significa ? Muchas gracias de ante mano.

**Comment by TCattd** [comment]
Tal cual como dice, estimado. Chilexpress, por algún motivo, no ofrece servicio desde el origen configurado en vuestra tienda, y hacia el destino seleccionado por el usuario.

En ocasiones la API de ellos puede responder "sin servicio" si están con algún tipo de problema; cuando eso ocurre, la verdad, escapa de lo que nosotros podemos hacer al respecto.

Espero haber aclarado la duda.

Esteban
