### ISSUE TITLE
Problema selección Tipos de Envios

### ISSUE THREAD

**Issue by alpachino23** [whooohq/whq-woocommerce-chilexpress-shipping#54]
Instalé la aplicación sin ningún problema, pero al momento de hacer una compra, sólo me muestra el Tipo de Envío "Día Habil Siguiente", siendo que tengo 3 métodos de envíos activados. Pensé que el error era que sólo estaba mostrando el primer método de la lista, por lo que sólo dejé el método "Tercer día", pero ahora me dice que "No hay métodos de envío disponibles". Esto me pasa con todas las comunas que seleccione.

De antemano gracias por la ayuda.

Saludos

**Comment by TCattd** [comment]
Estimado,

Es la API de Chilexpress la que decide que métodos de envío mostrar, e ignoro cuál es la lógica que usan para decidir que método no ofrecerán en ciertas ocasiones.

La opción que dimos está orientada básicamente a si ofrecerán el servicio overnight **siempre y cuando esté disponible** para el tramo que debe recorrer el paquete, según el origen de los envíos y el destino del paquete.

Me explico.
Si tu origen es Santiago y el envío va a Rancagua, es altamente probable que exista un envío overnight, por el tramo (es corto). Aunque no puedo estar 100% seguro, porque no trabajo en Chilexpress. Puedo asumir si que será el caso y habrá un servicio ultra expreso para esa distancia.

Al otro lado de la moneda, tienes un caso donde tu tienda está en Arica, y alguien compra desde Punta Arenas. Por ningún motivo creo que Chilexpress de la opción de envío overnight, y ni siquiera uno para el día hábil siguiente. Es probable que lo único que puedan ofrecer sea para el "tercer día" (el de espera más extensa que tienen).

La opción que tienen en la configuración finalmente tendrá que ser tratada con cuidado, según cuál sea la ubicación de su tienda (origen, desde donde harán los envíos).

No se si fue buena idea dejar que configurasen todos los tipos de envío, si al final el único que deberían considerar activar o no es el overnight... pero está, para que tomen la decisión ustedes como dueños de las tiendas.
En caso que decidan habilitar el mostrar un envío prioritario, tendrán que dejar el paquete del cliente de inmediato en una sucursal de Chilexpress, puesto que el ultra rápido necesita ser entregado hasta las 11 am, y el overnight hasta las 19 horas (ver http://www.chilexpress.cl/tiempos-de-entrega-envios-paquetes-documentos url que está enlazada en la configuración del plugin de hecho).

Otros casos son en los que Chilexpress ofrece el "día hábil siguiente". Si lo ofrece, entonces la API no ofrecerá el "tercer día".
Por eso la selección del tipo de envío en la configuración del plugin es múltiple, y por lo mismo la opción por default que viene es la recomendada: http://prntscr.com/hfvvoe
A menos que quieran ofrecer overnight o ultra rápido, y lidiar con clientes que pidan fuera o justo en el tope de horario de esos tipos de envío, y luego les reclamen a ustedes por no cumplir con el periodo de envío.

Todo eso deben tener en cuenta al configurar esa opción.

Pero está bien, no es un error. Así funciona.

Saludos,
Esteban

**Comment by alpachino23** [comment]
Gracias por la respuesta.

Después me metí a la página de Chilexpress y me di cuenta que en ninguna de las simulaciones que hice, están ofreciendo al tercer día habil, sólo al día siguiente, independiente si el despacho es en Santiago o en Arica.

Mi problema principal no es que quisiera ofrecer Overnight, sino que por el contrario, quiero ofrecer al Tercer día Habil, ya que aun no tengo la capacidad de hacer todos los días el despacho, por lo que necesitaba que el cliente no tuviera le expectativa de que recibiría su paquete al día siguiente de realizar la compra.

Finalmente lo resolví agregando un texto en la opción del despacho, para así manejar las expectativas del comprador.

Nuevamente muchas gracias por las aclaraciones.

Saludos,

Alvaro

**Comment by TCattd** [comment]
👍
