### ISSUE TITLE
No puedo activar el plugin

### ISSUE THREAD

**Issue by vsbnjmn** [whooohq/whq-woocommerce-chilexpress-shipping#55]
Hola, he intentado activar el plugin en 3 sitios diferentes y me arroja el siguiente error:

Fatal error: Can't use function return value in write context in /home/cramila/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 50

**Comment by TCattd** [comment]
Estimado,

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/50

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/40

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/31

El plugin requiere PHP 5.6 o superior.
Es altamente probable que si estás teniendo el mismo error que aquellos otros issues, tu problema sea el mismo y la solución igual:
Debes actualizar la versión de PHP de vuestro servidor.

Saludos,
Esteban

**Comment by vsbnjmn** [comment]
Efectivamente era la versión de PHP. Muchas gracias.
