### ISSUE TITLE
Como activar SOAP en servidor

### ISSUE THREAD

**Issue by deibeatx** [whooohq/whq-woocommerce-chilexpress-shipping#56]
Existe algo facil para activar SOAP en el servidor?

me aparece:
El plugin requiere la extensión SOAP para poder conectarse a Chilexpress. Por favor, activa SOAP en tu servidor.

**Comment by TCattd** [comment]
Lamentablemente no puedo ayudarte ahí (acá), más allá de donde el plugin te lleva. Al manual de PHP. Ahí tienes un item con la instalación de SOAP: http://php.net/manual/en/soap.installation.php

La instalación de SOAP generalmente dependerá del servidor que tienes. Por ejemplo, en el caso de CentOS: https://stackoverflow.com/a/26879589/920648

Como ves, es algo que debes habilitar en tu servidor, en la instalación de PHP.

Saludos,
Esteban
