### ISSUE TITLE
Calculo de envío

### ISSUE THREAD

**Issue by vsbnjmn** [whooohq/whq-woocommerce-chilexpress-shipping#57]
Estoy teniendo por el momento un problemita en el calculo de envíos, el plugin había funcionado perfecto, pero en estos momentos no me está tomando el envío 'mas barato', sino que al parecer un paquete que pesa más (no están configurados los pesos de los productos, así que por omisión debería tomar el mínimo)
Por ej en Envíos dentro de RM debería calcular 2960 y aparece 3256

**Comment by vsbnjmn** [comment]
Ahora está cobrando un poco más todavía. La comuna seleccionada es Estación central y la de base es santiago centro.
![capture](https://user-images.githubusercontent.com/34044268/33560322-31114f86-d8ee-11e7-9a66-560702514bd8.PNG)

**Comment by vsbnjmn** [comment]
Al parecer Chilexpress subió sus precios (estoy cotizando de forma manual en el sitio web). Pero el plugin no está entregando valores en los chekout.

**Comment by TCattd** [comment]
Estimado,

Claramente estás haciendo algo que no es soportado, no solo por el plugin, si no que ni siquiera por Chilexpress mismo:
http://prntscr.com/hjiu9w

Si en el FAQ del plugin se aclara que los productos DEBEN tener configurados tanto peso (kilos) como tamaño (cm), es porque así lo requiere la API de Chilexpress también.

Dado lo que comentas al principio, no puedo ayudarte, estimado. Lo siento.

Debes configurar esos valores (peso y tamaño) en tus productos.

Saludos,
Esteban

**Comment by vsbnjmn** [comment]
Hola Esteban,

Primero pensé que esa era la razón, pero en primera instancia el plugin calculaba de todas formas el valor del primer tramo de peso volumetrico que entrega Chilexpress. Proseguí a hacer la forma con un producto de las medidas: 0.3 grs, 2x2x5 cms. Y como resultado sigo obteniendo el valor del segundo tramo de cobro.

**Comment by TCattd** [comment]
El peso de los productos va en kilos, estimado, no en gramos. Chilexpress lo requiere en kilos. Ver https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/51

Y me parece (experiencia propia, no tengo certeza de lo que diré ni hay documentación al respecto) que de todos modos Chilexpress siempre considera 1 kilo como el mínimo para todas las encomiendas.

Lo mismo podría ocurrir para los valores alto-ancho-largo, algún mínimo forzado por Chilexpress en su API; me imagino que si quieres enviar una caja de 1x1x1 cm, Chilexpress igual te va a cobrar un mínimo por usar su servicio, y no algo proporcional al tamaño de esa caja.

**Comment by vsbnjmn** [comment]
Error mío, me refería a 0.3 kgs. Comprendo que Chilexpress cobra el mínimo, pero el plugin en este caso está calculando el valor que sigue al mínimo. En un comienzo estaba calculando perfecto los valores que entrega Chilexpress. Hace unos días no lo está haciendo. Imagino que algo cambió en la API de Chilexpress, ya que al calcular manualmente en la web de ellos los valores han cambiado.

**Comment by TCattd** [comment]
Chilexpress puede y ha subido valores antes.
A considerar: las fechas. Diciembre. Temporada alta para los envíos a todo el país, por navidad.

Y el próximo año volverán a cambiar, desde el 2 de enero: http://prntscr.com/hjj4yd

Por eso usamos la API, el cálculo lo hacen ellos y el plugin solo utiliza los valores que la API de Chilexpress reporta.
No modificamos esos valores en lo absoluto cuando llegan a WC.

**Comment by TCattd** [comment]
http://prntscr.com/hjjggc

http://prntscr.com/hjjgvq

http://prntscr.com/hjjh4r

Ambos casos con el mismo origen (Santiago Centro) y mismo destino (Estación Central).

Ignoro el porqué de la diferencia, pero es mínima (326 pesos) y a favor de tu tienda; no perderás dinero en el envío.

Lo que entrega el plugin, es lo que informa la API de Chilexpress directamente.
Si es más alto, por mínimo que sea, es porque así lo ha querido Chilexpress (ellos fijan los precios que entrega la API).

**Comment by vsbnjmn** [comment]
En lo personal estoy considerando eso como gasto de embalaje, pero me llama la atención si en un comienzo el plugin entregaba el mismo valor que Chilexpress.

**Comment by TCattd** [comment]
Entiendo.

Pero como no trabajamos en Chilexpress, y no tenemos información directa de ellos, solo podemos aceptar esas diferencias y seguir adelante.

Si es lo que la API dice y entrega, es con lo que debemos trabajar.

Espero se comprenda, estimado.
