### ISSUE TITLE
Diferencias precio cotizador vs checkout

### ISSUE THREAD

**Issue by zerosixtyfour** [whooohq/whq-woocommerce-chilexpress-shipping#58]
Estimados tengo un gran problema:

Al momento de hacer checkout el cálculo del envío se realiza, sin embargo, este no coincide con los datos del cotizador propio de Chilexpress, ni tampoco con el valor final al solicitar el envío
El plugin me da este valor: 
https://imgur.com/a/CXIgU

Sin embargo el cotizador y el precio real a pagar es este:
https://imgur.com/rS7BZ5m

Tengo la última versión del plugin y los pesos y dimensiones están configurados correctamente (en kg y cm), al parecer de todas maneras se está calculando el valor mínimo, estos son los datos para que puedan verificarlo: peso 0.1 kg, dimensiones, 7.5x9x7.5cm

Además de todo probé incluso el plugin en una instalación limpia de wordpress + woocommerce y da ese mismo valor, es posible que el problema sea del webservice de Chilexpress?

Anteriormente el precio había sido calculado correctamente, pero ahora todos los precios tienen diferencias bastante notorias, algunas a favor y otras en contra.

Saludos y si necesitan algún dato adicional estaré mirando el ticket, muchas gracias!

**Comment by TCattd** [comment]
Favor leer: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/57
