### ISSUE TITLE
Problema endpoint order-pay

### ISSUE THREAD

**Issue by maticzd** [whooohq/whq-woocommerce-chilexpress-shipping#59]
Estimados, antes que todo, muchas gracias por el plugin, es genial lo que están haciendo!!

En la página (endpoint) order-pay (https://mipagina.com/checkout/order-pay/1171/?pay_for_order=true&key=wc_order_6a9809d09a7a0)
Encontré el problema con el botón para pagar (place_order), el cual no realiza ninguna acción, es decir, al dar click no hace nada.

Mirando el código del plugin encontré una función para el evento click del elemento con id = "place_order" y es el preventDefault() el que no deja seguir adelante con el proceso.

Lo que hice fue comprobar si la url de la página contiene "?pay_for_order=true" y si no hacer el preventDefault() y el whq_wcchp_submit_check() tal como está en la función antes mencionada.

Haciendo lo anterior logré hacer que funcionara el botón de pagar en dicha página (endpoint)

Ahora, el motivo de mi publicación es dar a conocer el problema y ver si la solución adoptada es correcta o genera algún otro problema, o si existe una mejor solución.

Espero haber explicado bien el problema, y repito las gracias por el plugin.
Saludos.

**Comment by TCattd** [comment]
Estimado,

¿Qué método de pago estás utilizando en tu tienda?

**Comment by maticzd** [comment]
Transferencia directa, Paypal, khipu, webpay.

Probé desactivando los plugins de las pasarelas de pago y otros que tienen que ver con el checkout, y solo al momento de desactivar el de chilexpress volvía a funcionar el botón.

Saludos.

**Comment by TCattd** [comment]
Estimado,

Algunas pasarelas de pago saltan directamente a un servicio externo.
Webpay no.

Por eso preguntaba con cual pasarela de pago tienes problemas directamente, para poder probar acá también.

¿Webpay es una con las que tienes problemas?

**Comment by maticzd** [comment]
Con cualquiera de las pasarelas el botón no funciona, pero ojo que el problema es sólo en la página mencionada. No en la página de checkout.

Saludos.

**Comment by TCattd** [comment]
http://prntscr.com/hth1bg ¿ahí? ¿o es otro botón y/o en otra página después del checkout?

**Comment by maticzd** [comment]
https://youtu.be/iOGQvHZ7pv8 Ahí es el problema.

Espero se entienda,
Saludos.

**Comment by TCattd** [comment]
Entiendo. Gracias por el video.

El preventDefault que mencionas está ahí para evitar que la gente pueda avanzar si Chilexpress no cuenta con servicio (API caida) y si es el único método de envío disponible.
Pero el plugin debería enviar el formulario igual una vez que checkea que esté todo en orden (haciendo un submit al form principal del checkout de WooCommerce).

Te pido un favor, puedes instalar este theme https://woocommerce.com/storefront/ (gratuito), y volver a probar. Solo para descartar que no sea problema del theme que estás utilizando.

¡Gracias!

**Comment by TCattd** [comment]
Webpay funcionando sin problemas en una instalación default de WP, actualizada, con WC actualizado, y el plugin actualizado. Theme Storefront (default de WC).

Revisa vuestro theme, estimado, por favor.
