### ISSUE TITLE
Orden de regiones y comunas

### ISSUE THREAD

**Issue by rorozamorano** [whooohq/whq-woocommerce-chilexpress-shipping#6]
Existirá la forma de editar el orden de las regiones y comunas?
Por ejemplo la lista de regiones las muestras así:
TARAPACA
ANTOFAGASTA
ATACAMA
COQUIMBO
VALPARAISO
LIBERTADOR GRAL BERNARDO O HIGGINS
MAULE
BIOBIO
ARAUCANIA
METROPOLITANA DE SANTIAGO
LOS LAGOS
AISEN DEL GRAL. C. IBANEZ DEL CAMPO
MAGALLANES Y LA ANTARTICA CHILENA
LOS RIOS
ARICA Y PARINACOTA

Me gustaría ordenarlas por orden geográfico para facilitar el uso a los clientes, dejándolo algo así:
ARICA Y PARINACOTA
TARAPACA
ANTOFAGASTA
ATACAMA
COQUIMBO
VALPARAISO
METROPOLITANA DE SANTIAGO
LIBERTADOR GRAL BERNARDO O HIGGINS
MAULE
BIOBIO
ARAUCANIA
LOS RIOS
LOS LAGOS
AISEN DEL GRAL. C. IBANEZ DEL CAMPO
MAGALLANES Y LA ANTARTICA CHILENA

En las comunas se lista LOS ALAMOS como tercera opción, me di cuenta q la abreviación es 'ALAM' por eso sale en las primeras opciones, no es algo trascendente pero se los informo :D.

Saludos.

**Comment by TCattd** [comment]
Aunque tienen implementado Select2 (ambos cambios, regiones y ciudades), y es fácil buscar no importando el orden que tenga...

...resuelto:

http://prntscr.com/fsdqsd
http://prntscr.com/fsdqwo
http://prntscr.com/fsdr1h

Viene la actualización pronto.

**Comment by rorozamorano** [comment]
Excelente :D
