### ISSUE TITLE
Region drop down automatically selected but after that city can't able to set on checkout page as we have selected from cart  page

### ISSUE THREAD

**Issue by maheshvora** [whooohq/whq-woocommerce-chilexpress-shipping#60]
When i am select region and city on cart page after that chilexpress show method of shipping after selecting method i am going to checkout but on the checkout page region and shipping method will select successfully but city drop-down does not have automatic city select so i want to select city automatic on checkout page.

**Comment by TCattd** [comment]
I can barely understand you. Sorry.

Can you give a more detailed step by step of your issue?

If you can provide screenshots (or even a video, no audio, just the video) that would be really helpful.

Thanks in advance.
Esteban

**Comment by rarulitos** [comment]
Trata de decir que cuando selecciona chilexpress como método de envío con una región y ciudad en la página del carro de compras. posteriormente al ir a la página del checkout los select se le resetean. ( si es que no entendí mal)
