### ISSUE TITLE
Problema con la instalación

### ISSUE THREAD

**Issue by felmardones** [whooohq/whq-woocommerce-chilexpress-shipping#62]
Hola!.

 Tengo un problema la instalar el plugin. Al activarlo me da el siguiente error:

Fatal error: Can't use function return value in write context in /home/dospasos/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 50

Revisé el archivo pero llega hasta la línea 34.
 Me podrían ayudar a ver que puede ser el error?.

Saludos.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/55
