### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by xript3r** [whooohq/whq-woocommerce-chilexpress-shipping#63]
El plugin dejo de funcionar hace días, y estaba impidiendo que los clientes realizaran pagos por webpay... ya no sincroniza los datos con Chilexpress...

**Comment by TCattd** [comment]
Esto es probado hoy, estimado: http://prntscr.com/i7cor1
Funcionando. En vivo.

Lamentablemente, creo que aquí (en vuestro problema) aplica: https://wordpress.org/plugins/woo-chilexpress-shipping/#faq en particular la entrada "¿Chilexpress caído? (Chilexpress no disponible)".

Lo siento.

Saludos,
Esteban

**Comment by xript3r** [comment]
Si. en que version de Wordpress esta corriendo ese sitio? que en el repositorio de plugins de wordpress dice que este plugin no esta probado en la ultima version de Wordpress... Porque no dice que esta caído, simplemente arroja un mensaje de error... puede ser un error de conectividad pero 3 días seguidos es mucho... saludos

**Comment by TCattd** [comment]
WordPress 4.9.2

Que el plugin no diga que es compatible con la última versión, no significa que no lo sea.

La verdad es que para mantener ese tag actualizado y decir que el plugin es compatible con cada versión nueva por mínima que sea, ejemplo 4.9.X, hay que subir una versión nueva del plugin con un solo cambio en el archivo principal del plugin.

Lanzar una actualización del plugin y molestar s la gente que lo usa, solo para cambiar un número de 4.9.1 a 4.9.2, no creo que valga la pena. Por eso no se hace.

Al menos en el mundo de WordPress, los cambios menores (4.9.X) no traen cambios mayores a WordPress y no deberían quebrar no características del mismo WordPress y por lo mismo, ningún plugin debería dejar de funcionar si este ya funcionaba bien con la versión mayor (4.9.0).

No se si me explico.

El plugin funciona bien con la última versión de WordPress en todo caso. Por si no quedó claro.

Volviendo a lo vuestro...

Dices que cuando busca un costo, arroja un mensaje de error... ¿Cuál?.

Sobre límites de la API, creo que deberías leer completo el issue que enlaza el FAQ en torno a ese tema: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/27#issuecomment-321929605

Pon atención al tema de los límites y/o posible throttling.

Frente a eso, y no trabajando en Chilexpress, no hay mucho que pueda hacer por ti, estimado.

Lo siento.
