### ISSUE TITLE
Duplicación de País y Región

### ISSUE THREAD

**Issue by rarulitos** [whooohq/whq-woocommerce-chilexpress-shipping#65]
Al parecer el plugin genera 2 nuevos bloques que al clickearlos dicen "no results found" (ayer a la noche funcionaba el plugin pero hoy no, probablemente sea por los servidores de chilexpress o quizás el issue)

![image](https://user-images.githubusercontent.com/25890779/35771345-03e52cca-090a-11e8-8f17-9276564f9f1e.png)

**Comment by rarulitos** [comment]
![image](https://user-images.githubusercontent.com/25890779/35771364-665eeb66-090a-11e8-8ac9-93c7fb99da70.png)

imagen completa con los dos duplicados.

**Comment by rarulitos** [comment]
Por si no se entiende bien en la imágenes... en el selector de región, se ve lo que pasa normalmente (dos selectores y uno con no results found) y en el selector de país es lo que ocurre al hacer click al primero. Al parecer los selectores de abajo son los que el plugin agrega como funcionalidad en vez de utilizar el mismo selector con la nueva información.

¿Existirá alguna forma de que los selectores otorgados por el plugin se acoplen con los selectores que ya existen en el tema? En el video de prueba se ve que están integrados en uno mismo y no agrega nuevos selectores al checkout.

¡Saludos y excelente trabajo con el plugin!

**Comment by TCattd** [comment]
No ocurre en una instalación limpia de WP (actualizado), con el theme Storefront y el plugin actualizado.

Ver por favor: http://wpchilexpress.whooohq.com

Revisa vuestra instalación de WP y los plugins instalados. El theme también, importante. Si se aleja del default de las plantillas de WC, habrá problemas.

**Comment by rarulitos** [comment]
Gracias Esteban. Si, después de estar un buen rato identificando el problema efectivamente tenía que ver con mi instalación de wordpress. y lo arregle con un simple css.

Solo por preguntar, ya que no estoy seguro si abrir otro topic o algo. ¿De qué manera puedes pedir un user y pass para la API? Me imagino que de esa manera uno se puede asegurar un buen un menor nivel de caídas, ¿o es exactamente igual?

¡Saludos!

**Comment by TCattd** [comment]
Para que otros puedan resolver sus eventuales problemas, si es que es lo mismo, sería muy útil si compartes el detalle de tu problema y como lo resolviste, estimado.
No es obligación, claro, pero ayudaría mucho a la comunidad.

---

El plugin usa un usuario y password que Chilexpress entrega para las integraciones.
Que yo sepa, no entregan usuarios y passwords personalizados. Tampoco tengo claro si, en caso de lograrlo (y obtener uno propio), eso mejore problemas conectividad con el servicio de ellos.

Dicho eso, la única forma de poder conversar con ellos, es volverse cliente empresas http://portalempresa.chilexpress.cl
Ahí te entregan la documentación (aunque con el mismo user y pass que usamos en este plugin), y puedes conversar con el soporte técnico de ellos.

No hay otra forma, que yo sepa.

Esteban

**Comment by rarulitos** [comment]
Buenas Esteban,

En caso de que el plugin y tu tema no logren incorporarse de buena manera (como en mi caso) . Al parecer el plugin genera unos nuevos select debajo de los originales. (como las fotos presentadas al inicio del issue.


Adjunto el código con el que logre arreglar el issue de la duplicación de los select y no hay problema con la recopilación de la data al borrar el sobrante. ya que poseen la misma id, clases, etc.

#billing_country_field > span:last-child, #billing_city_field > span:not(:last-child), #billing_state_field > span:not(:last-child){
   display: none;
}

En mi caso como solo permite la venta en Chile, no hay necesidad de seleccionar un nuevo país.

En caso de necesitar la selección de país. Dejar el código así.

#billing_city_field > span:not(:last-child), #billing_state_field > span:not(:last-child){
   display: none;
}

Saludos.
Raul Cerda.
