### ISSUE TITLE
¿Como saber si el plugin está realmente funcionando?

### ISSUE THREAD

**Issue by rarulitos** [whooohq/whq-woocommerce-chilexpress-shipping#66]
¿Existe alguna manera de darse cuenta si el plugin está correctamente configurado, pero los servicios de API de Chilexpress están caidos?

¿O Darse cuenta que tienes mal configurado el plugin y por eso sale el envío por chilexpress como no disponible?

**Comment by TCattd** [comment]
Si funciona acá http://wpchilexpress.whooohq.com el plugin no está teniendo problemas, y el inconveniente viene de vuestra instalación de WP, plugins, servidor, conexión, otro.

(Finalmente monté un sitio para que sepan si está andando o no, y como funciona)

**Comment by rarulitos** [comment]
Muchas gracias es una buena solución al problema.

Igual no se si sea posible dejar una especie de texto o informe en la pestaña de configuración del plugin con la típica luz roja o verde si la conexión con la API de chilexpress es posible o no pueda ser una solución más amigable con los usuarios.

si no, un "probar conexión" como los plugins de SMTP podría ser otra forma.

De todas maneras, gran trabajo Esteban.

Saludos.
Raúl Cerda.
