### ISSUE TITLE
¿Cobertura extendida de Chilexpress?

### ISSUE THREAD

**Issue by rarulitos** [whooohq/whq-woocommerce-chilexpress-shipping#67]
¿Existirá una forma de agregar la cobertura extendida de Chilexpress al calculador de costes?

> 
¿Qué es Cobertura extendida?

Con Cobertura extendida puedes dar protección adicional a tus encomiendas.

Si el monto del producto que envías es superior a $50.000, puedes pagar el 1% del valor declarado de éste para tener Cobertura Extendida. Así, en caso de daño, extravío o merma atribuible a Chilexpress, serás compensado por el valor del producto efectivamente acreditado.

Si el valor declarado del producto que envías no supera los $50.000, o no deseas contratar Cobertura Extendida, sólo podremos compensarte con un tope máximo de $50.000 una vez que presentes boleta o factura.

El valor máximo de compensación para un envío con Cobertura Extendida es de $10.000.000.

>

**Comment by PatrickCaneloDigital** [comment]
estoy revisando este caso y se me ocurren varias soluciones, pero en especifico 2 (y una tercera combinada):

1) hacer un ajuste adicional que esté activo en toda la tienda y aplicar la formula de cobertura extendida a todos los pedidos en el caso que esta esté activa

2) injectar por cada tipo de envio un segundo que incluya el monto adicional mas la descripccion que es con Cobertura extendida, asi el cliente podría elegir caso por caso si requiere cobertura extendida
(tendría la desventaja que apareceria en todas las tiendas pese que las tiendas no trabajen con cobertura extendida)

3) añadir un ajuste que permita definir si la tienda quiere funcionar con esa opcion pero darle elegir al cliente final si quiere cobertura extendida o no...

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
