### ISSUE TITLE
Chilexpress (No disponible)

### ISSUE THREAD

**Issue by svenms** [whooohq/whq-woocommerce-chilexpress-shipping#68]
Al instalarlo me salía que había incompatibilidad parcial porque tenía instalado WooCommerce Checkout Field Editor. Pero al desactivar el plugin, me sigue saliendo en el checkout que el método de envío no está disponible.
¿Qué otro problema puede ser?
Mi sitio es www.chilevapo.cl

Saludos y muchas gracias de antemano,

**Comment by TCattd** [comment]
Leer https://wordpress.org/plugins/woo-chilexpress-shipping/#faq item "¿Chilexpress caído? (Chilexpress no disponible)", por favor.

Demo público funcionando sin problemas hoy: http://wpchilexpress.whooohq.com
Ver: http://prntscr.com/ii9iyf
