### ISSUE TITLE
Envío vía Chilexpress (SIN SERVICIO)

### ISSUE THREAD

**Issue by rodrigos12** [whooohq/whq-woocommerce-chilexpress-shipping#69]
Hola amigos, estoy tratando de instalar el plugin y al momento de activarlo tengo el siguiente error
" Envío vía Chilexpress (SIN SERVICIO) " he buscando mas información pero no logro dar con la solución :/

dejo capturas de pantallas de la configuracion que tengo.

cap 1 : https://i.imgur.com/aXZ43rT.png
cap 2 : https://i.imgur.com/gzQK21g.png
cap3 : https://i.imgur.com/N64FeF5.png

pd: cabe decir que el plugin esta activado, en la captura no se alcanza a ver.

no se si falta algun tipo de configuracion.
quedo atento a sus comentarios. muchas gracias.
saludos

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/53

**Comment by dabasulto** [comment]
Hola tengo el mismo problema y en la pagina de demo tampoco funciona el Plugins, como lo podría solucionar?
Saludos.

**Comment by TCattd** [comment]
@dabasulto https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/80#issuecomment-386018521

**Comment by dabasulto** [comment]
@TCattd  al llenar todos los datos del despacho sigue con el error, podrá ser API de Chilexpress?
Muchas Gracias por responder.
Saludos.

**Comment by TCattd** [comment]
Es probable que sea problema de la API de Chilexpress, como dices.
