### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /includes/ajax.php on line 31 

### ISSUE THREAD

**Issue by llermaly** [whooohq/whq-woocommerce-chilexpress-shipping#7]
Hola : Primero que todo MUY BUEN PLUGIN , gracias por compartir.

Me tira ese error al intentar activar el plugin

A alguien más le ha pasado?

saludos

**Comment by TCattd** [comment]
Estimado,

¿Versión de PHP en tu servidor? Por favor.

Te puedes ayudar de algo como esto para averiguarlo rápidamente sin salir de WordPress: https://wordpress.org/plugins/wordpress-php-info/

Gracias desde ya ;)

**Comment by llermaly** [comment]
Hola Esteban, tengo PHP 5.3, al parecer ese es el problema (cambiaron la sintaxis) . 

De qué versión en adelante debería andar OK el plugin?

Atte.

**Comment by TCattd** [comment]
Uffff.

Ojo que te expones a serios problemas con esa versión de PHP.
Mira: http://php.net/supported-versions.php
PHP 5.3 dejó de ser soportado en algún punto del 2014.

En la actualidad, la versión más antigua soportada de PHP es la 5.6
No deberías estar corriendo nada menor que aquello.

Estos son los requerimientos recomendados por WordPress: https://wordpress.org/about/requirements/
Aunque recomiendan PHP 7, la verdad es que WordPress aún funciona sin inconvenientes en PHP 5.6

Probablemente podría colocar un "stop" al momento de activar el plugin, si la versión de PHP no es 5.6 o superior.
Lo dejo pendiente para una actualización futura.

Pero si, en tu caso estimado, vas a tener que actualizar a PHP 5.6 como mínimo, por vuestra seguridad de hecho.

Buen día ;)
Esteban

**Comment by llermaly** [comment]
Gracias! , ocupo Sentora que desgraciadamente viene con esa versión y no se le puede cambiar. Probaré con VestaCP . gracias :)
