### ISSUE TITLE
Compatibilidad con WordPress Multisite Network

### ISSUE THREAD

**Issue by odayan** [whooohq/whq-woocommerce-chilexpress-shipping#71]
Hola,

Probe todo pero nunca aparecio la opcion del plugin en Ajustes de Woocommerce.

Mi proveedor de hosting me confirma que el SOAP esta instalado correctamente.
El plugin tiene version 1.3.9 que es lo ultimo.
Woocommerce tiene version 3.3.3 que es lo ultimo.
Otros plugins como mercadopago funcionan sin problema en woocommerce 

Agradezco toda la ayuda. Saludos

**Comment by TCattd** [comment]
Solo para confirmar, ¿esto es lo que no aparece?: http://prntscr.com/io1il0

Si es así, ¿qué pasa si clickeas acá?: http://prntscr.com/io1iz9 (eso en la lista de plugins instalados). ¿Puedes ver la configuración del plugin?.

**Comment by odayan** [comment]
Correcto.

Screenshot de Woocommerce: https://prnt.sc/io1lzs 

En la lista de plugins instalados no puedo ver la configuracion: https://prnt.sc/io1ml5

**Comment by odayan** [comment]
Creo que si... https://prnt.sc/io1scs

Pero la configuracion no aparece ni en el administrador del sitio, ni en la pagina web actual

**Comment by TCattd** [comment]
No he probado nunca el plugin en una red de WP.
Voy a hacerlo, estimado, apenas tenga tiempo, y reporto acá como me fue.

**Comment by TCattd** [comment]
Estimado, la versión 1.4.9 debiera resolver vuestros problemas con una red de WordPress.

Me avisas si tienes algún inconveniente, por favor. Reabres el issue nada más ;)

Esteban

**Comment by LisetteHR** [comment]
Hola, tengo el mismo problema, el plugin de Chilexpress tiene versión 1.4.21
Mi Wordpress es Multisitio y tiene versión 5.4.2 
y no aparecen los ajustes del plugin ni en el administrador del sitio, ni en la pagina web actual y no me sale la opción en los envíos de Woocomerce.
¿Qué puedo hacer?
Gracias!

**Comment by TCattd** [comment]
@LisetteHR ¿me puedes enviar los datos de acceso a tu WP, por favor?

esteban arroba actitud.xyz

¡Gracias!

**Comment by LisetteHR** [comment]
Hola Esteban,
Muchas gracias por tu respuesta.
Ya revisé en mi Cpanel y tengo activo el SOAP.

Los datos de acceso son:
www.cegostor.cl
admin
cegoStore125!

Quedo atenta a tus comentarios.
Saludos,
Lisette

**Comment by TCattd** [comment]
@LisetteHR borré tu respuesta recién.
No dejes datos de acceso en GitHub, por favor. Cualquiera puede verlos, y usarlos.

Escríbeme al correo, por favor: esteban arroba actitud.xyz

Gracias.

**Comment by TCattd** [comment]
Resuelto nuevamente. Fix en versión 1.4.22 https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/CHANGELOG.md

**Comment by thegeomaster** [comment]
Hola TCattd:

Creo que para la versión 1.4.29 de en Woocommerce v4.6.0, Wordpress 5.5.1, nuevamente no parece funcionar en ambiente multisite. Inicialmente si funcionaba cuando el sitio aún no era multisite (era una de las pruebas de funcionalidad antes de pasar a multisite), y ahora revisando la operatividad del sitio, me encontré con este incidente.

Ya revisé los plugins incompatibles, y a pesar de desactivarlos para revisar, el incidente persiste.

Espero tu ayuda

Gracias
