### ISSUE TITLE
Error al activar Plugin

### ISSUE THREAD

**Issue by Nakamura6** [whooohq/whq-woocommerce-chilexpress-shipping#72]
Hola a todos
Necesito resolver este error al intentar Activar el Plugin y desconozco como hacerlo porfavor

![123](https://user-images.githubusercontent.com/34669560/37351811-ab75abcc-26ba-11e8-8613-dca1dc683bb2.jpg)

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/55#issuecomment-347372976
