### ISSUE TITLE
Opciones "día hábil sub" y "tercer día" no funcionan

### ISSUE THREAD

**Issue by NicoMotoshop** [whooohq/whq-woocommerce-chilexpress-shipping#73]
Estimados, cómo están? Muchas gracias por este plugin, es muy útil para construir un ecommerce!

Tengo el siguiente problema y les quería consultar al respecto.

Al activar el plugin, configurando sólo la opción "día hábil siguiente", este funciona perfectamente en el carro de compras. Pero si selecciono (exclusivamente o incluyendo la primera opción) las opciones "día hábil subsiguiente" o "tercer día" me muestra el mensaje "no existen métodos de envío" o "sin servicio".

¿Me podrían guiar porqué se estaría generando este error? Muchas gracias!

**Comment by TCattd** [comment]
Chilexpress decide que envíos están disponibles, dependiendo de dos cosas: el origen de vuestra tienda (configurado en el plugin este) y el destino que selecciona el cliente para enviar el item que está comprando.

Si tu tienda tiene origen en Arica, y estás enviando a un cliente de Punta Arenas, es altamente probable que el envío Overnight y Día Hábil siguiente NO estén disponibles y Chilexpress ni si quiera los muestre.

En esa misma situación anterior, si configuraste tu tienda solo para mostrar envío Overnight y Día Hábil siguiente, al estar tu en Arica y el cliente en Punta Arenas, y al no dar chance a mostrar otros envíos como Día Hábil subsiguiente o más extensos, el plugin simplemente no mostrará tipos de envíos disponibles.

Eso es lo que se menciona acá: http://prntscr.com/itd97u
No se si muy claro, pero es la idea de aquella advertencia.

Dicho eso, esa opción está pensada para ocultar tipos de envíos a los que no quieres dar soporte, más que decir que envíos si serán visibles... puesto que eso lo decide Chilexpress automáticamente desde la API de ellos.

No se si me explico.

Básicamente esa opción sirve para ocultar el envío Overnight si es que está disponible en vuestro origen. Pero con libertad total para ocultar otros tipos de envío... si saben lo que están haciendo.

Resumen: no debería desactivar envíos a día subsiguiente y tercer día hábil. Nunca. Clientes de lejos del origen de tu tienda no podrán comprar y pedir por Chilexpress si haces eso.
A menos que tengas una buena excusa, no deberían hacerlo.

Saludos ;)
Esteban
