### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Birkoffzerone** [whooohq/whq-woocommerce-chilexpress-shipping#74]
Al tratar de activar el plugin me tira este error.
Fatal error: Can't use function return value in write context in /home/seedsmonkey/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 50

Espero que se pueda arreglar. Saludos.

**Comment by TCattd** [comment]
Por favor, estimado: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?q=is%3Aissue+Can%27t+use+function+return+value+in+write+context+is%3Aclosed

Actualizar versión de PHP.

Saludos ;)
Esteban
