### ISSUE TITLE
no se puede continuar la compra.

### ISSUE THREAD

**Issue by patazito** [whooohq/whq-woocommerce-chilexpress-shipping#75]
Estimados

tengo el siguiente problema , cuando activo el plugin  ya no  se puede continuar el proceso de compra

WordPress 4.9.4 - woocommercer 3.3.4  

espero su respuesta, gracias por su ayuda

**Comment by TCattd** [comment]
@patazito, tienes la tienda montada en vivo de casualidad para poder entrar a mirar?

Gracias

**Comment by patazito** [comment]
prueba ahi
https://www.sublinnovate.cl/producto/producto-3/

gracias por la rapidez

**Comment by TCattd** [comment]
Tienes un problema de js en tu tema actual seleccionado en WP: http://prntscr.com/ixnbjw

Te recomiendo instalar este theme https://woocommerce.com/storefront/ (gratuito), y volver a probar con aquel theme activado. Con eso descartas que no sea o no un problema de tu theme.

**Comment by patazito** [comment]
pero si yo saco el plugin puedo comprar, me podrias decir como arreglar lo del js que molesta, porque no es opcion cambiar el theme,

**Comment by TCattd** [comment]
Para poder saber si es tu theme el que tiene un problema de incompatibilidad o no, debes probar primero con el theme que WooCommerce recomienda por defecto, que es Storefront.

Puedes ayudarte de este plugin https://wordpress.org/plugins/wp-theme-test/ para luego activar el theme (Storefront) solo para ti como administrador, y probar el proceso de compra.

Si la compra usando Storefront funciona, recién ahí podemos asegurar que existe algún problema en tu theme o algo similar.

Eso, estimado. Espero se comprenda.
Cualquier duda, comentas, por favor.

**Comment by patazito** [comment]
si entiendo compañero

yo ya confirme que no es compatible con el plugin, ya probe eso y funciono, si el problema es que no puedo cambiar el theme solo por eso, entonces por eso pregunto si me puedes dar una guia de como solucionar este problema

**Comment by TCattd** [comment]
Eso es lo que necesitaba saber primero, @patazito, que no era problema del plugin si no del theme, para no dar palos de ciego con el problema.
No me había quedado claro antes si habías realizado ese descarte o no.
Lo siento.

Tengo claro que no es tu intención cambiar el theme. No es la idea tampoco. Pero...

Lamentablemente se requiere poder entrar a ver el sitio (admin) y el servidor donde lo tienes alojado (acceso sftp, shell, etc), y lo que a mi personalmente me pesa: tiempo... se requiere tiempo... como para debugear el problema que tienes con tu theme hoy.

El menester nuestro se cumple cuando el plugin funciona correctamente con el theme default que WooCommerce recomienda; solo así podemos asegurarnos que no quebramos nada que WooCommerce necesite, y que el plugin debe funcionar bien con themes que respetan los defaults tanto de WordPress como de WooCommerce.

Necesitas ayuda de un desarrollador para ver el problema con tu theme y resolver el conflicto, estimado. Parte viendo los errores JS que da la consola de Chrome, y trata de ver por qué ocurren.

Nuevamente, lo siento, no puedo ayudar más allá, acá.
