### ISSUE TITLE
Listado de regiones y comunas/ciudades?

### ISSUE THREAD

**Issue by masterbip** [whooohq/whq-woocommerce-chilexpress-shipping#76]
Hola. Disculpen la pregunta que puede ser tonta.

En la demo que tienen vemos el listado de comunas/ciudades y regiones, como selector.

En una demo rapida que tengo en http://demo.masterbip.com/finalizar-compra/ veo los selectores correctamente...

Sin embargo en el sitio en el que estoy probando el plugin (http://www.casaruralcurico.cl/finalizar-compra/) no se generan los selectores, y no tengo nada que este modificando el carro o algun plugin extraño para eso salvo el de flow para los pagos online ...

Que podria ser?
Podrian dare una mano?

Gracias!

**Comment by TCattd** [comment]
Mismo consejo: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/75#issuecomment-376966489

Luego, prueba desactivando el plugin aquel (flow) y ve si aparece el select de Regiones y Comunas.

Si no para nada, puedes ir probando desactivando otros plugins (o todos) para ver si se normaliza todo. Luego ir reactivando uno a uno esos plugins e ir viendo cuál es el que quiebra el finalizar compra de WC.

**Comment by masterbip** [comment]
Te pasaste por la rapida respuesta. Precisamente iba a hacer eso ahora.
Dejare Woo y Chilexpress solamente activos y de ahi ire probando. Espero que no sea el de Flow que es para lo de los pagos online .... Gracias!

**Comment by masterbip** [comment]
Hola nuevamente.
Hice de todo. Deshabilite los plugins, inclusive volvi al theme por defecto y sigue sucediendo lo mismo.
Region/Ciudad no se ven como selector... :-(

Entonces solo me queda suponer ... tendrá relacion con el SOAP? Debo contactar con el proveedor de hosting para habilitar/validar que SOAP funcione correctamente?

Hay alguna manera de revisarlo?

Muchisimas gracias nuevamente y disculpa otra vez por la molestia.

**Comment by TCattd** [comment]
El plugin verifica, durante la activación, que tengas instalada la extensión SOAP en PHP.
No debería dejarte activarlo si no tienes la extensión andando.

Podrías subir este archivo a tu host: https://github.com/TCattd/wc-webpay-reqcheck y abrirlo en el navegador. Te va a decir si tienes SOAP activado (no es para este plugin, pero verifica lo mismo en cuanto al SOAP por lo menos).

Revisa la consola de Chrome. Puede haber errores de js que estén evitando que el checkout funcione correctamente.

**Comment by masterbip** [comment]
Bueno ... sucede que desactive todo plugin y estoy utilizando el theme por defecto. Se que no hay errores javascript. Ademas la consola no muestra nada.

http://www.casaruralcurico.cl/webpayreqcheck.php
Todo en orden

Sera que los productos aun no tienen dimensiones?

No se me ocurre nada mas... :-(

Agradezco tu gentileza y disposicion.

**Comment by masterbip** [comment]
Mira que curioso ... en las opciones del plugin habia realizado el cambio de "Origen de los envios" ... la configuracion básica. Presione guardar y recargo ... segui trabajando ...
Ahora accedi nuevamente y al parecer no habia guardado los cambios pues seguia diciendo ACHAO ... es decir no se habian guardado las configuraciones....

Ahora funciona bien. Que quede registro igual para otros por si les sucede lo mismo.

Gracias nuevamente por tu gentileza.

**Comment by TCattd** [comment]
Excelente. Gracias por volver y comentar, estimado.

Buen día! ;)

**Comment by rodoccl** [comment]
Sólo para que quede registro. El plugin de Chilexpress ya no funciona :-(

**Comment by TCattd** [comment]
@rodoccl ¿Qué error tienes?

**Comment by rodoccl** [comment]
No cargan todas las comunas. Por ej en Los Lagos carga solo 2 comunas.

Saludos
Rodolfo.

**Comment by TCattd** [comment]
@rodoccl https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/128

**Comment by rodoccl** [comment]
Gracias Esteban. Lo probaré.

Saludos
Rodolfo.
