### ISSUE TITLE
Error al Activar el Plugin

### ISSUE THREAD

**Issue by andreschiponti** [whooohq/whq-woocommerce-chilexpress-shipping#77]
Buenas Noches, vi la demo y está excelente, lo malo es que no puedo activar el Plugin ya que me aparece este error:
**_Fatal error: Can't use function return value in write context in /home/barrilit/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 50_**

Les agradeceré indicarme por dónde puedo revisar, aparentemente se refiere a un error de un Plugin, revisando no debería haber incompatibilidad, quizá es un problema con el servidor.
Saludos

**Comment by TCattd** [comment]
Por favor, estimado: https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?q=is%3Aissue+Can%27t+use+function+return+value+in+write+context+is%3Aclosed

Actualizar versión de PHP.

Saludos ;)
Esteban
