### ISSUE TITLE
Limitar envío solo a sucursales de Chilexpress

### ISSUE THREAD

**Issue by AnglDavd** [whooohq/whq-woocommerce-chilexpress-shipping#79]
es posible de alguna manera hacer que el plugin de la opcion de elegir exclusivamente las sucursales?

**Comment by TCattd** [comment]
No existe actualmente una opción para algo como eso.

Entiendo como podría ser útil si. Totalmente.

Dejo abierto por si alguien quiere contribuir (bienvenido sea) ;)

Esteban

**Comment by truchosky** [comment]
donde está la documentacion de la Api de chilexpress?, alguien la tiene ?

**Comment by AnglDavd** [comment]
[Servicios de Integración - GeoReferencia.pdf](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/1961210/Servicios.de.Integracion.-.GeoReferencia.pdf)

[Servicios de Integración -Tarificación.pdf](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/1961211/Servicios.de.Integracion.-Tarificacion.pdf)

[CamposTrackingPush.xlsx](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/1961212/CamposTrackingPush.xlsx)
[Servicios de Integración -Tracking Push.pdf](https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/files/1961213/Servicios.de.Integracion.-Tracking.Push.pdf)

Chilexpress una vez me envió esta documentación cuando trataba de hacer una integración, quizás ayude en algo.

**Comment by TCattd** [comment]
Uno de los motivos por el cuál no he compartido la documentación públicamente, es porque no tengo idea de cual es la licencia y/o los términos de uso y condiciones de esa documentación.
Finalmente, son propiedad de Chilexpress.

Como dice @AnglDavd , Chilexpress mismo la envía cuando uno desea integrarse a su plataforma. Pero entiendo también que Chilexpress suele no responder inmediatamente... o nunca... los emails. Por experiencia propia lo digo: al día de hoy aún no responden un email respecto a una duda técnica que tuve, cuando lanzamos la versión 1.0 de este plugin. Aquel correo lo di por perdido.

Por posibles inconvenientes legales es que no repartimos la documentación aquí libremente, estimado.
Como pueden ver acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/22#issuecomment-319655903

Si alguien desea hacerlo por su cuenta, como lo hizo @AnglDavd , corren por vuestra cuenta.

Ni yo ni quienes patrocinan este plugin vamos a hacerlo, a menos que Chilexpress nos saque de esa duda (o la entreguen libremente en su sitio, que sería lo ideal la verdad).

Espero se comprenda.

Saludos,
Esteban

**Comment by dsovino** [comment]
Buenas estimados. Alguien realizó algún tipo de avance en esto? 

Necesito implementar precisamente esto, que en función de la región seleccionada, liste las sucursales disponibles en dicha región. El envío sería por pagar. 

Estoy evaluando si es mejor extender el plugin, o simplemente realizar un "envío gratis" dinámico consumiendo la api de ChileExpress para poder hacer el tema de la selección de la oficina.

Quedo atento a sus comentarios, que serían de gran ayuda.

Saludos

**Comment by TCattd** [comment]
"help wanted", estimado. Cualquier ayuda y PR sobre todo es gratamente bienvenido ;)

El tiempo es escaso, lamentablemente.

**Comment by TCattd** [comment]
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/discussions/248
