### ISSUE TITLE
Problema plugin "no disponible"

### ISSUE THREAD

**Issue by romaincimenta** [whooohq/whq-woocommerce-chilexpress-shipping#80]
Hola, 
Disculpa para mi español, soy francés, asi que no hablo muy bien .. 
No sé si es solo mi, pero parece que el plugin no funciona ..  puede ver que incluso en la demostración no funciona, es marcado "no disponible". 
Una solucion ? 
Le agradezco por su ayuda, 
Saludos, 
Romain.

**Comment by TCattd** [comment]
Estimado,

Hasta no ingresar los datos de envío en el checkout (todos los requeridos por WooCommerce), lo que incluye la región y ciudad, WooCommerce no procesa el carro para cálculo de costo de envío.

Más aún: sin saber la región y la ciudad, Chilexpress no puede calcular el costo del envío.

Una vez ingresados esos datos, pueden ver que calculará correctamente el precio de envío y Chilexpress estará seleccionable.

Si aún después de eso continuas con problema, por favor leer https://wordpress.org/plugins/woo-chilexpress-shipping/#faq item "¿Chilexpress caído? (Chilexpress no disponible)".

Hay diversos factores de conectividad a los servidores de Chilexpress que no controlamos. Si ellos tienen problemas o están con intermitencias en el servidor donde mantienen la API, no podemos hacer nada al respecto.

Saludos,
Esteban

PD: you can use english here if you want and if that make it more easy for you. No problem ;)

**Comment by PatrickCaneloDigital** [comment]
Voy a aprovechar la ocasión para hacer otra consulta al respecto:
En un sistema productivo el cliente me avisó ayer de una compra que entró con costo de envio cero y la indicación Chilexpress (Sin servicio)
Sin poder hacer mayor analysis, asumo que en un momento la api de chilexpress estaba caida.

El plugin al parecer no posee un mecanismo de bloqueo para este caso, en el cual no hay costo de envio por la API, es decir el cliente igual puede finalizar la compra, pese que diga costo "0"
No se puede bloquear por ultimo el boton de finalizar compra mientras este elegido "Chilexpress (Sin servicio)"???

**Comment by TCattd** [comment]
@PatrickCaneloDigital existe ese mecanismo, en teoría. Lo trabajamos, si no me equivoco, hace un buen tiempo, con ayuda de la comunidad acá.

Pero si crees que hay problemas, por favor, abre un issue nuevo y lo vemos. Nunca está de más ;)

**Comment by TCattd** [comment]
For the OP,

It was a Chilexpress's API outage, apparently.
I even got that error when working in issue #81 

Now it's working fine at the demo site: http://prntscr.com/jcx6f2

In front of that kind of problems (Chilexpress API outages) i'm afraid we can't do anything. Just wait. Sorry.
