### ISSUE TITLE
Chilexpress no disponible

### ISSUE THREAD

**Issue by IsaiasUziel** [whooohq/whq-woocommerce-chilexpress-shipping#83]
Primeramente, antes de seleccionar la opción de envío vía chilexpress ya aparece como "No disponible" al momento de seleccionar me aparece el mensaje de que no está disponible por ahora, que lo intente mas tarde.
Sin embargo espero un tiempo prudente para volver a intentarlo y sigue con el mismo problema.

Adjunto captura
![image](https://user-images.githubusercontent.com/31748165/40378032-658be788-5dc0-11e8-946c-a9367662fa90.png)

**Comment by TCattd** [comment]
Estimado,

Sin problemas funcionando en el demo online http://wpchilexpress.whooohq.com/cart/

Ver "¿Chilexpress caído? (Chilexpress no disponible)" en el FAQ del plugin, por favor: https://wordpress.org/plugins/woo-chilexpress-shipping/#faq

No hay mucho más que pueda hacer por ti en estos momentos.
Debes debugear por vuestro lado. Puedes ver otros issues similares para tener ideas, por acá https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Chilexpress+no+disponible
Lo siento.

Esteban
