### ISSUE TITLE
Error detectado soap.call.php Linea 53

### ISSUE THREAD

**Issue by juanchomix** [whooohq/whq-woocommerce-chilexpress-shipping#85]
He instalado el plugin y los felicito por su gran trabajo. Que el plugin funciona funciona, pero tal como ustedes lo indican es incompatible con algunos plugin que modifican el checkout siempre que se elimine el pais (Ese fue mi caso) pero finalmente pude hacerlo funcionar.

Eso si un error, que especulo fue por el flujo de consultas debido al ciber day pero igual se los dejo para que comenten. 

Lo otro: Me pueden indicar con que versión de PHP es la más apropiada para el buen funcionamiento del plugin¿?

Gracias!!

El error se encuentra en la línea 53 del fichero woo-chilexpress-shipping/includes/soap_call.php 

[28-May-2018 22:46:02 UTC] PHP Fatal error: SOAP-ERROR: Parsing Schema: can't import schema from 'http://qaws.ssichilexpress.cl:80/GeoReferencia?SCHEMA%2FPX_CorpGeoReferencia%2FPX000014_GeoReferencia%2FSpecification%2FWSDL%2FPX000014_CorpGR_ConsultarCoberturaRequest' in

**Comment by TCattd** [comment]
PHP 5.6 o superior.
Ha sido probar con PHP 7.0 y PHP 7.1, sin problemas igual.

Exacto, ese error fue por el colapso de sus servidores.
Igual podríamos hacer algo, detectar si ese server está abajo, y no dejar que el plugin intente continuar.

Duda:
¿Haciendo qué viste ese error?
¿Cargando una página del administrador?
¿Viendo el carro de compras o el checkout?
¿En cualquier página del sitio?
¡Gracias!

**Comment by Wenape** [comment]
También me apareció este error ayer. Puede ser como dices @juanchomix por el CyberDay. Pero también puede ser algún problema con la nueva actualización de Woocommerce que justamente apareció hace poco.

`PHP Fatal error:  SOAP-ERROR: Parsing Schema: can't import schema from 'http://qaws.ssichilexpress.cl:80/TarificarCourier?SCHEMA%2FPX_CorpValorizaCourier%2FPX000040_ValorizarCourier%2FSpecification%2FWSDL%2FPX000040_OpValorizarCourierResponse' in /var/www/html/wp-content/plugins/woo-chilexpress-shipping/includes/soap_call.php on line 53, referer: /wp-admin/admin.php?page=wc-settings&tab=shipping&section=chilexpress`

El error aparece cuando el plugin intenta calcular el costo de envió en la pagina de "Finalizar Compra". El plugin termina mostrando siempre la misma y única opción, independiente de la ubicación: 

`Envío vía Chilexpress (No Disponible): $0`

**Comment by juanchomix** [comment]
En mi caso estaba trabajando con la versión anterior de WOO y cuando llegó la actualización de WOO, por seguridad, primero actualice el plugin en localhost y todo funcionó perfectamente para luego actualizar mi sitio web y funcionó en forma normal hasta que llego el ciber day por lo que, creo, muy probale sea error provocado por eso. Ahora bien lo otro es que la casilla para seleccionar los modos de envios del plugin dejó de funcionar. Es ahi donde, creo, es posible la actualización de WOO alla afectado el plugin.

**Comment by TCattd** [comment]
Había probado en el sitio demo http://wpchilexpress.whooohq.com y funcionaba.
Pero ya no.

Tienen razón. Está abajo.

Ahora, el plugin está haciendo lo que debe cuando no logra llegar al servidor de Chilexpress. Muestra Chilexpress como no disponible.

Si la API sigue abajo, no podemos hacer mucho más. Simplemente esperar.
No es algo que podamos solucionar por nuestro lado.

Voy a dejar abierto el issue, por si llega más gente por esto.
Pero, reitero lo ya mencionado: no hay mucho que podamos hacer acá. Solo esperar hasta que la API de Chilexpress vuelva a responder correctamente.

**Comment by juanchomix** [comment]
Toda la razón y mejor argumento que el tuyo no hay...Saludos y gracias por la solución y actualización del plugin!! Felicitaciones
