### ISSUE TITLE
Tipos de Envio Soportados no guarda los cambios

### ISSUE THREAD

**Issue by juanchomix** [whooohq/whq-woocommerce-chilexpress-shipping#86]
Al intentar elegir los tipos de envio soportados dentro de la configuración del plugin, por alguna razón y luego de la actualización de la nueva versión de WOO no se puede guardar los cambios seleccionados en las opciones que se enlistan.
![error](https://user-images.githubusercontent.com/39717982/40637175-4d71b9e6-62d1-11e8-8e6f-654c68aa1512.png)

**Comment by TCattd** [comment]
Confirmado, lo puedo reproducir acá.
Vamos a ver que es.

Gracias ;)

**Comment by TCattd** [comment]
Se lo que es. Va el fix en unos minutos.

**Comment by juanchomix** [comment]
Efectivamente, luego de tu actualización del plugin 1.3.13 ya puedo visualizar en el Carrito y Checkout el cálculo del envío correctamente.!!! funcionando al 100%.

Gracias por el soporte y la atención. Muy profesional de su parte. Felicitaciones!!

**Comment by TCattd** [comment]
Gracias a ti @juanchomix por dar el aviso ;)

**Comment by juanchomix** [comment]
Como un último comentario recién hace unos minutos se liberó una nueva actualización de WOO por lo que hay que estar atentos a los cambios que puede provocar en el plugin. Comenten cualquier variación
