### ISSUE TITLE
Problemas al activar plugin

### ISSUE THREAD

**Issue by svaldebenitog** [whooohq/whq-woocommerce-chilexpress-shipping#88]
Estimados, instale el plugin pero al darle activar me arroja error 403

Forbidden
You don't have permission to access /wp-admin/plugins.php on this server.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Probé instalando otros plugin y no hay problemas.

Favor su ayuda

**Comment by TCattd** [comment]
Estimado,

Para poder saber que ocurre, debes ver el log de errores del servidor.
Repite la acción, gatilla el error, y luego de eso ve el log de errores del servidor. Debería salir el motivo ahí.
Sin ese dato, es difícil poder ayudarte.

Quedo atento.

Esteban

**Comment by TCattd** [comment]
¿Alguna novedad, estimado?

**Comment by svaldebenitog** [comment]
Estimado,

Logre dar con el problema, era un error por la versión de SOAP, la
actualice y funciono sin problemas.

Muchas gracias

**Comment by TCattd** [comment]
Bueno saberlo, estimado.

Sería bueno que nos compartieras, si puedes, la versión anterior de SOAP que tenías instalada (la que te daba error). Por favor.
Para ayudar a alguien más a futuro.

¡Gracias desde ya!

Esteban

**Comment by svaldebenitog** [comment]
La versión de Soap que estaba instalada (creo que era la 5.4) no era
compatible con la versión de PHP que estaba corriendo el servidor (7)
instale los modulos para todas las versiones y funciono sin problemas.

Muchas gracias por todo

**Comment by TCattd** [comment]
Gracias estimado ;)
