### ISSUE TITLE
Cambio de orden en fields city and state

### ISSUE THREAD

**Issue by carlosromanxyz** [whooohq/whq-woocommerce-chilexpress-shipping#89]
Tomando en cuenta la experiencia de usuario.

Es posible cambiar el orden de los campos de ciudad y región?

Un usuario tiende a seleccionar primero la región para "desbloquear" la selección de comunas y no al revés como se encuentra hoy.

![fireshot capture 12](https://user-images.githubusercontent.com/20117120/41060833-cbe66ca8-699e-11e8-86e4-2961b9c7f5d7.png)

Agradecido.

**Comment by TCattd** [comment]
Estimado

La solución entregada acá, aún funciona:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/19#issuecomment-317432138
(Ahí mismo el motivo de por qué no agregamos algo así al plugin)

Buen día ;D

**Comment by carlosromanxyz** [comment]
Tiene sentido, muchas gracias!

Resuelto con plugin.
