### ISSUE TITLE
No cargan comunas y regiones

### ISSUE THREAD

**Issue by rorozamorano** [whooohq/whq-woocommerce-chilexpress-shipping#9]
Estimados después de haber tenido el plug-in funcionando ok por unos dias, ahora no me carga las comunas http://prntscr.com/ftpds8 y regiones http://prntscr.com/ftpdyw en los select. 

Probe desactivando todos los plug-ins del sitio y también con una instalación nueva.

Alguna idea de lo que podrá ser?

**Comment by TCattd** [comment]
Lamentablemente el plugin depende de la API de Chilexpress.
Si el servicio de ellos cae, el plugin también.

Probé recién con un sitio donde está andando el plugin, y veo las ciudades y regiones sin inconvenientes.

Quizás lo que podríamos hacer es que, si la API de Chilexpress cae, permitir que los usuarios escriban su ciudad y región a mano, como es tradicional en WooCommerce, para no quebrar el flujo de compra en ningún sitio solo por Chilexpress.

Pero claro, eso evitaría poder calcular precios con Chilexpress cuando su API cae, por lo que no sería posible usarlo tampoco (como método de envío) cuando eso ocurre.

Como salva-guarda en caso de caida de la API de Chilexpress, sería bueno tenerlo en consideración si.

Lo voy a ver apenas tenga tiempo.

**Comment by rorozamorano** [comment]
Gracias por la respuesta. 

Eso debe haber sido ya que ahora si está funcionando.
Cuando no me cargaban probé el tarificador de Chilexpress http://www.chilexpress.cl/cotizador-envios-de-encomiendas-tarifas y estaba funcionando sin problemas. Ese tarificador no usa los mismos datos que el plugin?

**Comment by TCattd** [comment]
La verdad: no tengo idea que sistema usa la web de Chilexpress.

Como el servicio (Chilexpress) y la web de ellos mismos existe desde antes de la API para integración de terceros (lo que usamos en este plugin), es probable que la web de ellos (y sus sistemas en oficinas) usen otro acceso para calcular costos de envío. Puedo presumir que es así, pero no puedo estar 100% seguro de eso (no trabajo para ellos).

De todos modos el tema de la caída de la API de Chilexpress es algo que el plugin debería tener en cuenta, para no dejar inutilizada la venta desde WooCommerce.

Lo voy a ver, estimado.

**Comment by rorozamorano** [comment]
Muchas gracias, estaré atento a las novedades. Saludos

**Comment by TCattd** [comment]
http://prntscr.com/fu1x0p

El campo no es seleccionable mientras Chilexpress esté abajo (simulado bloqueando el acceso a la API de Chilexpress desde el router en casa para estar 100% seguro).

Cuando eso ocurre, WooCommerce vuelve al estado anterior (donde los usuarios pueden escribir a mano su ciudad y región), y pueden seleccionar otros métodos de envío si existen. De esa forma no se entorpece el funcionamiento de la tienda mientras Chilexpress esté abajo (y claro, no se puede usar Chilexpress tampoco, nada que hacer si están caidos).

En unos minutos más va la actualización.

Gracias @rorozamorano por reportar esto ;)

**Comment by rorozamorano** [comment]
Genial, gracias ;)
