### ISSUE TITLE
Como puedo hacer despacho gratis solo en RM

### ISSUE THREAD

**Issue by jpccea** [whooohq/whq-woocommerce-chilexpress-shipping#90]
Hola me gustaría saber si hay una opción de poner despacho gratis solo en la región RM
es posible???

**Comment by TCattd** [comment]
Eso es configuración de WooCommerce https://docs.woocommerce.com/document/free-shipping/ no del plugin de Chilexpress.

Si usas las zonas de WC, puedes seleccionar free shipping según localidad.

Lamentablemente no puedo ayudarte más ahí, estimado.

Saludos,
Esteban
