### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by Carlillo** [whooohq/whq-woocommerce-chilexpress-shipping#91]
Antes que todo, Muchas!!!! Gracias!!!! Al creador/es de esto realmente lo encuentro genial, mi consulta es la siguiente, cuando quiero poner en el envío "Tercer día", y al guardar con esa característica me sigue apareciendo en el carrito "Día hábil siguiente", alguna sugerencia?, de ante mano muchas gracias nuevamente.

Saludos!

**Comment by TCattd** [comment]
Estimado,

Es la API de Chilexpress la que decide que métodos de envío mostrar, e ignoro cuál es la lógica que usan para decidir que método no ofrecerán en ciertas ocasiones.

La opción que dimos está orientada básicamente a **si ofrecerán o no el servicio overnight siempre, siempre y cuando esté disponible para el tramo que debe recorrer el paquete**, según el origen de los envíos y el destino del paquete.

Me explico.

Si tu origen es Santiago y el envío va a Rancagua, es altamente probable que exista un envío overnight, por el tramo (es corto). Aunque no puedo estar 100% seguro, porque no trabajo en Chilexpress. Puedo asumir si que será el caso y habrá un servicio ultra expreso para esa distancia.

Al otro lado de la moneda, tienes un caso donde tu tienda está en Arica, y alguien compra desde Punta Arenas. Por ningún motivo creo que Chilexpress de la opción de envío overnight, y ni siquiera uno para el día hábil siguiente. Es probable que lo único que puedan ofrecer sea para el "tercer día" (el de espera más extensa que tienen).

Ahora, si el envío (destino) es muy cercano al origen seleccionado en tu tienda, la API de Chilexpress puede simplemente obligarte a seleccionar un envío de "día hábil siguiente", no importando si tu quieres uno al "tercer día". Me imagino que tener un paquete en bodega a ellos les cuesta (el espacio es limitado), así es que no tiene sentido ofrecer "tercer día" si el paquete llegará igual al día siguiente, y lo van a tener que mantener a la espera en la central o sucursal.

Finalmente,
La opción que tienen en la configuración tendrá que ser tratada con cuidado, según cuál sea la ubicación de su tienda (origen, desde donde harán los envíos).

En esa configuración, como dije anteriormente, lo que deberían considerar es si activar o no el envío overnight y/o ultra rápido.
La decisión final la toman ustedes como dueños de las tiendas.

El default de esa opción es el que muestro acá: http://prntscr.com/jxp2ee
Y es el que recomendamos ahí mismo en la descripción de aquella opción.
