### ISSUE TITLE
Pregunta: ¿Alguien puede desarrollar algo como esto, pero versión Starken?

### ISSUE THREAD

**Issue by alonsillou** [whooohq/whq-woocommerce-chilexpress-shipping#92]
Necesito el mismo plugin, pero con las tarifas de starken, si alguien pude ayudarme dejo mi email : alonsosepur@*******

**Comment by TCattd** [comment]
Estimado,

Lo lamento, pero no es lugar para solicitar trabajos.
Mucho menos si no tienen que ver con el plugin directamente.

Esteban
