### ISSUE TITLE
Fatal Error al intentar activar el plugin

### ISSUE THREAD

**Issue by ortokore** [whooohq/whq-woocommerce-chilexpress-shipping#93]
Hola! - les escribo porque tengo días intentando activar el plugin en el sitio de un cliente y no he podido, siempre me tira el siguiente error:

El plugin no ha podido activarse porque ha provocado un error fatal.
Fatal error: Can't use function return value in write context in /home/twsc2017/public_html/wp-content/plugins/woo-chilexpress-shipping/includes/wordpress.php on line 65

Mi teoría es que es un asunto entre plugins, revisé la documentación de los plugins incompatibles y sólo tenemos uno que es parcialmente incompatible (Woo Checkout Fields, inclusive desactivando el plugin, continúa el error. 

¿Alguna idea de qué podría ser? gracias de antemano a cualquier ayuda!

Corriendo la última versión del plugin (1.3.13), última de Woocommerce (3.4.3) y última de Wordpress  (4.9.6)

**Comment by TCattd** [comment]
Por favor:

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues?q=is%3Aissue+Can%27t+use+function+return+value+is%3Aclosed

Actualizar versión de PHP.
