### ISSUE TITLE
Sin servicio a pesar de salir el precio calculado al momento de checkout

### ISSUE THREAD

**Issue by fserrano88** [whooohq/whq-woocommerce-chilexpress-shipping#94]
Estuvo funcionando impecable el plugin, pero de un momento a otro cuando quiero pagar el carro de compras, aparece el valor del servicio chilexpress pero no seleccionado. Cuando lo selecciono se borra el valor y aparece el "SIN SERVICIO". También al intentar enviar el formulario, me aparece que debo rellenar la ciudad de facturación. Es como si el plugin estuviera eliminando ese campo, por lo cual pierde también el valor del envío y no me deja enviar el formulario de checkout de woocommerce. Al desactivar el plugin, me deja enviar correctamente el formulario sin asumir que no he rellenado el campo de la ciudad. 

¿A que se puede deber este error?.

**Comment by TCattd** [comment]
Estimado,

https://wordpress.org/plugins/woo-chilexpress-shipping/#faq
Ver item: ¿Chilexpress caído? (Chilexpress no disponible).
Eso es lo que debes revisar para tu problema del "Sin Servicio".

Respecto al otro problema, revisar el item "¿Problemas generales, visuales (glitches) y/o funcionales en el carro o finalizar compra (checkout)?" en el mismo FAQ. Revisar y seguir instrucciones ahí, por favor.

Como dato extra, en el sitio de pruebas está funcionando todo sin problemas:
http://wpchilexpress.whooohq.com/

Tanto en el carro http://prntscr.com/k027ol como en el checkout http://prntscr.com/k0289g

**Comment by fserrano88** [comment]
Muchas gracias, ya se corrigió el problema. Era un tema de otro plugin. Saludos y gracias.

**Comment by TCattd** [comment]
@fserrano88 sería de mucha ayuda si pudieras compartir el plugin con el que tuviste problema, y cuál fue la forma de resolverlo; si desactivaste alguna opción dentro del plugin, o si lo desactivaste y eliminaste por completo.

De esa forma, otros con problemas similares a futuro podrían saber que es lo que está causando su inconveniente.

Por favor.
