### ISSUE TITLE
Día Hábil Siguiente

### ISSUE THREAD

**Issue by jpccea** [whooohq/whq-woocommerce-chilexpress-shipping#95]
Hola estaba probando el plugin y en la parte del dia habil siguiente, lo borro pero al momento del calculo del producto me sigue saliendo que esta habilitado para el día habíl siguiente, que puede ser el error???

**Comment by TCattd** [comment]
Estimado,

https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/91#issuecomment-399170590
