### ISSUE TITLE
Primera vez que usaré este plugin, mi cliente tiene dudas sobre el flujo de chilexpress al usar el plugin

### ISSUE THREAD

**Issue by inger-garrido** [whooohq/whq-woocommerce-chilexpress-shipping#96]
Acudo a este medio, ya que va asociado al plugin
Las preguntas son las siguientes:

1). Chilexpress va a buscar los productos a la casa o uno tiene que ir directamente a chilexpress a mandar los productos?
2). Los valores calculados corresponden al envío a sucursal para que el cliente retire, o los valores son para que les lleguen a domicilio?
3). Solo funciona para chile?
4).Hay que pagar alguna comisión a chilexpress?

Son preguntas realizadas por el cliente, y como es primera vez que utilizaré este plugin, la idea es responderle lo mas clara posible estas preguntas.

**Comment by TCattd** [comment]
1. El plugin no tiene integración para generar la orden de transporte y que Chilexpress vaya a retirar el paquete. La tienda debe ir a hacer los envíos.

2. Son calculados respecto a la dirección, región y ciudad que el comprador selecciona en el checkout de WooCommerce.

3. No me parece que Chilexpress trabaje fuera de Chile. ¿No es así?.

4. Es un envío como cualquier otro el que realizarán. No hay nigún tipo de comisión extra, más allá del valor que Chilexpress entrega a través de su API, que es lo que deberán pagar en la sucursal para hacer el envío.
