### ISSUE TITLE
Integración con marketplace (Dokan)

### ISSUE THREAD

**Issue by fserrano88** [whooohq/whq-woocommerce-chilexpress-shipping#97]
Estimados,

Estoy usando el plugin de ustedes hace un tiempo y esta excelente. Actualmente estamos desarrollando un sitio estilo marketplace (lugar donde varios se crean cuentas y pueden subir sus propias tiendas y productos). Esta enfocado en el mercado local, por lo que chilexpress se abre como la opción para calcular el envío.

Tengo un par de dudas que me gustaría que me aclararan sobre el plugin.

1) El plugin actualmente solo toma una sola ubicación de envío? (la que se define en la configuración del plugin).
2) Si la respuesta anterior es afirmativa, es posible que me orientaran donde habría que modificar el plugin para aceptar multiples zonas de envío dependiendo la dirección definida para el usuario? (que es el que vende al fin de cuentas). Para hacer el marketplace, estamos usando el plugin pagado Dokan. 

Les agradezco el tiempo y la dedicación.
Saludos.

**Comment by TCattd** [comment]
1.- Si

2.- https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/blob/master/classes/WC_WHQ_Chilexpress_Shipping.php#L593
Ahí, $this->shipping_origin contiene la ciudad de origen del envío.

Creo que podría agregar una acción ahí, para que puedan poner un hook y alterar la ciudad de origen a través de otro plugin o código en general (dentro del functions.php de un theme por ejemplo).

De esa forma no tienen que modificar a mano el plugin y perder las actualizaciones.

Lo voy a ver.

**Comment by TCattd** [comment]
Andando en v1.4.0

El origen es filtrable ahora vía:
```
$this->shipping_origin               = apply_filters( 'whq_wcchp_shipping_origin', $this->get_option( 'shipping_origin' );
```

Con eso puedes sobre-escribir el origen del paquete a una ciudad/localidad diferente.

**Comment by screpone** [comment]
hola buenas consulta en la versión actual no encuentro opción para escoger diferentes ciudades de sucursal de origen?? esta vigente esa opcion @TCattd , saludos cordiales

**Comment by TCattd** [comment]
No existe aquello @screpone . No es un dato que la API SOAP de Chilexpress necesite para calcular el costo de envío.
Solo requiere la ciudad de origen nada más.

Esteban

**Comment by TCattd** [comment]
Por cierto, la configuración de ciudad funciona sin problemas.
Probado hoy: https://tppr.me/19Srx

**Comment by screpone** [comment]
mi duda que tengo hace tiempo que me tiene entrampado como el amigo del post tengo el dokan con muiltivendedores ejemplo uno de **Calama, Arica, Coquimbo** en la configuración del plugin solo me deja seleccionar 1 sucursal de origen ejemplo Calama, pero si compro al vendedor de **Arica** la API me calcula también de Calama, disculpando el atrevimiento estoy dispuesto a pagar por el tema.
Gracias por tu tiempo Esteban

**Comment by fserrano88** [comment]
Hola @screpone, 
Yo lo hice el 2018 modificando en su época el plugin directamente (ya que lo entregué antes de que Esteban hiciera la actualización del Plugin). 

Pero la solución propuesta por @TCattd es mucho más cómoda, ya que permite en otro plugin o en el functions.php, poder efectuar el cambio dinámico del origen (por ejemplo basándose en el que provee Dokan).

De esta manera, para cada cálculo, puedes cambiar el origen de forma dinámica, basándote en el de la tienda (de uno de los market) y no en el de la configuración del plugin (que sería el por defecto).

Ese proyecto fue hace 3 años así que no tengo el código ahora, pero analizando el plugin y el hook entregado por Esteban, te podrás hacer una idea rápido de donde editarlo.

Saludos y aprovecho de agradecer @TCattd ya que en su oportunidad no lo hice (se me pasó).

**Comment by screpone** [comment]
Gracias @fserrano88 , tratare de ver como resolverlo pero si tengo suerte, ojala tengas el código a mano por ahí ya que mis conocimientos en programación son casi nulos, saludos
