### ISSUE TITLE
Problema con calculo de envío

### ISSUE THREAD

**Issue by gibli2018** [whooohq/whq-woocommerce-chilexpress-shipping#98]
Hola! Increíble el plugin. Muchas gracias por desarrollarlo.

Pero llevo días tratando de resolver un problema. El plugin me calcula correctamente el envío para distintas ciudades de Chile, pero me dice que no hay métodos disponibles de envío al elegir alguna comuna de Santiago (exceptuando Pirque). Muy raro, sobretodo que anteriormente el plugin funcionaba impecable (de pronto surgió este problema). En zonas de envío coloqué Chile.
Mi sitio es www.tiendaentornoalvino.cl

Me podrían ayudar?
Desde ya muchas gracias!

**Comment by TCattd** [comment]
https://wordpress.org/plugins/woo-chilexpress-shipping/#faq
Ver item: ¿Chilexpress caído? (Chilexpress no disponible).

Si la API de Chilexpress no está respondiendo ok con algunas zonas, literalmente lo único que puedes hacer es esperar.

Habiendo dicho eso, el sitio de pruebas:
http://wpchilexpress.whooohq.com/
... responde correctamente. El plugin funciona sin inconvenientes ahí.

Debes revisar que no sea problema de conectividad de tu servidor con los de Chilexpress.
O, si pegaste en algún throttling del servidor de ellos (cosa que tampoco controlamos, y solo es teórico), lo único que te queda por hacer es esperar (también).
