### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by MarceloHauser** [whooohq/whq-woocommerce-chilexpress-shipping#99]
Hola, hasta hace algunas semanas yo utilizaba este plugin sin ningún problema, pero ahora no me aparece la opción cuando se solicita el pedido. Es como si el plugin estuviera desconectado pero he revisado una y otra vez y todo está en orden. Quisiera saber a que se puede deber. 
Saludos

**Comment by TCattd** [comment]
Estimado,

Lo mismo dicho acá:
https://github.com/whooohq/whq-woocommerce-chilexpress-shipping/issues/98#issuecomment-406048499

El punto de tener un sitio de pruebas (demo) funcional y público, es para que ustedes mismos puedan saber si el plugin aún está funcionando bien o no: http://wpchilexpress.whooohq.com/
Hoy lunes 23 de julio, lo veo funcionando bien: http://prntscr.com/k9wamq

Si pegaste en un límite de requests desde el servidor, o tu servidor no está pudiendo conectarse con el servidor de la API de Chilexpress, etc. no tengo como saberlo.
Esa "última milla" de debug es menester de ustedes, estimados.

Espero se comprenda.

Saludos,
Esteban
